- platform: template
  switches:
    chromecast_radio_mute:
      icon_template: '{% if states("switch.chromecast_radio_mute") %}mdi:volume-off{% else %}mdi:volume-high{% endif %}'
      value_template: >
        {% if is_state("input_select.chromecast_radio_speakers", "Conservatory") %} {% if state_attr("media_player.conservatory","is_volume_muted") %}on{% else %}off{% endif %}
        {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} {% if state_attr("media_player.kitchen","is_volume_muted") %}on{% else %}off{% endif %}
        {% elif is_state("input_select.chromecast_radio_speakers", "Living Room") %} {% if state_attr("media_player.living_room","is_volume_muted") %}on{% else %}off{% endif %}
        {% elif is_state("input_select.chromecast_radio_speakers", "House") %} {% if state_attr("media_player.house","is_volume_muted") %}on{% else %}off{% endif %}
        {% elif is_state("input_select.chromecast_radio_speakers", "Bedroom Nest Hub") %} {% if state_attr("media_player.bedroom_nest_hub","is_volume_muted") %}on{% else %}off{% endif %}
        {% elif is_state("input_select.chromecast_radio_speakers", "Office Nest Hub") %} {% if state_attr("media_player.office_nest_hub","is_volume_muted") %}on{% else %}off{% endif %}
        {% else %}off
        {% endif %}
      turn_on:
        service: media_player.volume_mute
        data:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "Conservatory") %} media_player.conservatory
            {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.kitchen
            {% elif is_state("input_select.chromecast_radio_speakers", "Living Room") %} media_player.living_room
            {% elif is_state("input_select.chromecast_radio_speakers", "House") %} media_player.house
            {% elif is_state("input_select.chromecast_radio_speakers", "Bedroom Nest Hub") %} media_player.bedroom_nest_hub
            {% elif is_state("input_select.chromecast_radio_speakers", "Office Nest Hub") %} media_player.office_nest_hub
            {% endif %}
          is_volume_muted: true
      turn_off:
        service: media_player.volume_mute
        data:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "Conservatory") %} media_player.conservatory
            {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.kitchen
            {% elif is_state("input_select.chromecast_radio_speakers", "Living Room") %} media_player.living_room
            {% elif is_state("input_select.chromecast_radio_speakers", "House") %} media_player.house
            {% elif is_state("input_select.chromecast_radio_speakers", "Bedroom Nest Hub") %} media_player.bedroom_nest_hub
            {% elif is_state("input_select.chromecast_radio_speakers", "Office Nest Hub") %} media_player.office_nest_hub
            {% endif %}
          is_volume_muted: false

    chromecast_radio_vol_up:
      icon_template: 'mdi:volume-plus'
      value_template: 'on'
      turn_on:
        service: media_player.volume_up
        data:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "Conservatory") %} media_player.conservatory
            {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.kitchen
            {% elif is_state("input_select.chromecast_radio_speakers", "Living Room") %} media_player.living_room
            {% elif is_state("input_select.chromecast_radio_speakers", "House") %} media_player.house
            {% elif is_state("input_select.chromecast_radio_speakers", "Bedroom Nest Hub") %} media_player.bedroom_nest_hub
            {% elif is_state("input_select.chromecast_radio_speakers", "Office Nest Hub") %} media_player.office_nest_hub
            {% endif %}
      turn_off:
        service: media_player.volume_up
        data:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "Conservatory") %} media_player.conservatory
            {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.kitchen
            {% elif is_state("input_select.chromecast_radio_speakers", "Living Room") %} media_player.living_room
            {% elif is_state("input_select.chromecast_radio_speakers", "House") %} media_player.house
            {% elif is_state("input_select.chromecast_radio_speakers", "Bedroom Nest Hub") %} media_player.bedroom_nest_hub
            {% elif is_state("input_select.chromecast_radio_speakers", "Office Nest Hub") %} media_player.office_nest_hub
            {% endif %}

    chromecast_radio_vol_down:
      icon_template: 'mdi:volume-minus'
      value_template: 'on'
      turn_on:
        service: media_player.volume_down
        data:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "Conservatory") %} media_player.conservatory
            {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.kitchen
            {% elif is_state("input_select.chromecast_radio_speakers", "Living Room") %} media_player.living_room
            {% elif is_state("input_select.chromecast_radio_speakers", "House") %} media_player.house
            {% elif is_state("input_select.chromecast_radio_speakers", "Bedroom Nest Hub") %} media_player.bedroom_nest_hub
            {% elif is_state("input_select.chromecast_radio_speakers", "Office Nest Hub") %} media_player.office_nest_hub
            {% endif %}
      turn_off:
        service: media_player.volume_down
        data:
          entity_id: >
            {% if is_state("input_select.chromecast_radio_speakers", "Conservatory") %} media_player.conservatory
            {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.kitchen
            {% elif is_state("input_select.chromecast_radio_speakers", "Living Room") %} media_player.living_room
            {% elif is_state("input_select.chromecast_radio_speakers", "House") %} media_player.house
            {% elif is_state("input_select.chromecast_radio_speakers", "Bedroom Nest Hub") %} media_player.bedroom_nest_hub
            {% elif is_state("input_select.chromecast_radio_speakers", "Office Nest Hub") %} media_player.office_nest_hub
            {% endif %}

    chromecast_radio_play:
      icon_template: 'mdi:play'
      value_template: 'on'
      turn_on:
        service: script.turn_on
        entity_id: script.play_chromecast_radio
      turn_off:
        service: script.turn_on
        entity_id: script.play_chromecast_radio

    chromecast_radio_stop:
      icon_template: 'mdi:stop'
      value_template: 'on'
      turn_on:
        service: script.turn_on
        entity_id: script.stop_chromecast_radio
      turn_off:
        service: script.turn_on
        entity_id: script.stop_chromecast_radio

