- platform: template
  switches:
    dafang_living_room_status:
      friendly_name: Dafang Living Room motion Status
      value_template: "{{ is_state('sensor.dafang_living_room_status_scrape', 'ACTIVE') }}"
      turn_on:
        service: shell_command.dafang_living_room_active
      turn_off:
        service: shell_command.dafang_living_room_pause

- platform: mqtt
  name: "DaFang Living Room RTSP"
  state_topic: "LivingRoom/DaFang/status"
  value_template: "{% if value_json[\"RTSP-Server\"] == 'running' %}h264_noseg_start{% else %}rtsp_stop{% endif %}"
  command_topic: "LivingRoom/DaFang/set"
  payload_on: "h264_noseg_start"
  payload_off: "rtsp_stop"
  optimistic: false

- platform: mqtt
  name: "Dafang Living Room Blue LED"
  state_topic: "LivingRoom/DaFang/leds/blue"
  # value_template: "{% if value_json.LEDs.Blue == 'on' %}blue_led_on{% else %}blue_led_off{% endif %}"
  command_topic: "LivingRoom/DaFang/leds/blue/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Dafang Living Room Yellow LED"
  state_topic: "LivingRoom/DaFang/leds/yellow"
  # value_template: "{% if value_json.LEDs.Yellow == 'on' %}yellow_led_on{% else %}yellow_led_off{% endif %}"
  command_topic: "LivingRoom/DaFang/leds/yellow/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Dafang Living Room Left Right"
  command_topic: "LivingRoom/DaFang/motors/horizontal/set"
  payload_off: "left"
  payload_on: "right"
  optimistic: false

- platform: mqtt
  name: "Dafang Living Room Up Down"
  command_topic: "LivingRoom/DaFang/motors/vertical/set"
  payload_off: "down"
  payload_on: "up"
  optimistic: false


- platform: template
  switches:
    dafang_kitchen_status:
      friendly_name: Dafang Kitchen motion Status
      value_template: "{{ is_state('sensor.dafang_kitchen_status_scrape', 'ACTIVE') }}"
      turn_on:
        service: shell_command.dafang_kitchen_active
      turn_off:
        service: shell_command.dafang_kitchen_pause

- platform: mqtt
  name: "DaFang Kitchen RTSP"
  state_topic: "Kitchen/DaFang/rtsp_h264_server"
  # value_template: "{% if value_json[\"RTSP-Server\"] == 'running' %}h264_noseg_start{% else %}rtsp_stop{% endif %}"
  command_topic: "Kitchen/DaFang/rtsp_h264_server/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Dafang Kitchen Blue LED"
  state_topic: "Kitchen/DaFang/leds/blue"
  # value_template: "{% if value_json.LEDs.Blue == 'on' %}blue_led_on{% else %}blue_led_off{% endif %}"
  command_topic: "Kitchen/DaFang/leds/blue/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Dafang Kitchen Yellow LED"
  state_topic: "Kitchen/DaFang/leds/yellow"
  # value_template: "{% if value_json.LEDs.Yellow == 'on' %}yellow_led_on{% else %}yellow_led_off{% endif %}"
  command_topic: "Kitchen/DaFang/leds/yellow/set"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false

- platform: mqtt
  name: "Dafang Kitchen Left Right"
  command_topic: "Kitchen/DaFang/motors/horizontal/set"
  payload_off: "left"
  payload_on: "right"
  optimistic: false

- platform: mqtt
  name: "Dafang Kitchen Up Down"
  command_topic: "Kitchen/DaFang/motors/vertical/set"
  payload_off: "down"
  payload_on: "up"
  optimistic: false



- platform: template
  switches:
    cctv_garage_status:
      friendly_name: CCTV Garage motion Status
      value_template: "{{ is_state('sensor.cctv_garage_status_scrape', 'ACTIVE') }}"
      turn_on:
        service: shell_command.cctv_garage_active
      turn_off:
        service: shell_command.cctv_garage_pause
