- platform: rest
  resource: http://192.168.0.24:8126/container/ddclient
  name: ddclient
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/dropbox
  name: dropbox
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/influxdb
  name: influxdb
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/grafana
  name: grafana
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/ha_dockermon
  name: ha_dockermon
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/eufy-bridge
  name: eufy_bridge
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/miscale
  name: miscale
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/mqtt
  name: mqtt
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/mysql
  name: mysql
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/swag
  name: letsencrypt
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/portainer
  name: portainer
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/watchtower
  name: watchtower
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/zigbee2mqtt
  name: zigbee2mqtt
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

# - platform: rest
#   resource: http://192.168.0.24:8126/container/zwavejs
#   name: zwavejs
#   body_on: '{"state": "start"}'
#   body_off: '{"state": "stop"}'
#   is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
#   timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/syncthing
  name: syncthing
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/vscode
  name: VS Code
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.0.24:8126/container/wordpress
  name: wordpress
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.9.23:8126/container/ha
  name: CCTV2 HA
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30

- platform: rest
  resource: http://192.168.9.23:8126/container/motion
  name: CCTV2 Motion
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
  timeout: 30