- platform: mqtt
  name: "Zigbee2MQTT Permit Join"
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json['permit_join']}}"
  command_topic: "zigbee2mqtt/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"
  state_on: true
  state_off: false
  optimistic: false
  qos: 1

- platform: mqtt
  name: "Xiaomi Garage Socket"
  state_topic: "zigbee2mqtt/xiaomi_garage_socket"
  value_template: "{{ value_json['state'] }}"
  command_topic: "zigbee2mqtt/xiaomi_garage_socket/set"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  optimistic: false
  qos: 1

- platform: mqtt
  name: "ZigBee Round Socket"
  state_topic: "zigbee2mqtt/zigbee_round_socket"
  value_template: "{{ value_json['state'] }}"
  command_topic: "zigbee2mqtt/zigbee_round_socket/set"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
  optimistic: false
  qos: 1