- platform: mqtt
  name: "RPi Kitchen Heartbeat"
  state_topic: "RPi_Kitchen/Heartbeat"
  icon: mdi:heart-pulse

- platform: mqtt
  name: "RPi Heartbeat"
  state_topic: "RPi/Heartbeat"
  icon: mdi:heart-pulse