- platform: mqtt
  name: "Lolo Weight"
  state_topic: "miScale/Lolo/weight"
  value_template: "{{ value_json['weight'] }}"
  unit_of_measurement: "kg"
  json_attributes_topic: "miScale/Lolo/weight"
  icon: mdi:scale-bathroom

- platform: mqtt
  name: "Lolo BMI"
  state_topic: "miScale/Lolo/weight"
  value_template: "{{ value_json['bmi'] }}"
  icon: mdi:human-pregnant
  unit_of_measurement: "kg/m2"

- platform: mqtt
  name: "Div Weight"
  state_topic: "miScale/Div/weight"
  value_template: "{{ value_json['weight'] }}"
  unit_of_measurement: "kg"
  json_attributes_topic: "miScale/Div/weight"
  icon: mdi:scale-bathroom

- platform: mqtt
  name: "Div BMI"
  state_topic: "miScale/Div/weight"
  value_template: "{{ value_json['bmi'] }}"
  icon: mdi:human-pregnant
  unit_of_measurement: "kg/m2"

- platform: mqtt
  name: "Kiaan Weight"
  state_topic: "miScale/Kiaan/weight"
  value_template: "{{ value_json['Weight'] }}"
  unit_of_measurement: "kg"
  json_attributes_topic: "miScale/Kiaan/weight"
  icon: mdi:scale-bathroom

- platform: mqtt
  name: "Kiaan BMI"
  state_topic: "miScale/Kiaan/weight"
  value_template: "{{ value_json['bmi'] }}"
  icon: mdi:human-pregnant
  unit_of_measurement: "kg/m2"