- platform: mqtt
  name: "Kitchen Fridge Temperature"
  state_topic: "zigbee2mqtt/kitchen_fridge"
  value_template: "{{ value_json['temperature'] }}"
  unit_of_measurement: 'ºC'
  device_class: temperature

- platform: mqtt
  name: "Kitchen Fridge Humidity"
  state_topic: "zigbee2mqtt/kitchen_fridge"
  value_template: "{{ value_json['humidity'] | float (1) }}"
  unit_of_measurement: "%"
  device_class: humidity

- platform: mqtt
  name: "Kitchen Fridge Temperature Battery"
  state_topic: "zigbee2mqtt/kitchen_fridge"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Master Bedroom Right Window Big Window Battery"
  state_topic: "zigbee2mqtt/master_bedroom_right_big_window"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Master Bedroom Right Window Small Window Battery"
  state_topic: "zigbee2mqtt/master_bedroom_right_small_window"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Master Bedroom Left Window Small Window Battery"
  state_topic: "zigbee2mqtt/master_bedroom_left_small_window"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Conservatory Skylight Left Battery"
  state_topic: "zigbee2mqtt/conservatory_skylight_left"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Pooja Room Small Window Battery"
  state_topic: "zigbee2mqtt/pooja_room_small_window"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Pooja Room Big Window Battery"
  state_topic: "zigbee2mqtt/pooja_room_big_window"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Xiaomi Garage Socket Watts"
  state_topic: "zigbee2mqtt/xiaomi_garage_socket"
  value_template: "{{ value_json['power'] }}"
  unit_of_measurement: "W"
  device_class: power

- platform: mqtt
  name: "Pooja Temperature"
  state_topic: "zigbee2mqtt/pooja_hygro"
  value_template: "{{ value_json['temperature'] }}"
  unit_of_measurement: 'ºC'
  device_class: temperature

- platform: mqtt
  name: "Pooja Humidity"
  state_topic: "zigbee2mqtt/pooja_hygro"
  value_template: "{{ value_json['humidity'] | float (1) }}"
  unit_of_measurement: "%"
  device_class: humidity

- platform: mqtt
  name: "Pooja Temperature Battery"
  state_topic: "zigbee2mqtt/pooja_hygro"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Master Bedroom Temperature"
  state_topic: "zigbee2mqtt/master_bedroom_hygro"
  value_template: "{{ value_json['temperature'] }}"
  unit_of_measurement: 'ºC'
  device_class: temperature

- platform: mqtt
  name: "Master Bedroom Humidity"
  state_topic: "zigbee2mqtt/master_bedroom_hygro"
  value_template: "{{ value_json['humidity'] | float (1) }}"
  unit_of_measurement: "%"
  device_class: humidity

- platform: mqtt
  name: "Master Bedroom Pressure"
  state_topic: "zigbee2mqtt/master_bedroom_hygro"
  value_template: "{{ value_json['pressure'] | float (1) }}"
  unit_of_measurement: "hPa"
  device_class: pressure

- platform: mqtt
  name: "Master Bedroom Temperature Battery"
  state_topic: "zigbee2mqtt/master_bedroom_hygro"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Bathroom Temperature"
  state_topic: "zigbee2mqtt/bathroom_hygro"
  value_template: "{{ value_json['temperature'] }}"
  unit_of_measurement: 'ºC'
  device_class: temperature

- platform: mqtt
  name: "Bathroom Humidity"
  state_topic: "zigbee2mqtt/bathroom_hygro"
  value_template: "{{ value_json['humidity'] | float (1) }}"
  unit_of_measurement: "%"
  device_class: humidity

- platform: mqtt
  name: "Bathroom Temperature Battery"
  state_topic: "zigbee2mqtt/bathroom_hygro"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Loft Temperature"
  state_topic: "zigbee2mqtt/loft_hygro"
  value_template: "{{ value_json['temperature'] }}"
  unit_of_measurement: 'ºC'
  device_class: temperature

- platform: mqtt
  name: "Loft Humidity"
  state_topic: "zigbee2mqtt/loft_hygro"
  value_template: "{{ value_json['humidity'] | float (1) }}"
  unit_of_measurement: "%"
  device_class: humidity

- platform: mqtt
  name: "Loft Temperature Battery"
  state_topic: "zigbee2mqtt/loft_hygro"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Bathroom Fan Switch Toggle"
  state_topic: "zigbee2mqtt/bathroom_hygro"

- platform: mqtt
  name: "Garage Freezer Temperature"
  state_topic: "zigbee2mqtt/garage_freezer_hygro"
  value_template: "{{ value_json['temperature'] }}"
  unit_of_measurement: 'ºC'
  device_class: temperature

- platform: mqtt
  name: "Garage Freezer Humidity"
  state_topic: "zigbee2mqtt/garage_freezer_hygro"
  value_template: "{{ value_json['humidity'] | float (1) }}"
  unit_of_measurement: "%"
  device_class: humidity

- platform: mqtt
  name: "Garage Freezer Temperature Battery"
  state_topic: "zigbee2mqtt/garage_freezer_hygro"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Kiaan Big Window Battery"
  state_topic: "zigbee2mqtt/kiaan_big_window"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Conservatory Door Lock Battery"
  state_topic: "zigbee2mqtt/conservatory_door_lock"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Aqara Toggle Pooja"
  state_topic: "zigbee2mqtt/aqara_toggle_pooja"
  value_template: "{{ value_json['click'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Aqara Toggle Pooja Battery"
  state_topic: "zigbee2mqtt/aqara_toggle_pooja"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Aqara Toggle Bathroom"
  state_topic: "zigbee2mqtt/aqara_toggle_bathroom"
  value_template: "{{ value_json['click'] }}"
  unit_of_measurement: "%"
  device_class: battery

- platform: mqtt
  name: "Aqara Toggle Bathroom Battery"
  state_topic: "zigbee2mqtt/aqara_toggle_bathroom"
  value_template: "{{ value_json['battery'] }}"
  unit_of_measurement: "%"
  device_class: battery


