- platform: mqtt
  name: "Kitchen Fridge Temperature Last Seen"
  state_topic: "zigbee2mqtt/kitchen_fridge_hygro"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Kitchen Freezer Temperature Last Seen"
  state_topic: "zigbee2mqtt/kitchen_freezer_hygro"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Master Bedroom Right Big Window Last Seen"
  state_topic: "zigbee2mqtt/master_bedroom_right_big_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Master Bedroom Right Small Window Last Seen"
  state_topic: "zigbee2mqtt/master_bedroom_right_small_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Master Bedroom Left Small Window Last Seen"
  state_topic: "zigbee2mqtt/master_bedroom_left_small_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Conservatory Skylight Left Last Seen"
  state_topic: "zigbee2mqtt/conservatory_skylight_left"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Pooja Room Small Window Last Seen"
  state_topic: "zigbee2mqtt/pooja_room_small_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Pooja Room Big Window Last Seen"
  state_topic: "zigbee2mqtt/pooja_room_big_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Xiaomi Garage Socket Last Seen"
  state_topic: "zigbee2mqtt/xiaomi_garage_socket"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Pooja Temperature Last Seen"
  state_topic: "zigbee2mqtt/pooja_hygro"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Master Bedroom Temperature Last Seen"
  state_topic: "zigbee2mqtt/master_bedroom_hygro"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Bathroom Temperature Last Seen"
  state_topic: "zigbee2mqtt/bathroom_hygro"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Loft Temperature Last Seen"
  state_topic: "zigbee2mqtt/loft_hygro"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Garage Freezer Temperature Last Seen"
  state_topic: "zigbee2mqtt/garage_freezer_hygro"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Kiaan Big Window Last Seen"
  state_topic: "zigbee2mqtt/kiaan_big_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Conservatory Door Lock Last Seen"
  state_topic: "zigbee2mqtt/conservatory_door_lock"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Aqara Toggle Pooja Last Seen"
  state_topic: "zigbee2mqtt/aqara_toggle_pooja"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Aqara Toggle Bathroom Last Seen"
  state_topic: "zigbee2mqtt/aqara_toggle_bathroom"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Master Bedroom Left Big Window Last Seen"
  state_topic: "zigbee2mqtt/master_bedroom_left_big_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Conservatory Single Door Last Seen"
  state_topic: "zigbee2mqtt/conservatory_single_door"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Conservatory Double Door Last Seen"
  state_topic: "zigbee2mqtt/conservatory_double_door"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Kitchen Window Last Seen"
  state_topic: "zigbee2mqtt/kitchen_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Kiaan Small Window Last Seen"
  state_topic: "zigbee2mqtt/kiaan_small_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Blue Room Big Window Last Seen"
  state_topic: "zigbee2mqtt/blue_room_big_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Blue Room Small Window Last Seen"
  state_topic: "zigbee2mqtt/blue_room_small_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Bathroom Window Last Seen"
  state_topic: "zigbee2mqtt/bathroom_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Cloakroom Window Last Seen"
  state_topic: "zigbee2mqtt/cloakroom_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Living Room Right Small Window Last Seen"
  state_topic: "zigbee2mqtt/living_room_right_small_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Living Room Right Big Window Last Seen"
  state_topic: "zigbee2mqtt/living_room_right_big_window"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Main Door Last Seen"
  state_topic: "zigbee2mqtt/main_door"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Conservatory Skylight Right Last Seen"
  state_topic: "zigbee2mqtt/conservatory_skylight_right"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Ground Floor Smoke Detector Last Seen"
  state_topic: "zigbee2mqtt/ground_floor_smoke_detector"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "First Floor Smoke Detector Last Seen"
  state_topic: "zigbee2mqtt/first_floor_smoke_detector"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Garage Freezer Door Last Seen"
  state_topic: "zigbee2mqtt/garage_freezer_door"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: mqtt
  name: "Pooja Door Last Seen"
  state_topic: "zigbee2mqtt/pooja_door"
  value_template: "{{ value_json['last_seen'] }}"
  device_class: timestamp

- platform: template
  sensors:
    lost_zigbee_devices:
      value_template: >-
        {% for state in states.sensor %}
        {%- if "last_seen" in state.entity_id %} {% if (as_timestamp(now()) - as_timestamp(state.state) |int ) > 7200 %}{{state.entity_id | replace ("binary_","") | replace ("sensor.","") | replace ("_last_seen","")  | replace ("_"," ") | title}}{% endif %} {% endif -%}
        {% endfor %}
      friendly_name: Lost ZigBee devices
      icon_template: 'mdi:zigbee'
    lost_zigbee_devices_ticker:
      value_template: >-
        {%- for state in states.sensor %}
        {%- if "last_seen" in state.entity_id %} {%- if (as_timestamp(now()) - as_timestamp(state.state) |int ) > 7200 %}1{% endif -%} {% endif -%}
        {%- endfor %}
      friendly_name: Lost ZigBee devices
      icon_template: 'mdi:zigbee'
    lost_zigbee_devices_count:
      value_template: '{{ states("sensor.lost_zigbee_devices_ticker") | length }}'
      friendly_name: Lost ZigBee devices
      icon_template: 'mdi:zigbee'