# - platform: mjpeg
#   mjpeg_url: http://192.168.9.23:8082
#   name: 'Front'
# - platform: mjpeg
#   mjpeg_url: http://192.168.9.23:8081
#   name: 'Side'
# - platform: mjpeg
#   mjpeg_url: http://192.168.9.23:8083
#   name: 'Back'
# - platform: mjpeg
#   mjpeg_url: http://192.168.9.23:8085
#   name: 'Living Room'
# - platform: mjpeg
#   mjpeg_url: http://192.168.9.23:8084
#   name: 'Kitchen'
# - platform: mjpeg
#   mjpeg_url: http://192.168.9.23:8086
#   name: 'Garage'
# - platform: mjpeg
#   mjpeg_url: http://192.168.9.23:8087
#   name: 'Conservatory'
- platform: mjpeg
  mjpeg_url: http://192.168.9.23:8089
  name: 'Fire7'

# Frigate Last Person

# - platform: mqtt
#   topic: frigate/garage/person/snapshot
#   name: 'Garage Last Person'

# frigate cams
# - platform: generic
#   still_image_url: http://192.168.9.23:5000/api/back/latest.jpg
#   stream_source: rtmp://192.168.9.23:1935/live/back
#   name: 'Back'
# - platform: generic
#   still_image_url: http://192.168.9.23:5000/api/conservatory/latest.jpg
#   stream_source: rtmp://192.168.9.23:1935/live/conservatory
#   name: 'Conservatory'
# - platform: generic
#   still_image_url: http://192.168.9.23:5000/api/front/latest.jpg
#   stream_source: rtmp://192.168.9.23:1935/live/front
#   name: 'Front'
# - platform: generic
#   still_image_url: http://192.168.9.23:5000/api/garage/latest.jpg
#   stream_source: rtmp://192.168.9.23:1935/live/garage
#   name: 'Garage'
# - platform: generic
#   still_image_url: http://192.168.9.23:5000/api/kitchen/latest.jpg
#   stream_source: rtmp://192.168.9.23:1935/live/kitchen
#   name: 'Kitchen'
# - platform: generic
#   still_image_url: http://192.168.9.23:5000/api/living_room/latest.jpg
#   stream_source: rtmp://192.168.9.23:1935/live/living_room
#   name: 'Living Room'
# - platform: generic
#   still_image_url: http://192.168.9.23:5000/api/side/latest.jpg
#   stream_source: rtmp://192.168.9.23:1935/live/side
#   name: 'Side'




- platform: generic
  still_image_url: !secret xiaomi_vacuum_map
  name: Vacuum Map
  content_type: image/png

- platform: generic
  still_image_url: http://192.168.9.23:8123/local/CCTV_Snapshots/Doorbell.jpg
  name: Doorbell Last Ring
  content_type: image/png

- platform: generic
  name: 'Lolo'
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ state_attr("device_tracker.ha_lolos_iphone","latitude") }},{{ state_attr("device_tracker.ha_lolos_iphone","longitude") }}&zoom=15&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:L%7C{{ state_attr("device_tracker.ha_lolos_iphone","latitude") }},{{ state_attr("device_tracker.ha_lolos_iphone","longitude") }}&markers=color:red%7Clabel:D%7C{{ state_attr("device_tracker.ha_div_iphone","latitude") }},{{ state_attr("device_tracker.ha_div_iphone","longitude") }}
  limit_refetch_to_url_change: true
- platform: generic
  name: 'Div'
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ state_attr("device_tracker.ha_div_iphone","latitude") }},{{ state_attr("device_tracker.ha_div_iphone","longitude") }}&zoom=15&size=500x500&maptype=roadmap&markers=color:red%7Clabel:D%7C{{ state_attr("device_tracker.ha_div_iphone","latitude") }},{{ state_attr("device_tracker.ha_div_iphone","longitude") }}&markers=color:blue%7Clabel:L%7C{{ state_attr("device_tracker.ha_lolos_iphone","latitude") }},{{ state_attr("device_tracker.ha_lolos_iphone","longitude") }}
  limit_refetch_to_url_change: true
- platform: generic
  name: YrForecastCrawley
  still_image_url: https://www.yr.no/en/content/2-6621541/meteogram.svg
  # still_image_url: https://www.yr.no/place/United_Kingdom/England/Maidenbower/meteogram.svg
  content_type: 'image/svg+xml'
- platform: generic
  name: YrForecastWeybridge
  still_image_url: https://www.yr.no/en/content/2-2634204/meteogram.svg
  # still_image_url: https://www.yr.no/place/United_Kingdom/England/Weybridge/meteogram.svg
  content_type: 'image/svg+xml'
- platform: generic
  name: chromecast_radio_pic
  still_image_url: '{{states("sensor.stream_album_art")}}'
    
  
  
- platform: generic
  name: FrontHD
  still_image_url: !secret xiaomi_vacuum_map
  stream_source: !secret cctv_url_front

# - platform: generic
#   name: Grafana Lolo Weight
#   still_image_url: http://192.168.0.24:3000/render/d-solo/ItrU5gHik/ha-dashboard?orgId=1&panelId=6&width=1000&height=500&tz=Europe%2FLondon
#   username: !secret grafana_user
#   password: !secret grafana_password

# - platform: generic
#   name: Grafana CPU RAM
#   still_image_url: http://192.168.0.24:3000/render/d-solo/ItrU5gHik/ha-dashboard?orgId=1&panelId=8&width=1000&height=500&tz=Europe%2FLondon
#   username: !secret grafana_user
#   password: !secret grafana_password