# - platform: xiaomi
#   host: 192.168.0.1
#   password: !secret xiaomi_router_password

- platform: mqtt
  devices:
    lolo: 'location/lolo'
    div: 'location/div'

- platform: tile
  username: !secret tile_user
  password: !secret tile_password

- platform: icloud3
  username: !secret icloud3_username
  password: !secret icloud3_password
  #exclude_sensors: batstat,lzonn,lzont,name
  
  
# - platform: life360
  # username: !secret life360_username
  # password: !secret life360_password
  # show_as_state: driving, moving, places
  # driving_speed: 18
  # max_gps_accuracy: 200
  # time_as: device_or_local
  # max_update_wait:
    # minutes: 45