- name: gmaillolo
  platform: smtp
  server: smtp.gmail.com
  port: 587
  sender: !secret email_from
  starttls: true
  username: !secret email_from
  password: !secret email_password
  recipient: !secret email_to_lolo
  encryption: starttls

- name: gmaildiv
  platform: smtp
  server: smtp.gmail.com
  port: 587
  sender: !secret email_from
  starttls: true
  username: !secret email_from
  password: !secret email_password
  recipient: !secret email_to_div
  encryption: starttls
  
- platform: group
  name: divandlolo
  services:
    - service: mobile_app_lolo_iphone
    - service: mobile_app_div_iphone

- name: lolowork
  platform: smtp
  server: smtp.gmail.com
  port: 587
  sender: !secret email_from
  starttls: true
  username: !secret email_from
  password: !secret email_password
  recipient: !secret email_to_lolo_work
  encryption: starttls

- name: twillio_lolo
  platform: twilio_call
  from_number: !secret twillio_lolo_phone_number

- name: whatsapp_neighbourhood_watch
  platform: rest
  resource: !secret whin_neighbourhood_watch_group_id
  method: POST
  verify_ssl: true
  headers: 
    X-RapidAPI-Key: !secret whin_api_key
  message_param_name: text