- name: gmaillolo
  platform: smtp
  server: smtp.gmail.com
  port: 587
  sender: !secret email_from
  starttls: true
  username: !secret email_from
  password: !secret email_password
  recipient: !secret email_to_lolo
  encryption: starttls

- name: gmaildiv
  platform: smtp
  server: smtp.gmail.com
  port: 587
  sender: !secret email_from
  starttls: true
  username: !secret email_from
  password: !secret email_password
  recipient: !secret email_to_div
  encryption: starttls
  
- platform: group
  name: divandlolo
  services:
    - service: mobile_app_lolo_s_iphone
    - service: mobile_app_div_iphone

- name: lolowork
  platform: smtp
  server: smtp.gmail.com
  port: 587
  sender: !secret email_from
  starttls: true
  username: !secret email_from
  password: !secret email_password
  recipient: !secret email_to_lolo_work
  encryption: starttls
