title: Home



custom_header:
  compact_mode: true
  show_tabs: 0
  kiosk_mode: true
  exceptions:
    - conditions:
        user: Laurent, Divashni
      config:
        show_tabs: '0 to 50'
        kiosk_mode: false

# preload:
  # - gauge
  # - picture-glance
  # - conditional
  # - picture-entity
views:
  - !include /config/lovelace_views/alarm.yaml
  - !include /config/lovelace_views/home.yaml
  - !include /config/lovelace_views/media.yaml
  - !include /config/lovelace_views/living_room.yaml
  - !include /config/lovelace_views/kitchen.yaml
  - !include /config/lovelace_views/entrance.yaml
  - !include /config/lovelace_views/conservatory.yaml
  - !include /config/lovelace_views/staircase.yaml
  - !include /config/lovelace_views/pooja.yaml
  - !include /config/lovelace_views/bathroom.yaml
  - !include /config/lovelace_views/main_bedroom.yaml
  - !include /config/lovelace_views/kiaan_bedroom.yaml
  - !include /config/lovelace_views/cctv.yaml
  - !include /config/lovelace_views/automations.yaml
  - !include /config/lovelace_views/server.yaml
  - !include /config/lovelace_views/server_stats.yaml
  - !include /config/lovelace_views/car.yaml
  - !include /config/lovelace_views/garage.yaml
  # - !include /config/lovelace_views/test.yaml