title: Home

resources:

animated_background:
  default_url: /hacsfiles/lovelace-animated-backgroundBackup/background-animations/sunny.html
  # debug: true
  # display_user_agent: true
  excluded_users:
    - Fire7
  excluded_devices:
    - iphone
  entity: "input_boolean.theme_dark"
  state_url:
    'off':
      - "/local/community/lovelace-animated-backgroundBackup/Autumn_Lake.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Grand_Canyon.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Mountain.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Mountains_Lake.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/River.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Tropical_Beach.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Volcano.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Waterfall.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Waterfall2.mp4"
    'on':
      - "/local/community/lovelace-animated-backgroundBackup/Night_Grand_Canyon.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Night_Moon.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Night_Moon2.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Night_Skies.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Night_Space.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Night_Sunset.mp4"
      - "/local/community/lovelace-animated-backgroundBackup/Night_Sunset2.mp4"
  views:
    - path: nest_hub
      config:
        enabled: false

preload_cards:
  - 'custom:canvas-gauge-card'


views:
  - !include /config/lovelace_views/alarm.yaml
  - !include /config/lovelace_views/home.yaml
  - !include /config/lovelace_views/media.yaml
  - !include /config/lovelace_views/living_room.yaml
  - !include /config/lovelace_views/kitchen.yaml
  - !include /config/lovelace_views/entrance.yaml
  - !include /config/lovelace_views/conservatory.yaml
  - !include /config/lovelace_views/staircase.yaml
  - !include /config/lovelace_views/bathroom.yaml
  - !include /config/lovelace_views/master_bedroom.yaml
  - !include /config/lovelace_views/kiaan_bedroom.yaml
  - !include /config/lovelace_views/pooja.yaml
  - !include /config/lovelace_views/blue_room.yaml
  - !include /config/lovelace_views/cctv.yaml
  - !include /config/lovelace_views/temperature.yaml
  - !include /config/lovelace_views/automations.yaml
  - !include /config/lovelace_views/server.yaml
  - !include /config/lovelace_views/server_stats.yaml
  - !include /config/lovelace_views/car.yaml
  - !include /config/lovelace_views/garage.yaml
  # - !include /config/lovelace_views/nest_hub.yaml
  # - !include /config/lovelace_views/test.yaml