- platform: template
  sensors:
    kitchen_freezer_temperature_battery:
      friendly_name: Kitchen Freezer Temperature Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("sensor.kitchen_freezer_humidity", "battery_level") | int}}'
      device_class: battery
    garage_freezer_temperature_battery:
      friendly_name: Garage Freezer Temperature Battery
      unit_of_measurement: '%'
      value_template: '{{state_attr("sensor.garage_freezer_humidity", "battery_level") | int}}'
      device_class: battery