- platform: mqtt
  name: "RTL2_Pic"
  state_topic: "RadioStream/RTL2/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "RTL2_Artist"
  state_topic: "RadioStream/RTL2/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "RTL2_Track"
  state_topic: "RadioStream/RTL2/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Chill_Pic"
  state_topic: "RadioStream/Chill/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Chill_Artist"
  state_topic: "RadioStream/Chill/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Chill_Track"
  state_topic: "RadioStream/Chill/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_Pic"
  state_topic: "RadioStream/Absolute_Radio/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_Artist"
  state_topic: "RadioStream/Absolute_Radio/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_Track"
  state_topic: "RadioStream/Absolute_Radio/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_CR_Pic"
  state_topic: "RadioStream/Absolute_Radio_CR/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_CR_Artist"
  state_topic: "RadioStream/Absolute_Radio_CR/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Scala_Pic"
  state_topic: "RadioStream/Scala/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Scala_Artist"
  state_topic: "RadioStream/Scala/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Scala_Track"
  state_topic: "RadioStream/Scala/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Radio_Fiji_Two_Artist"
  state_topic: "RadioStream/Radio_Fiji_Two/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Radio_Fiji_Two_Track"
  state_topic: "RadioStream/Radio_Fiji_Two/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "ha_podcast"
  state_topic: "RadioStream/Hass Podcast/mp3_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "ha_podcast_track"
  state_topic: "RadioStream/Hass Podcast/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_CR_Track"
  state_topic: "RadioStream/Absolute_Radio_CR/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "internet_of_things_podcast"
  state_topic: "RadioStream/IoT Podcast/mp3_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "internet_of_things_podcast_track"
  state_topic: "RadioStream/IoT Podcast/track"
  value_template: "{{ value }}"


- platform: template
  sensors:
    stream_artist:
      value_template: >
        {% if is_state("input_select.chromecast_radio_station", "RTL2") %} {{states("sensor.rtl2_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio") %} {{states("sensor.absolute_radio_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio Classic Rock") %} {{states("sensor.absolute_radio_CR_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Hit West") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "HA Podcast") %} Phil & Rohan
        {% elif is_state("input_select.chromecast_radio_station", "IoT Podcast") %} Stacey & Kevin
        {% elif is_state("input_select.chromecast_radio_station", "Chill") %} {{states("sensor.chill_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Navtarang") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Radio Fiji Two") %} {{states("sensor.radio_fiji_two_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Scala") %} {{states("sensor.scala_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} N/A
        {% endif %}
      friendly_name: Artist
      icon_template: 'mdi:account'
    stream_track:
      value_template: >
        {% if is_state("input_select.chromecast_radio_station", "RTL2") %} {{states("sensor.rtl2_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio") %} {{states("sensor.absolute_radio_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio Classic Rock") %} {{states("sensor.absolute_radio_CR_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Hit West") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "HA Podcast") %} {{states("sensor.ha_podcast_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "IoT Podcast") %} {{states("sensor.internet_of_things_podcast_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Chill") %} {{states("sensor.chill_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Navtarang") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Radio Fiji Two") %} {{states("sensor.radio_fiji_two_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Scala") %} {{states("sensor.scala_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} N/A
        {% endif %}
      friendly_name: Track
      icon_template: 'mdi:account'
    stream_album_art:
      value_template: >
        {% if is_state("binary_sensor.radio_is_streaming","on")%}
        {% if is_state("input_select.chromecast_radio_station", "Hit West") %} https://upload.wikimedia.org/wikipedia/fr/b/bd/HitWestLogo.jpg
        {% elif is_state("input_select.chromecast_radio_station", "RTL2") %} {{states("sensor.rtl2_pic") | replace("https://images.rtl.fr", "http://images.rtl.fr")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio") %} {{states("sensor.absolute_radio_pic")}}
        {% elif is_state("input_select.chromecast_radio_station", "Scala") %} {{states("sensor.scala_pic")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio Classic Rock") %} {{states("sensor.absolute_radio_CR_pic")}}
        {% elif is_state("input_select.chromecast_radio_station", "HA Podcast") %} https://secureimg.stitcher.com/feedimageswide/480x270_176113.jpg
        {% elif is_state("input_select.chromecast_radio_station", "IoT Podcast") %} https://is1-ssl.mzstatic.com/image/thumb/Music62/v4/b3/d6/64/b3d664ab-0560-f24d-2379-d01142267f94/source/1200x630bb.jpg
        {% elif is_state("input_select.chromecast_radio_station", "Chill") %} {{states("sensor.chill_pic")}}
        {% elif is_state("input_select.chromecast_radio_station", "Navtarang") %} https://static-media.streema.com/media/cache/61/a2/61a237fb6851e34614c55420b3e11a62.jpg
        {% elif is_state("input_select.chromecast_radio_station", "Radio Fiji Two") %} http://player.streamguys.com/fbc/sgplayer/include/assets/img/RF2.png
        {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} https://www.holyscripturesandisrael.com/images/radio/radio-icon.png
        {% endif %}
        {%else%}http://192.168.0.24:8123/local/Select_Radio.png
        {%endif%}
      friendly_name: Album Art
      icon_template: 'mdi:account'