- platform: mqtt
  name: "RTL2_Pic"
  state_topic: "RadioStream/RTL2/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "RTL2_Artist"
  state_topic: "RadioStream/RTL2/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "RTL2_Track"
  state_topic: "RadioStream/RTL2/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Chill_Pic"
  state_topic: "RadioStream/Chill/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Chill_Artist"
  state_topic: "RadioStream/Chill/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Chill_Track"
  state_topic: "RadioStream/Chill/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_Pic"
  state_topic: "RadioStream/Absolute_Radio/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_Artist"
  state_topic: "RadioStream/Absolute_Radio/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_Track"
  state_topic: "RadioStream/Absolute_Radio/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_CR_Pic"
  state_topic: "RadioStream/Absolute_Radio_CR/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_CR_Artist"
  state_topic: "RadioStream/Absolute_Radio_CR/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Scala_Pic"
  state_topic: "RadioStream/Scala/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Scala_Artist"
  state_topic: "RadioStream/Scala/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Scala_Track"
  state_topic: "RadioStream/Scala/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Radio_Fiji_Two_Artist"
  state_topic: "RadioStream/Radio_Fiji_Two/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Radio_Fiji_Two_Track"
  state_topic: "RadioStream/Radio_Fiji_Two/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "ha_podcast"
  state_topic: "RadioStream/Hass Podcast/mp3_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "ha_podcast_track"
  state_topic: "RadioStream/Hass Podcast/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_CR_Track"
  state_topic: "RadioStream/Absolute_Radio_CR/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "internet_of_things_podcast"
  state_topic: "RadioStream/IoT Podcast/mp3_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "internet_of_things_podcast_track"
  state_topic: "RadioStream/IoT Podcast/track"
  value_template: "{{ value }}"


- platform: template
  sensors:
    stream_artist:
      value_template: >
        {% if is_state("input_select.chromecast_radio_station", "RTL2") %} {{states("sensor.rtl2_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio") %} {{states("sensor.absolute_radio_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio Classic Rock") %} {{states("sensor.absolute_radio_CR_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Hit West") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "HA Podcast") %} Phil & Rohan
        {% elif is_state("input_select.chromecast_radio_station", "IoT Podcast") %} Stacey & Kevin
        {% elif is_state("input_select.chromecast_radio_station", "Chill") %} {{states("sensor.chill_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Navtarang") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Radio Fiji Two") %} {{states("sensor.radio_fiji_two_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Scala") %} {{states("sensor.scala_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} N/A
        {% endif %}
      friendly_name: Artist
      icon_template: 'mdi:account'
    stream_track:
      value_template: >
        {% if is_state("input_select.chromecast_radio_station", "RTL2") %} {{states("sensor.rtl2_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio") %} {{states("sensor.absolute_radio_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio Classic Rock") %} {{states("sensor.absolute_radio_CR_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Hit West") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "HA Podcast") %} {{states("sensor.ha_podcast_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "IoT Podcast") %} {{states("sensor.internet_of_things_podcast_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Chill") %} {{states("sensor.chill_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Navtarang") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Radio Fiji Two") %} {{states("sensor.radio_fiji_two_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Scala") %} {{states("sensor.scala_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} N/A
        {% endif %}
      friendly_name: Artist
      icon_template: 'mdi:account'
