- platform: scrape
  resource: https://www.home-assistant.io
  name: Online Version
  select: ".current-version h1"
  value_template: '{{ value.split(":")[1] }}'
  scan_interval: 3600

# Tasmota
# - platform: scrape
#   resource: https://github.com/arendst/Tasmota/releases
#   name: tasmota_online_version
#   select: "span.css-truncate-target"
#   scan_interval: 3600

- platform: command_line
  name: 'Tasmota Online Version'
  command: "curl -s https://github.com/arendst/Tasmota/releases/latest | cut -d'\"' -f2 | rev | cut -d'/' -f1 | rev"
  scan_interval: 3600