# CCTV Detection
- platform: rest
  resource: http://192.168.0.23:8080/4/detection/status
  name: dafang_kitchen_status_scrape
  value_template: '{{ value.split("Detection status ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/5/detection/status
  name: dafang_living_room_status_scrape
  value_template: '{{ value.split("Detection status ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/6/detection/status
  name: dafang_conservatory_status_scrape
  value_template: '{{ value.split("Detection status ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/7/detection/status
  name: cctv_garage_status_scrape
  value_template: '{{ value.split("Detection status ")[1] }}'

# - platform: rest
#   resource: http://192.168.0.23:8080/8/detection/status
#   name: cctv_doorbell_status_scrape
#   value_template: '{{ value.split("Detection status ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/9/detection/status
  name: cctv_staircase_status_scrape
  value_template: '{{ value.split("Detection status ")[1] }}'


# CCTV Connection
- platform: rest
  resource: http://192.168.0.23:8080/5/detection/connection
  name: dafang_living_room_connection_scrape
  value_template: '{{ value.split("Camera 5 Connection ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/4/detection/connection
  name: dafang_kitchen_connection_scrape
  value_template: '{{ value.split("Camera 4 Connection ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/6/detection/connection
  name: dafang_conservatory_connection_scrape
  value_template: '{{ value.split("Camera 6 Connection ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/7/detection/connection
  name: cctv_garage_connection_scrape
  value_template: '{{ value.split("Camera 7 Connection ")[1] }}'

# - platform: rest
#   resource: http://192.168.0.23:8080/8/detection/connection
#   name: cctv_doorbell_connection_scrape
#   value_template: '{{ value.split("Camera 8 Connection ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/9/detection/connection
  name: cctv_staircase_connection_scrape
  value_template: '{{ value.split("Camera 9 Connection ")[1] }}'



- platform: scrape
  resource: https://www.home-assistant.io
  name: Online Version
  select: ".current-version h1"
  value_template: '{{ value.split(":")[1] }}'
  scan_interval: 3600

# Tasmota
- platform: scrape
  resource: https://github.com/arendst/Tasmota/releases
  name: tasmota_online_version
  select: "span.css-truncate-target"
  scan_interval: 3600
