- platform: waze_travel_time
  name: Home to Work
  origin: zone.home
  destination: zone.verint
  region: 'EU'

- platform: waze_travel_time
  name: Lolo to Home
  origin: person.laurent
  destination: zone.home
  region: 'EU'

- platform: waze_travel_time
  name: Div to Home
  origin: person.div
  destination: zone.home
  region: 'EU'



- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 0
  monitored_conditions:
    - summary
    - icon
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature
    - humidity
    - temperature_high
    - temperature_low
    - precip_intensity_max
    - wind_speed
    - wind_gust

- platform: template
  sensors:
    sunset_time:
      entity_id: sun.sun
      value_template: >
        {{ as_timestamp(state_attr("sun.sun","next_setting")) | timestamp_custom("%H:%M") }}
      friendly_name: Sunset
      icon_template: '{% if states("sun.sun") == "above_horizon" %}mdi:white-balance-sunny{% else %}mdi:weather-night{% endif %}'

- platform: template
  sensors:
    precipitation:
      entity_id: weather.dark_sky
      value_template: >
        {{state_attr('weather.dark_sky', 'forecast')[0].precipitation}}
      friendly_name: Precipitation
      unit_of_measurement: "mm"


- platform: version
  name: Current Version

- platform: version
  name: Docker Version
  source: docker

- platform: uptime
  unit_of_measurement: hours

- platform: time_date
  display_options:
    - 'time'

- platform: template
  sensors:
    week_day:
      entity_id: sensor.time
      value_template: "{{ now().strftime('%A')}}"
    current_date:
      entity_id: sensor.time
      value_template: "{{ now().strftime('%d')}} {{ now().strftime('%B')}} {{ now().strftime('%Y')}}"

- platform: random
  name: bauble_random_effect
  minimum: 1
  maximum: 3
  scan_interval: 290
  
  
- platform: seventeentrack
  username: !secret seventeentrack_email
  password: !secret seventeentrack_passwqord
  show_delivered: true

- platform: template
  sensors:
    pages_left:
      value_template: "{{ states('var.printer_pages_at_month_start')|int - states('sensor.hp_printer_printer')|int + 50}}"
      unit_of_measurement: Pages