- platform: template
  sensors:
    edimax1_watts:
      value_template: '{{state_attr("switch.edimax1","current_power_w")|float}}'
      unit_of_measurement: 'W'
      friendly_name: Edimax1 Watts
      icon_template: '{% if is_state("switch.edimax1","on") %}mdi:speedometer{% else %}mdi:speedometer-slow{% endif %}'
      device_class: power

    xiaomi_dual_usb_socket_watts:
      value_template: '{{state_attr("switch.xiaomi_dual_usb_socket","load_power")|float}}'
      unit_of_measurement: 'W'
      friendly_name: Xiaomi Dual USB Socket Watts
      icon_template: '{% if is_state("switch.xiaomi_dual_usb_socket","on") %}mdi:speedometer{% else %}mdi:speedometer-slow{% endif %}'
      device_class: power

    xiaomi_garage_socket_watts:
      value_template: '{{state_attr("switch.xiaomi_garage_socket","load_power")|float}}'
      unit_of_measurement: 'W'
      friendly_name: Xiaomi Garage Socket Watts
      icon_template: '{% if is_state("switch.xiaomi_garage_socket","on") %}mdi:speedometer{% else %}mdi:speedometer-slow{% endif %}'
      device_class: power