- platform: template
  sensors:
    porch_door_lock_status:
      value_template: >
        {% if states("sensor.yale_conexis_l1_alarmtype_none") == "9"  %}Jammed
        {% elif states("sensor.yale_conexis_l1_alarmtype_none") == "16"  %}Unlocked by Yale App
        {% elif states("sensor.yale_conexis_l1_alarmtype_none") == "21"  %}Locked manually
        {% elif states("sensor.yale_conexis_l1_alarmtype_none") == "22"  %}Unlocked manually
        {% elif states("sensor.yale_conexis_l1_alarmtype_none") == "24"  %}Locked by zwave
        {% elif states("sensor.yale_conexis_l1_alarmtype_none") == "25"  %}Unlocked by zwave
        {% elif states("sensor.yale_conexis_l1_alarmtype_none") == "27"  %}Auto relock
        {% elif states("sensor.yale_conexis_l1_alarmtype_none") == "144"  %}Unlocked by RFID tag
        {% else %}Unknown ({{("sensor.yale_conexis_l1_alarmtype_none")}})
        {% endif %}
      friendly_name: Porch Door Lock Status
      icon_template: 'mdi:lock-clock'