- platform: template
  sensors:
    porch_door_lock_status:
      value_template: >
        {{ state_attr("lock.yale_conexis_l1_lock","lock_status") }}
      friendly_name: Porch Door Lock Status
      icon_template: 'mdi:lock-clock'