- platform: template
  sensors:
    dafang_living_room_status:
      entity_id: input_boolean.pir_living_room_back
      value_template: >
        {{ states("input_boolean.pir_living_room_back") == 'ACTIVE'}}
      friendly_name: Dafang Living Room motion Status
      device_class: power

    dafang_living_room_connection_status:
      entity_id: sensor.dafang_living_room_connection_scrape
      value_template: >
        {{ states("sensor.dafang_living_room_connection_scrape") == 'OK'}}
      friendly_name: Dafang Living Room Connection Status
      device_class: connectivity

    dafang_kitchen_connection_status:
      entity_id: sensor.dafang_kitchen_connection_scrape
      value_template: >
        {{ states("sensor.dafang_kitchen_connection_scrape") == 'OK'}}
      friendly_name: Dafang Kitchen Connection Status
      device_class: connectivity

    dafang_conservatory_connection_status:
      entity_id: sensor.dafang_conservatory_connection_scrape
      value_template: >
        {{ states("sensor.dafang_conservatory_connection_scrape") == 'OK'}}
      friendly_name: Dafang Conservatory Connection Status
      device_class: connectivity

    garage_cctv_connection_status:
      entity_id: sensor.cctv_garage_connection_scrape
      value_template: >
        {{ states("sensor.cctv_garage_connection_scrape") == 'OK'}}
      friendly_name: Garage CCTV Connection Status
      device_class: connectivity


- platform: hikvision
  name: front_cctv
  host: 192.168.0.31
  port: 8031
  ssl: False
  username: !secret hikvision_username
  password: !secret hikvision_password

- platform: hikvision
  name: side_cctv
  host: 192.168.0.34
  port: 8034
  ssl: False
  username: !secret hikvision_username
  password: !secret hikvision_password

- platform: hikvision
  name: back_cctv
  host: 192.168.0.35
  port: 8035
  ssl: False
  username: !secret hikvision_username
  password: !secret hikvision_password

