- platform: template
  sensors:
    dafang_living_room_status:
      value_template: >
        {{ states("input_boolean.pir_living_room_back") == 'ACTIVE'}}
      friendly_name: Dafang Living Room motion Status
      device_class: power

    dafang_living_room_connection_status:
      value_template: >
        {{ states("sensor.dafang_living_room_connection_scrape") == 'OK'}}
      friendly_name: Dafang Living Room Video Feed Status
      device_class: connectivity

    dafang_kitchen_connection_status:
      value_template: >
        {{ states("sensor.dafang_kitchen_connection_scrape") == 'OK'}}
      friendly_name: Dafang Kitchen Video Feed Status
      device_class: connectivity

    dafang_conservatory_connection_status:
      value_template: >
        {{ states("sensor.dafang_conservatory_connection_scrape") == 'OK'}}
      friendly_name: Dafang Conservatory Video Feed Status
      device_class: connectivity

    garage_cctv_connection_status:
      value_template: >
        {{ states("sensor.cctv_garage_connection_scrape") == 'OK'}}
      friendly_name: Garage CCTV Video Feed Status
      device_class: connectivity

    doorbell_cctv_connection_status:
      value_template: >
        {{ states("sensor.cctv_doorbell_connection_scrape") == 'OK'}}
      friendly_name: Doorbell CCTV Video Feed Status
      device_class: connectivity

    # doorbell_motion :
    #   value_template: >
    #     {{ states("binary_sensor.doorbell_motion") == 'on'}}
    #   friendly_name: Doorbell Motion
    #   device_class: motion

    # doorbell_person :
    #   value_template: >
    #     {{ states("binary_sensor.doorbell_person") == 'on'}}
    #   friendly_name: Doorbell Person
    #   device_class: motion

    # doorbell_ring :
    #   value_template: >
    #     {{ states("binary_sensor.doorbell_ring") == 'on'}}
    #   friendly_name: Doorbell Ring
    #   device_class: motion


- platform: hikvision
  name: front_cctv
  host: 192.168.0.31
  port: 8031
  ssl: False
  username: !secret hikvision_username
  password: !secret hikvision_password

- platform: hikvision
  name: side_cctv
  host: 192.168.0.34
  port: 8034
  ssl: False
  username: !secret hikvision_username
  password: !secret hikvision_password

- platform: hikvision
  name: back_cctv
  host: 192.168.0.35
  port: 8035
  ssl: False
  username: !secret hikvision_username
  password: !secret hikvision_password

- platform: mqtt
  name: "Garage Motion"
  state_topic: "Sensors/CCTV2/Garage/Motion"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion

# - platform: rest
#   name: "Doorbell Motion ioBroker"
#   resource: http://192.168.0.24:8087/get/eufy-security.0.T8200N02204208EC.cameras.T8200N02204208EC.motion_detected
#   value_template: '{{ value_json.val }}'
#   scan_interval: 5

# - platform: rest
#   name: "Doorbell Person ioBroker"
#   resource: http://192.168.0.24:8087/get/eufy-security.0.T8200N02204208EC.cameras.T8200N02204208EC.person_detected
#   value_template: '{{ value_json.val }}'
#   scan_interval: 5

# - platform: rest
#   name: "Doorbell Ring ioBroker"
#   resource: http://192.168.0.24:8087/get/eufy-security.0.T8200N02204208EC.cameras.T8200N02204208EC.ringing
#   value_template: '{{ value_json.val }}'
#   scan_interval: 5

