- platform: template
  sensors:
    hallway_heating:
      value_template: >
        {{ state_attr("climate.hallway", "hvac_action") == 'heating'}}
      friendly_name: Hallway Heating
      device_class: heat