- platform: ping
  host: 192.168.0.22
  name: RPi

- platform: ping
  host: 192.168.0.3
  name: MAIN

- platform: ping
  host: 192.168.0.40
  name: TV Cabinet LED Strip

- platform: ping
  host: 192.168.0.41
  name: StairCase LED Strip

- platform: ping
  host: 192.168.0.53
  name: Conservatory LED Strip

- platform: ping
  host: 192.168.0.17
  name: Kello

- platform: ping
  host: 192.168.0.21
  name: RPi Kitchen

- platform: ping
  host: 192.168.0.30
  name: Verint CCTV

- platform: ping
  host: 192.168.0.31
  name: Hikvision CCTV

- platform: ping
  host: 192.168.0.32
  name: Dafang Living Room

- platform: ping
  host: 192.168.0.33
  name: Dafang Kitchen

- platform: ping
  host: 192.168.0.36
  name: Dafang Conservatory

- platform: ping
  host: 192.168.0.37
  name: Doorbell

- platform: ping
  host: 192.168.0.4
  name: Pi-Zero