- platform: ping
  host: 192.168.0.22
  name: RPi

- platform: ping
  host: 192.168.0.3
  name: MAIN

- platform: ping
  host: 192.168.9.40
  name: TV Cabinet LED Strip

- platform: ping
  host: 192.168.9.41
  name: StairCase LED Strip

- platform: ping
  host: 192.168.9.53
  name: Conservatory LED Strip

- platform: ping
  host: 192.168.9.17
  name: Kello

- platform: ping
  host: 192.168.9.21
  name: RPi Kitchen

- platform: ping
  host: 192.168.9.30
  name: Verint CCTV

- platform: ping
  host: 192.168.9.31
  name: Hikvision CCTV

- platform: ping
  host: 192.168.9.32
  name: Dafang Living Room

- platform: ping
  host: 192.168.9.33
  name: Dafang Kitchen

- platform: ping
  host: 192.168.9.36
  name: Dafang Conservatory

- platform: ping
  host: 192.168.9.38
  name: Doorbell

- platform: ping
  host: 192.168.9.4
  name: Pi-Zero