- platform: mqtt
  name: "Power BI EMEA Status"
  state_topic: "Sensors/powerbistatus"
  value_template: "{{value_json['emeaservicestatus'] != 'good' }}"
  json_attributes_topic: "Sensors/powerbistatus"
  icon: mdi:web
  payload_on: true
  payload_off: false
  
- platform: mqtt
  name: "Power BI Service Status"
  state_topic: "Sensors/powerbistatus"
  value_template: "{{ value_json['serviceoutagestatus'] != 'good' }}"
  json_attributes_topic: "Sensors/powerbistatus"
  icon: mdi:web
  payload_on: true
  payload_off: false
  
- platform: mqtt
  name: "Power BI Awareness Status"
  state_topic: "Sensors/powerbistatus"
  value_template: "{{ value_json['awarenessstatus'] != 'good' }}"
  json_attributes_topic: "Sensors/powerbistatus"
  icon: mdi:web
  payload_on: true
  payload_off: false
