- platform: template
  sensors:
    radio_is_streaming:
      value_template: >
        {% set myval = namespace(found=0) %}
        {%- for state in states.media_player -%}
        {%- if state.entity_id in ["media_player.conservatory", "media_player.house", "media_player.kitchen", "media_player.onkyo", "media_player.master_bedroom_nest_hub", "media_player.office_nest_hub", "media_player.onkyo_tx_nr656_2"] -%}
        {% if state_attr(state.entity_id, "media_content_id") != None %}
        {% if state_attr(state.entity_id, "media_content_id").split("?")[0] in ["http://icecast.rtl2.fr/rtl2-1-44-128", "https://stream-ar.planetradio.co.uk/absoluteradiohigh.aac", "https://stream-ar.planetradio.co.uk/absoluteclassicrockhigh.aac", "http://broadcast.infomaniak.ch/hitwest-high.mp3", states("sensor.ha_podcast"), states("sensor.internet_of_things_podcast"), "http://media-the.musicradio.com/ChillMP3", "http://peridot.streamguys.com:7150/RFTwo", "https://stream.fijivillage.com/navtarang", "https://stream-mz.planetradio.co.uk/scalahigh.aac", states("input_text.custom_station")] -%}{% set myval.found = myval.found + 1%}{%- endif -%} {% endif %}
        {%- endif -%}  
        {%- endfor %}
        {{ myval.found > 0 }}
