- platform: rfxtrx
  # automatic_add: True
  devices:
    0B11002B00018F3C0A010F60:
      name: Garage Back Door
      device_class: door
    # 0B1100300001B0240A000050:
      # name: Conservatory Skylight Left
      # device_class: window
    # 09130007a68a42012970:
      # name: Kerui Remote Disarm
      # fire_event: true
    # 09130008a68a44012b70:
      # name: Kerui Remote Arm Away
      # fire_event: true
    # 09130009a68a48012b70:
      # name: Kerui Remote Panic
      # fire_event: true
    # 0913000aa68a41012970:
      # name: Kerui Remote Arm Home
      # fire_event: true
