- platform: rfxtrx
  automatic_add: false
  devices:
    091903076C911A000070:
      name: Kitchen Blinds
      fire_event: true
    09190002002527010070:
      name: Livingroom Blinds
      fire_event: true
      