- alias: 'Alarm - Trigger while armed away'
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.conservatory_skylight_left
        - binary_sensor.conservatory_single_door
        - binary_sensor.conservatory_double_door
        - binary_sensor.living_room_right_window
        - binary_sensor.living_room_left_window
        - binary_sensor.master_bedroom_right_window
        - binary_sensor.master_bedroom_left_window
        - binary_sensor.cloakroom_window
        - binary_sensor.bathroom_window
        - binary_sensor.kiaan_big_window
        - binary_sensor.kiaan_small_window
        - binary_sensor.blue_room_big_window
        - binary_sensor.blue_room_small_window
        - binary_sensor.main_door
        - binary_sensor.kitchen_window
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
    - condition: or
      conditions:
      - condition: template
        value_template: >
          {%- set pirs = [
          states.binary_sensor.conservatory_single_door,
          states.binary_sensor.conservatory_double_door,
          states.binary_sensor.living_room_right_window,
          states.binary_sensor.living_room_left_window,
          states.binary_sensor.master_bedroom_right_window,
          states.binary_sensor.master_bedroom_left_window,
          states.binary_sensor.cloakroom_window,
          states.binary_sensor.bathroom_window,
          states.binary_sensor.kiaan_big_window,
          states.binary_sensor.kiaan_small_window,
          states.binary_sensor.blue_room_big_window,
          states.binary_sensor.blue_room_small_window,
          states.binary_sensor.kitchen_window,
          states.binary_sensor.main_door ] -%}
          {%- set pirs_on = pirs | selectattr('state','eq','on') | list -%}
          {{ ((pirs_on | length) | int ) >= 1}}
      - condition: template
        value_template: >
          {%- set pirs = [
                states.binary_sensor.pir_conservatory,
                states.binary_sensor.pir_kitchen,
                states.binary_sensor.pir_living_room_front,
                states.binary_sensor.pir_living_room_back,
                states.binary_sensor.pir_staircase] -%}
          {%- set pirs_on = pirs | selectattr('state','eq','on') | list -%}
          {{ ((pirs_on | length) | int ) > 1}}
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_home_minis
        volume_level: '1' 
    - service: media_player.play_media
      data:
        entity_id: media_player.google_home_minis
        media_content_id: 'http://192.168.0.24/audio/Alarm-CountDown.mp3'
        media_content_type: 'audio/mp3'


- alias: 'Alarm - Alarm Triggered'
  initial_state: true
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'triggered'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 7811dcdae94a
        ringtone_id: 2
        ringtone_vol: 100
    # play alert, 0.9 on onkyo, 1 on conservatory, google minis
    # - service: media_player.play_media
      # data:
        # entity_id: media_player.google_home_minis
        # media_content_id: 'http://192.168.0.24/audio/Alarm-Intrusion.mp3'
        # media_content_type: 'audio/mp3'
    - service: switch.turn_off
      data:
        entity_id: switch.kerui_alarm
    - service: camera.snapshot
      data:
        entity_id: camera.fire7
        filename: '/config/www/CCTV_Snapshots/Fire7.jpg'
    - service: switch.turn_off
      data:
        entity_id: switch.kerui_alarm
    - service: camera.snapshot
      data:
        entity_id: camera.front
        filename: '/config/www/CCTV_Snapshots/Front.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.side
        filename: '/config/www/CCTV_Snapshots/Side.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.back
        filename: '/config/www/CCTV_Snapshots/Back.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.kitchen
        filename: '/config/www/CCTV_Snapshots/Kitchen.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.living_room
        filename: '/config/www/CCTV_Snapshots/LivingRoom.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.garage
        filename: '/config/www/CCTV_Snapshots/Garage.jpg'
    - service: notify.gmaillolo
      data_template:
        message: >
          ALARM! The alarm has been triggered !(
          ({% for windoor in state_attr("group.door_and_window_sensors","entity_id")|list  -%}
          {% if is_state(windoor,"on") %}{{state_attr(windoor, "friendly_name")}}, {% endif %}
          {%- endfor -%}
          {% if is_state('binary_sensor.main_door','on') %}Main Door,{% endif%}
          {% for mypirs in state_attr("group.pirs","entity_id")|list  -%}
          {% if is_state(mypirs ,"on") %}{{state_attr(mypirs , "friendly_name")}}, {% endif %}
          {%- endfor %})
        data:
          images:
            - /config/www/CCTV_Snapshots/LivingRoom.jpg
            - /config/www/CCTV_Snapshots/Kitchen.jpg
            - /config/www/CCTV_Snapshots/Fire7.jpg
            - /config/www/CCTV_Snapshots/Front.jpg
            - /config/www/CCTV_Snapshots/Side.jpg
            - /config/www/CCTV_Snapshots/Back.jpg
            - /config/www/CCTV_Snapshots/Garage.jpg
    - service: notify.gmaildiv
      data_template:
        message: >
          ALARM! The alarm has been triggered !(
          ({% for windoor in state_attr("group.door_and_window_sensors","entity_id")|list  -%}
          {% if is_state(windoor,"on") %}{{state_attr(windoor, "friendly_name")}}, {% endif %}
          {%- endfor -%}
          {% if is_state('binary_sensor.main_door','on') %}Main Door,{% endif%}
          {% for mypirs in state_attr("group.pirs","entity_id")|list  -%}
          {% if is_state(mypirs ,"on") %}{{state_attr(mypirs , "friendly_name")}}, {% endif %}
          {%- endfor %})
        data:
          images:
            - /config/www/CCTV_Snapshots/LivingRoom.jpg
            - /config/www/CCTV_Snapshots/Kitchen.jpg
            - /config/www/CCTV_Snapshots/Fire7.jpg
            - /config/www/CCTV_Snapshots/Front.jpg
            - /config/www/CCTV_Snapshots/Side.jpg
            - /config/www/CCTV_Snapshots/Back.jpg
            - /config/www/CCTV_Snapshots/Garage.jpg
    - service: notify.ios_lolos_iphone
      data_template:
        message: >
          ALARM! The alarm has been triggered !(
          ({% for windoor in state_attr("group.door_and_window_sensors","entity_id")|list  -%}
          {% if is_state(windoor,"on") %}{{state_attr(windoor, "friendly_name")}}, {% endif %}
          {%- endfor -%}
          {% if is_state('binary_sensor.main_door','on') %}Main Door,{% endif%}
          {% for mypirs in state_attr("group.pirs","entity_id")|list  -%}
          {% if is_state(mypirs ,"on") %}{{state_attr(mypirs , "friendly_name")}}, {% endif %}
          {%- endfor %})
        data:
          push:
            badge: '{{states("counter.iosbadgecount")}}'
            category: "alarm"
          attachment:
            url: !secret url_cctv_living_room
          action_data:
            entity_id: '{{trigger.entity_id}}'


- alias: 'Alarm - Stop arming when windows left open'
  initial_state: true
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'pending'
      from: 'disarmed'
  condition:
    - condition: state
      entity_id: group.door_and_window_sensors
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_7811dcdae94a
    - service: tts.google_say
      data_template:
        entity_id: media_player.google_home_minis
        message: |
          Please note, one or more windows are left open. Disarming alarm...
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code
    - delay:
        seconds: 2
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_home_minis
        volume_level: '{% if as_timestamp(now()) | timestamp_custom("%-H") | float >= 7 and as_timestamp(now()) | timestamp_custom("%-H") | float < 20 %} 0.75 {% else %} 0.5 {% endif %}' 


- alias: 'Alarm - Pending Arming'
  initial_state: true
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'pending'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.kerui_disarm
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_home_minis
        volume_level: '1' 
    - service: media_player.play_media
      data:
        entity_id: media_player.google_home_minis
        media_content_id: 'http://192.168.0.24/audio/Alarm-CountDown.mp3'
        media_content_type: 'audio/mp3'
    - wait_template: "{{ is_state('binary_sensor.main_door', 'on') }}"
      timeout: '00:00:30'
      continue_on_timeout: 'true'
    - wait_template: "{{ is_state('binary_sensor.main_door', 'off') }}"
      timeout: '00:00:30'
      continue_on_timeout: 'true'
    - condition: template
      value_template: '{{states("alarm_control_panel.alarm")=="armed_away" or states("alarm_control_panel.alarm")=="armed_home" or states("alarm_control_panel.alarm")=="pending" }}'
    - service: media_player.play_media
      data:
        entity_id: media_player.google_home_minis
        media_content_id: 'http://192.168.0.24/audio/Armed_Disarmed.mp3'
        media_content_type: 'audio/mp3'
    - service: script.turn_on
      data:
        entity_id: script.flash_aqara_light


- alias: 'Alarm - Pending Siren'
  initial_state: true
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'pending'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.kerui_disarm
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_home_minis
        volume_level: '1' 
    - service: media_player.play_media
      data:
        entity_id: media_player.google_home_minis
        media_content_id: 'http://192.168.0.24/audio/Alarm-CountDown.mp3'
        media_content_type: 'audio/mp3'
    - service: script.turn_on
      data:
        entity_id: script.flash_aqara_light


- alias: 'Alarm - Disarming'
  initial_state: true
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'disarmed'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.kerui_disarm
    # - service: media_player.play_media
      # data:
        # media_content_id: 'http://192.168.0.24/audio/1sec.mp3'
        # media_content_type: 'audio/mp3'
    - service: switch.turn_on
      data:
        entity_id: switch.kerui_disarm
    - service: media_player.play_media
      data:
        entity_id: media_player.google_home_minis
        media_content_id: 'http://192.168.0.24/audio/Armed_Disarmed.mp3'
        media_content_type: 'audio/mp3'
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_7811dcdae94a
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_home_minis
        volume_level: '{% if as_timestamp(now()) | timestamp_custom("%-H") | float >= 7 and as_timestamp(now()) | timestamp_custom("%-H") | float < 20 %} 0.75 {% else %} 0.5 {% endif %}'
    # - service: media_player.turn_off
      # entity_id: media_player.panasonic_viera_tv
    # - service: media_player.turn_off
      # entity_id: media_player.onkyo_tx_nr656



- alias: 'Alarm - Armed'
  initial_state: true
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_away'
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_home'
  action:
    - service: media_player.play_media
      data:
        entity_id: media_player.google_home_minis
        media_content_id: 'http://192.168.0.24/audio/Armed_Disarmed.mp3'
        media_content_type: 'audio/mp3'
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_7811dcdae94a
        brightness: 255
        rgb_color: [255,0,0]





- alias: 'Alarm - Fire Alarm'
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.smoke_sensor_158d0001e642ae
        - binary_sensor.smoke_sensor_158d000205ac9c
      to: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.fire7
        filename: '/config/www/CCTV_Snapshots/Fire7.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.kitchen
        filename: '/config/www/CCTV_Snapshots/Kitchen.jpg'
    - service: camera.snapshot
      data:
        entity_id: camera.living_room
        filename: '/config/www/CCTV_Snapshots/LivingRoom.jpg'
    - service: notify.gmaillolo
      data_template:
        message: >
          FIRE ALARM! Smoke detected on the {% if trigger.entity_id == 'binary_sensor.smoke_sensor_158d000205ac9c' %}Ground Floor Smoke Detector{% else %}First Floor Smoke Detector{% endif %}
        data:
          images:
            - /config/www/CCTV_Snapshots/LivingRoom.jpg
            - /config/www/CCTV_Snapshots/Kitchen.jpg
    - service: notify.gmaildiv
      data_template:
        message: >
          FIRE ALARM! Smoke detected on the {% if trigger.entity_id == 'binary_sensor.smoke_sensor_158d000205ac9c' %}Ground Floor Smoke Detector{% else %}First Floor Smoke Detector{% endif %}
        data:
          images:
            - /config/www/CCTV_Snapshots/LivingRoom.jpg
            - /config/www/CCTV_Snapshots/Kitchen.jpg
            - /config/www/CCTV_Snapshots/Fire7.jpg
    - service: notify.ios_lolos_iphone
      data_template:
        message: >
          FIRE ALARM!({% if trigger.entity_id == 'binary_sensor.smoke_sensor_158d0001e642ae' %}Gnd Floor Smoke Detector{% else %}1st Floor Smoke Detector{% endif %})
        data:
          push:
            badge: '{{states("counter.iosbadgecount")}}'
            category: "alarm"
          action_data:
            entity_id: '{{trigger.entity_id}}'





- alias: 'Alarm - Start Charging Fire 7'
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.fire7_battery
  condition:
    - condition: template
      value_template: "{{ states('sensor.fire7_battery')|int < 45 }}"
    - condition: state
      entity_id: switch.0220016868c63aa168d9
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.0220016868c63aa168d9

- alias: 'Alarm - Stop Charging Fire 7'
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.fire7_battery
  condition:
    - condition: template
      value_template: "{{ states('sensor.fire7_battery')|int > 85 }}"
    - condition: state
      entity_id: switch.0220016868c63aa168d9
      state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.0220016868c63aa168d9


- alias: 'Alarm - Switch everything off when we leave home'
  initial_state: true
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_away'
  action:
  - service: media_player.turn_off
    entity_id: media_player.kitchen
  - service: media_player.turn_off
    entity_id: media_player.onkyo_tx_nr656
  - service: media_player.turn_off
    entity_id: media_player.conservatory
  - service: media_player.turn_off
    entity_id: media_player.house
  - service: media_player.turn_off
    entity_id: media_player.downstairs
  - service: input_boolean.turn_on
    entity_id: input_boolean.silent
  - service: input_boolean.turn_off
    entity_id: input_boolean.normal
  - service: light.turn_off
    data:
      entity_id: group.Interior_Lights
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - service: input_boolean.turn_on
    entity_id: input_boolean.normal
  - service: input_boolean.turn_off
    entity_id: input_boolean.silent


- alias: 'Alarm - Re-arm Alarm after unplanned reboot'
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay:
        seconds: 2
    - condition: state
      entity_id: light.gateway_light_7811dcdae94a
      state: 'on'
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: Alarm - Remote Arm
  initial_state: true
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.kerui_remote_lock
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

- alias: Alarm - Remote Disarm
  initial_state: true
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.kerui_remote_unlock
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code


- alias: Alarm - Notify to Arm when leaving home unarmed
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.div
      from: "home"
    - platform: state
      entity_id: person.laurent
      from: "home"
  condition:
    - condition: template
      value_template: "{{ states('alarm_control_panel.alarm') == 'disarmed' }}"
  action:
    - delay:
        minutes: 2
    - condition: template
      value_template: '{{ states("person.laurent") != "home"}}'
    - condition: template
      value_template: '{{ states("person.div") != "home"}}'
    - service: notify.ios_lolos_iphone
      data_template:
        message: 'The alarm has not been armed !'
        data:
          push:
            badge: '{{states("counter.iosbadgecount")}}'
            category: "armalarm"
          action_data:
            entity_id: alarm_control_panel.alarm
    - service: notify.ios_diviphone
      data_template:
        message: 'The alarm has not been armed !'
        data:
          push:
            badge: '{{states("counter.iosbadgecount")}}'
            category: "armalarm"
          action_data:
            entity_id: alarm_control_panel.alarm

- alias: Alarm - Arm Alarm from iOS Notification
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: ARM_ALARM
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm
      data:
        code: !secret alarm_code

# {% for state in states.group.door_and_window_sensors.attributes['entity_id']  -%}
  # {% if is_state(state,"on")%}{{state_attr(state,"friendly_name")}}, {%else%}{% endif %} 
# {%- endfor %}