- alias: Alert - Temperature Upstairs Lost On
  id: alert_-_temperature_upstairs_lost_on
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.sensor.upstairs_temperature.last_updated | default(0)) | int > 3600 )}}'
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.sensor.upstairs_humidity.last_updated | default(0)) | int > 3600 )}}'
    - condition: state
      entity_id: alert.upstairs_temp_sensor_lost
      state: 'idle'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.upstairs_temp_sensor_lost

- alias: Alert - Temperature Upstairs Lost Off
  id: alert_-_temperature_upstairs_lost_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.upstairs_temperature
    - platform: state
      entity_id: sensor.upstairs_humidity
  condition:
    - condition: template
      value_template: '{{states("alert.upstairs_temp_sensor_lost") != "idle"}}'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.upstairs_temp_sensor_lost




- alias: Alert - Temperature Loft Lost On
  id: alert_-_temperature_loft_lost_on
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.sensor.loft_temperature.last_updated | default(0)) | int > 3600 )}}'
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.sensor.loft_humidity.last_updated | default(0)) | int > 3600 )}}'
    - condition: state
      entity_id: alert.outside_temp_sensor_lost
      state: 'idle'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.outside_temp_sensor_lost

- alias: Alert - Temperature Loft Lost Off
  id: alert_-_temperature_loft_lost_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.loft_temperature
    - platform: state
      entity_id: sensor.loft_humidity
  condition:
    - condition: template
      value_template: '{{states("alert.outside_temp_sensor_lost") != "idle"}}'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.outside_temp_sensor_lost




- alias: Alert - CurrentCost Lost On
  id: alert_-_currentcost_lost_on
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.sensor.currentcost_power.last_updated | default(0)) | int > 300 )}}'
    - condition: state
      entity_id: alert.currentcost_lost
      state: 'idle'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_lost_currentcost_power_at_300

- alias: Alert - CurrentCost Lost Off
  id: alert_-_currentcost_lost_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.currentcost_power
  condition:
    - condition: template
      value_template: '{{states("alert.currentcost_lost") != "idle"}}'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.alert_lost_currentcost_power_at_300




- alias: Alert - RAM Lost On
  id: alert_-_ram_lost_on
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.sensor.ram_usage.last_updated | default(0)) | int > 300 )}}'
    - condition: state
      entity_id: alert.ram_lost_on
      state: 'idle'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_lost_ram_usage_at_300

- alias: Alert - RAM Lost Off
  id: alert_-_ram_lost_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ram_usage
  condition:
    - condition: template
      value_template: '{{states("alert.ram_lost_on") != "idle"}}'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.alert_lost_ram_usage_at_300




- alias: Alert - Fire 7 Lost On
  id: alert_-_fire_7_lost_on
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.sensor.fire7_battery.last_updated | default(0)) | int > 3600 )}}'
    - condition: state
      entity_id: alert.fire7_lost
      state: 'idle'
  action:
    - service: shell_command.fire7_reload_url
    - delay: "00:01:00"
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.sensor.fire7_battery.last_updated | default(0)) | int > 3600 )}}'
    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_lost_fire7_at_300

- alias: Alert - Fire 7 Lost Off
  id: alert_-_fire_7_lost_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.fire7_battery
  condition:
    - condition: template
      value_template: '{{states("alert.fire7_lost") != "idle"}}'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.alert_lost_fire7_at_300




- alias: Alert - Pi Kitchen Lost On
  id: alert_-_pi_kitchen_lost_on
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.sensor.rpi_kitchen_heartbeat.last_updated | default(0)) | int > 300 )}}'
    - condition: state
      entity_id: alert.rpi_kitchen_lost
      state: 'idle'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.alert_lost_rpi_kitchen_at_300

- alias: Alert - Pi Kitchen Lost Off
  id: alert_-_pi_kitchen_lost_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.rpi_kitchen_heartbeat
  condition:
    - condition: template
      value_template: '{{states("alert.rpi_kitchen_lost") != "idle"}}'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.alert_lost_rpi_kitchen_at_300

