- alias: Bathroom - Turn Fan On When R% too high
  id: bathroom_turn_fan_on_when_r_too_high
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.bathroom_humidity
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: '{{ states("sensor.bathroom_humidity") | int >= states("input_number.bathroom_humidity_target") | int }}'
    - condition: state
      entity_id: switch.bathroom_fan
      state: 'off'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.bathroom_fan

- alias: Bathroom - Turn Fan Off When R% normal
  id: bathroom_turn_fan_on_when_r_normal
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathroom_humidity
      below: input_number.bathroom_humidity_target
      for:
        minutes: 20
    - platform: state
      entity_id: switch.bathroom_fan
      to: 'on'
      for:
        minutes: 59
  condition:
    - condition: state
      entity_id: switch.bathroom_fan
      state: 'on'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.bathroom_fan

- alias: Bathroom - Toggle Fan From Aqara Button
  id: bathroom_toggle_fan_from_aqara_button
  initial_state: true
  mode: restart
  trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/aqara_toggle_bathroom'
  action:
  - condition: template
    value_template: '{{ trigger.payload_json.click == "single" }}'
  - service: switch.toggle
    data:
      entity_id: switch.bathroom_fan

- alias: Bathroom - Set R% Target
  id: bathroom_set_humidity_target
  initial_state: true
  mode: restart
  trigger:
    - platform: time_pattern
      minutes: '/5'
      seconds: 0
  condition:
    - condition: state
      entity_id: switch.bathroom_fan
      state: 'off'
  action:
  - service: input_number.set_value
    data:
      entity_id: input_number.bathroom_humidity_target
      value: '{{ (( states("sensor.pooja_humidity") | int + states("sensor.master_bedroom_humidity") | int ) /2 * 1.25 ) | int}}'