- alias: Bins - Nightly Refresh
  id: bins_nightly_refresh
  initial_state: true
  trigger:
    platform: time_pattern
    hours: "4"
    minutes: 0
    seconds: 0
  action:
  - service: shell_command.refresh_bin_collection



- alias: Bins - Update Calendar (black, green)
  id: bins_update_calendar_black_green
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.black_bin, sensor.green_bin
  condition:
    - condition: template
      value_template: '{{ trigger.to_state.state != trigger.from_state.state and trigger.from_state.state != "unknown"}} '
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states("sensor.uptime")) | int > 30)}}'
  action:
  - service: google.add_event
    data:
      calendar_id: !secret google_family_calendar
      summary: '{{ trigger.entity_id | replace("sensor.","") | replace("_bin","") | title }} Bin Collection'
      description: '{{ trigger.entity_id | replace("sensor.","") | replace("_bin","") | title }} Bin Collection'
      start_date_time: '{{ (as_timestamp(trigger.to_state.state) + 7 * 60 * 60) | timestamp_custom ("%Y-%m-%d %H:%M:%S")}}'
      end_date_time: '{{ (as_timestamp(trigger.to_state.state) + 12 * 60 * 60) | timestamp_custom ("%Y-%m-%d %H:%M:%S")}}'



- alias: Bins - Update Calendar (red)
  id: bins_update_calendar_red
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.red_bin
  condition:
    - condition: template
      value_template: '{{ trigger.to_state.state != trigger.from_state.state and trigger.from_state.state != "unknown"}} '
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states("sensor.uptime")) | int > 30)}}'
  action:
  - service: google.add_event
    data:
      calendar_id: !secret google_family_calendar
      summary: 'Red Bin Collection'
      description: 'Red Bin Collection'
      start_date_time: '{{ (as_timestamp(trigger.to_state.state) + 7 * 60 * 60) | timestamp_custom ("%Y-%m-%d %H:%M:%S")}}'
      end_date_time: '{{ (as_timestamp(trigger.to_state.state) + 12 * 60 * 60) | timestamp_custom ("%Y-%m-%d %H:%M:%S")}}'

- alias: Bins - Announcement
  id: bins_announcement
  initial_state: true
  trigger:
    platform: time_pattern
    hours: "19"
    minutes: 0
    seconds: 0
  condition:
    - condition: template
      value_template: >-
        {{
        ((as_timestamp(states("sensor.black_bin")) - as_timestamp(now())) < 21700 and (as_timestamp(states("sensor.black_bin")) - as_timestamp(now())) > 0)
        or
        ((as_timestamp(states("sensor.red_bin")) - as_timestamp(now())) < 21700 and (as_timestamp(states("sensor.red_bin")) - as_timestamp(now())) > 0)
        or
        ((as_timestamp(states("sensor.green_bin")) - as_timestamp(now())) < 21700 and (as_timestamp(states("sensor.green_bin")) - as_timestamp(now())) > 0)
        }}
  action:
    - service: notify.gmaillolo
      data_template:
        title: "HA - Bins"
        message: |
          Remember to put {%- if ((as_timestamp(states("sensor.black_bin")) - as_timestamp(now())) < 2217000000 and (as_timestamp(states("sensor.black_bin")) - as_timestamp(now())) > 0) %} the black bin {% endif -%}
          {%- if ((as_timestamp(states("sensor.red_bin")) - as_timestamp(now())) < 21700 and (as_timestamp(states("sensor.red_bin")) - as_timestamp(now())) > 0) %}and the red bin {% endif -%}
          {%- if ((as_timestamp(states("sensor.green_bin")) - as_timestamp(now())) < 21700 and (as_timestamp(states("sensor.green_bin")) - as_timestamp(now())) > 0) %} the green bin {% endif -%}
          out
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: >
          Remember to put {%- if ((as_timestamp(states("sensor.black_bin")) - as_timestamp(now())) < 21700 and (as_timestamp(states("sensor.black_bin")) - as_timestamp(now())) > 0) %} the black bin {% endif -%}
          {%- if ((as_timestamp(states("sensor.red_bin")) - as_timestamp(now())) < 21700 and (as_timestamp(states("sensor.red_bin")) - as_timestamp(now())) > 0) %}and the red bin {% endif -%}
          {%- if ((as_timestamp(states("sensor.green_bin")) - as_timestamp(now())) < 21700 and (as_timestamp(states("sensor.green_bin")) - as_timestamp(now())) > 0) %} the green bin {% endif -%}
          out
  