- alias: Blinds - Open When Not Dark
  id: blinds_open_when_not_dark
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.dark
      to: 'off'
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.blinds_open_when_not_dark", "last_triggered")) | int(0) > 300)}}'
    - condition: template
      value_template: '{{ states("cover.kitchen_blinds") != "open" and states("cover.livingroom_blinds") != "open" }}'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.holidays
        state: 'on'
    - condition: template
      value_template: '{{state_attr("weather.tomorrow_io_home_nowcast","temperature") | int(20) < 20}}'
  action:
  - service: cover.open_cover
    data:
      entity_id:
        - cover.kitchen_blinds
        - cover.livingroom_blinds

- alias: Blinds - Close When Dark
  id: blinds_close_when_dark
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.dark
      to: 'on'
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.blinds_open_when_not_dark", "last_triggered")) | int(0) > 5)}}'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.holidays
        state: 'on'
  action:
  - service: cover.close_cover
    data:
      entity_id:
        - cover.kitchen_blinds
        - cover.livingroom_blinds


- alias: Blinds - Close When Movies On
  id: blinds_close_when_movies_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.movies
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.livingroom_blinds
      state: 'open'
  action:
  - service: cover.close_cover
    data:
      entity_id:
        - cover.livingroom_blinds

- alias: Blinds - Open When Movies Off
  id: blinds_open_when_movies_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.movies
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.dark
      state: 'off'
  action:
  - service: cover.open_cover
    data:
      entity_id:
        - cover.livingroom_blinds


- alias: Blinds - Close Living Room if too hot outside
  id: blinds_close_living_room_if_too_hot_outside
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: state
      entity_id: cover.livingroom_blinds
      state: 'open'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.blinds_close_living_room_if_too_hot_outside", "last_triggered")) | int > 7200)}}'
    - condition: template
      value_template: '{{states("weather.tomorrow_io_home_nowcast") in ["partlycloudy","sunny"]}}'
    - condition: template
      value_template: '{{state_attr("weather.tomorrow_io_home_nowcast","temperature") | int(0) > 20}}'
    - condition: template
      value_template: "{{not (state_attr('sun.sun', 'rising'))}}"
    - condition: template
      value_template: "{{state_attr('sun.sun', 'elevation') | int(0) >= 20}}"
  action:
  - service: cover.close_cover
    data:
      entity_id:
        - cover.livingroom_blinds
