- alias: Blinds - Open When Not Dark
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.dark
      to: 'off'
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.blinds_open_when_not_dark", "last_triggered") | default(0)) | int > 300)}}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.lights_all_lights_off_sunrise", "last_triggered") | default(0)) | int > 300)}}'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.holidays
        state: 'on'
    - condition: template
      value_template: "{{states('sensor.dark_sky_temperature') | int < 20}}"
  action:
  - service: cover.open_cover
    data:
      entity_id:
        - cover.kitchen_blinds
        - cover.livingroom_blinds

- alias: Blinds - Close When Dark
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.dark
      to: 'on'
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.blinds_open_when_not_dark", "last_triggered") | default(0)) | int > 300)}}'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.holidays
        state: 'on'
  action:
  - service: cover.close_cover
    data:
      entity_id:
        - cover.kitchen_blinds
        - cover.livingroom_blinds


- alias: Blinds - Close When Movies On
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.movies
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.livingroom_blinds
      state: 'open'
  action:
  - service: cover.close_cover
    data:
      entity_id:
        - cover.livingroom_blinds

- alias: Blinds - Open When Movies Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.movies
      to: 'off'
  condition:
    - condition: template
      value_template: "states('sensor.aqara_illumination') | int < 200"
  action:
  - service: cover.open_cover
    data:
      entity_id:
        - cover.livingroom_blinds


- alias: Blinds - Close Living Room if too hot outside
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: state
      entity_id: cover.livingroom_blinds
      state: 'open'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.blinds_close_living_room_if_too_hot_outside", "last_triggered") | default(0)) | int > 7200)}}'
    - condition: template
      value_template: "{{states('weather.dark_sky') == 'sunny' or states('weather.dark_sky') == 'partlycloudy'}}"
    - condition: template
      value_template: "{{states('sensor.dark_sky_temperature') | int > 20}}"
    - condition: template
      value_template: "{{not (state_attr('sun.sun', 'rising'))}}"
    - condition: template
      value_template: "{{state_attr('sun.sun', 'elevation') | int >= 20}}"
  action:
  - service: cover.close_cover
    data:
      entity_id:
        - cover.livingroom_blinds
