- alias: BMW - Windows/Doors left open
  id: bmw_windows_doors_left_open
  initial_state: true
  trigger:
    - platform: state
      entity_id: lock.220d_lock
      to: 'locked'
  action:
    - service: button.press
      target:
        entity_id: button.220d_refresh_from_cloud
    - wait_template: '{{(as_timestamp(now()) - as_timestamp(states.device_tracker["220d"].last_updated) | int > 300 )}}'
      timeout: '00:06:00'
      continue_on_timeout: true
    - condition: template
      value_template: >
        {%- set doors = [
              states.binary_sensor.bmw_220d_windowdriverdront,
              states.binary_sensor.bmw_220d_windowdriverrear,
              states.binary_sensor.bmw_220d_windowpassengerfront,
              states.binary_sensor.bmw_220d_windowpassengerrear,
              states.binary_sensor.bmw_220d_doordriverdront,
              states.binary_sensor.bmw_220d_doordriverrear,
              states.binary_sensor.bmw_220d_doorpassengerfront,
              states.binary_sensor.bmw_220d_doorpassengerrear,
              states.binary_sensor.bmw_220d_hood,
              states.binary_sensor.bmw_220d_trunk] -%}
        {%- set doors_on = doors | selectattr('state','eq','on') | list -%}
        {{ ((doors_on | length) | int ) >= 1}}
    - service: notify.gmaillolo
      data:
        title: "HA - BMW"
        message: >
          The following BMW doors/windows are not closed: 
          {% set doors = [
                states.binary_sensor.bmw_220d_windowdriverdront,
                states.binary_sensor.bmw_220d_windowdriverrear,
                states.binary_sensor.bmw_220d_windowpassengerfront,
                states.binary_sensor.bmw_220d_windowpassengerrear,
                states.binary_sensor.bmw_220d_doordriverdront,
                states.binary_sensor.bmw_220d_doordriverrear,
                states.binary_sensor.bmw_220d_doorpassengerfront,
                states.binary_sensor.bmw_220d_doorpassengerrear,
                states.binary_sensor.bmw_220d_hood,
                states.binary_sensor.bmw_220d_trunk] -%}
          {%- set doors_on = doors | selectattr('state','eq','on') | list -%}
          {% for door_names in doors_on -%}
          {{(door_names | string).split("friendly_name=")[1].split(" @")[0]}}, 
          {%- endfor %}

- alias: BMW - iOS Notification Car Unlocked
  id: bmw_ios_notification_car_unlocked
  initial_state: true
  trigger:
    - platform: state
      entity_id: lock.220d_lock
      to: 'unlocked'
  action:
    - service: button.press
      target:
        entity_id: button.220d_refresh_from_cloud
    - wait_template: '{{(as_timestamp(now()) - as_timestamp(states.device_tracker["220d"].last_updated) | int > 300 )}}'
      timeout: '00:06:00'
      continue_on_timeout: true
    - condition: template
      value_template: '{{state_attr("device_tracker.lolo_iphone","travel_distance") |int < 10}}'
    - service: notify.mobile_app_lolo_iphone
      data:
        message: "BMW 220d Not Locked !"
        data:
          actions:
            - action: "LOCK_BMW"
              title: "Lock BMW"
              destructive: yes

- alias: BMW - iOS Notification Lock Car
  id: bmw_ios_notification_lock_car
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: LOCK_BMW
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: LOCK_BMW
  action:
    - service: lock.lock
      data:
        entity_id: lock.220d_lock

- alias: BMW - Ventilate the car from iOS Notification
  id: bmw_ventilate_the_car_from_ios_notification
  initial_state: true
  trigger:
    # iOS 2.0 App Support
    - platform: event
      event_type: ios.action_fired
      event_data:
        action: BMW_VENTILATE
  action:
    - service: button.press
      target:
        entity_id: button.220d_activate_air_conditioning



- alias: BMW - Ventilate When Temp Above 20
  id: bmw_ventilate_when_temp_above_20
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "16"
      minutes: 0
      seconds: 0
    # - platform: time_pattern
    #   hours: "17"
    #   minutes: 25
    #   seconds: 0
  condition:
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "off"
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
    - condition: template
      value_template: '{{state_attr("weather.pirateweather","temperature") | int(0) >= 20}}'
    - condition: or
      conditions:
      # - condition: template
      #   value_template: '{{now().hour == 17 and now().minute == 25 and states("device_tracker.220d") == "home" and states("person.laurent") == "home" and states("person.div") != "home" and (as_timestamp(now()) | timestamp_custom("%a") == "Fri" or as_timestamp(now()) | timestamp_custom("%a") == "Mon")}}'
      - condition: template
        value_template: '{{now().hour == 16 and now().minute == 0 and states("device_tracker.220d") == "verint" and (as_timestamp(now()) | timestamp_custom("%a") == "Tue" or as_timestamp(now()) | timestamp_custom("%a") == "Wed" or as_timestamp(now()) | timestamp_custom("%a") == "Thu")}}'
  action:
    - service: button.press
      target:
        entity_id: button.220d_activate_air_conditioning



- alias: Astra - Toggle Deep Sleep
  id: astra_toggle_deep_sleep
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.astra_car_battery_network_status
    - platform: homeassistant
      event: start
  action:
    - wait_template: '{{ states("sensor.astra_car_battery_voltage") | float(0) >= 14 }}'
      timeout: '00:00:30'
      continue_on_timeout: true
    - service: '{% if states("binary_sensor.astra_car_battery_network_status") == "on" %}switch.turn_off{% else %}switch.turn_on{% endif %}'
      data:
        entity_id: switch.astra_car_battery_deep_sleep_wake

- alias: Astra - Battery Low
  id: astra_battery_low
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.astra_car_battery_voltage
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(this.attributes.last_triggered) | int > 60)}}'
    - condition: template
      value_template: '{{states("sensor.astra_car_battery_voltage") != "unavailable" and states("sensor.astra_car_battery_voltage") != "unknown" and states("sensor.astra_car_battery_voltage") | float(0) <= 11.85}}'
  action:
    - service: notify.gmaillolo
      data:
        title: "HA - Astra"
        message: >
          The Astra car battery is low! ({{states("sensor.astra_car_battery_voltage")}} V)