- alias: CCTV - Email when Front CCTV Disk Error
  id: cctv_email_when_front_cctv_disk_error
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.front_cctv_disk_error
    to: 'on'
  action:
  - service: notify.gmaillolo
    data:
      title: "HA - CCTV Error"
      message: Disk Error Detected on Front CCTV.

- alias: CCTV - Email when Front CCTV SD Card Full
  id: cctv_email_when_front_cctv_sd_card_full
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.front_cctv_disk_full
    to: 'on'
  action:
  - service: notify.gmaillolo
    data:
      title: "HA - CCTV Error"
      message: SD Card on Front CCTV is full.


- alias: CCTV - Email when Back CCTV Disk Error
  id: cctv_email_when_back_cctv_disk_error
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.back_cctv_disk_error
    to: 'on'
  action:
  - service: notify.gmaillolo
    data:
      title: "HA - CCTV Error"
      message: Disk Error Detected on Back CCTV.

- alias: CCTV - Email when Back CCTV SD Card Full
  id: cctv_email_when_back_cctv_sd_card_full
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.back_cctv_disk_full
    to: 'on'
  action:
  - service: notify.gmaillolo
    data:
      title: "HA - CCTV Error"
      message: SD Card on Back CCTV is full.


- alias: CCTV - Email when Side CCTV Disk Error
  id: cctv_email_when_side_cctv_disk_error
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.side_cctv_disk_error
    to: 'on'
  action:
  - service: notify.gmaillolo
    data:
      title: "HA - CCTV Error"
      message: Disk Error Detected on Side CCTV.

- alias: CCTV - Email when Side CCTV SD Card Full
  id: cctv_email_when_side_cctv_sd_card_full
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.side_cctv_disk_full
    to: 'on'
  action:
  - service: notify.gmaillolo
    data:
      title: "HA - CCTV Error"
      message: SD Card on Side CCTV is full.

- alias: CCTV - Activate motion we leave home
  id: cctv_activate_motion_we_leave_home
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.laurent
      from: "home"
    - platform: state
      entity_id: person.div
      from: "home"
  condition:
    - condition: template
      value_template: '{{ states("person.laurent") != "home"}}'
    - condition: template
      value_template: '{{ states("person.div") != "home"}}'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.conservatory_detect,switch.conservatory_recordings,switch.conservatory_snapshots
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_detect,switch.kitchen_recordings,switch.kitchen_snapshots
    - service: switch.turn_on
      data:
        entity_id: switch.living_room_detect,switch.living_room_recordings,switch.living_room_snapshots

    # - service: mqtt.publish
    #   data:
    #     topic: frigate/conservatory/detect/state
    #     payload: "ON"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/conservatory/recordings/state
    #     payload: "ON"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/conservatory/snapshots/state
    #     payload: "ON"
    #     retain: true
  
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/kitchen/detect/state
    #     payload: "ON"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/kitchen/recordings/state
    #     payload: "ON"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/kitchen/snapshots/state
    #     payload: "ON"
    #     retain: true
    
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/living_room/detect/state
    #     payload: "ON"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/living_room/recordings/state
    #     payload: "ON"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/living_room/snapshots/state
    #     payload: "ON"
    #     retain: true

    # - service: switch.turn_on
    #   entity_id:
    #     - switch.dafang_living_room_status
    #     - switch.dafang_kitchen_status
    #     - switch.cctv_conservatory_status
    #     - switch.cctv_staircase_status

- alias: CCTV - Deactivate motion we reach home
  id: cctv_deactivate_motion_we_reach_home
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.laurent
      to: "home"
    - platform: state
      entity_id: person.div
      to: "home"
    - platform: state
      entity_id: switch.dafang_living_room_status
      to: "on"
    - platform: state
      entity_id: switch.dafang_kitchen_status
      to: "on"
    - platform: state
      entity_id: switch.cctv_conservatory_status
      to: "on"
  condition:
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("person.laurent") == "home"}}'
      - condition: template
        value_template: '{{ states("person.div") == "home"}}'
      - condition: state
        entity_id: input_boolean.guests
        state: 'on'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.conservatory_detect,switch.conservatory_recordings,switch.conservatory_snapshots
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_detect,switch.kitchen_recordings,switch.kitchen_snapshots
    - service: switch.turn_off
      data:
        entity_id: switch.living_room_detect,switch.living_room_recordings,switch.living_room_snapshots

    # - service: mqtt.publish
    #   data:
    #     topic: frigate/conservatory/detect/state
    #     payload: "OFF"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/conservatory/recordings/state
    #     payload: "OFF"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/conservatory/snapshots/state
    #     payload: "OFF"
    #     retain: true
  
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/kitchen/detect/state
    #     payload: "OFF"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/kitchen/recordings/state
    #     payload: "OFF"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/kitchen/snapshots/state
    #     payload: "OFF"
    #     retain: true
    
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/living_room/detect/state
    #     payload: "OFF"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/living_room/recordings/state
    #     payload: "OFF"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: frigate/living_room/snapshots/state
    #     payload: "OFF"
    #     retain: true

    # - service: switch.turn_off
    #   entity_id:
    #     - switch.dafang_living_room_status
    #     - switch.dafang_kitchen_status
    #     - switch.cctv_conservatory_status
    #     - switch.cctv_staircase_status


# - alias: CCTV - Set Dafang Blue LED On
#   id: cctv_set_dafang_blue_led_on
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: switch.dafang_living_room_status
#       to: 'on'
#     - platform: state
#       entity_id: switch.dafang_kitchen_status
#       to: 'on'
#   action:
#   - service: switch.turn_on
#     data:
#       entity_id: '{{ trigger.entity_id | replace("status","blue_led") }}'

# - alias: CCTV - Set Dafang Yellow LED On
#   id: cctv_set_dafang_yellow_led_on
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: switch.dafang_living_room_status
#       to: 'off'
#     - platform: state
#       entity_id: switch.dafang_kitchen_status
#       to: 'off'
#   action:
#   - service: switch.turn_on
#     data:
#       entity_id: '{{ trigger.entity_id | replace("status","yellow_led") }}'


# - alias: CCTV - Kitchen CCTV Motion Connection Lost
#   id: cctv_kitchen_cctv_motion_connection_lost
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: sensor.dafang_kitchen_connection_scrape
#       to: 'Lost connection'
#       for:
#         minutes: 3
#   action:
#   - service: notify.gmaillolo
#     data:
#       title: "HA - CCTV Error"
#       message: Kitchen CCTV Motion Connection Lost!


# - alias: CCTV - Living Room CCTV Motion Connection Lost
#   id: cctv_living_room_cctv_motion_connection_lost
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: sensor.dafang_living_room_connection_scrape
#       to: 'Lost connection'
#       for:
#         minutes: 3
#   action:
#   - service: notify.gmaillolo
#     data:
#       title: "HA - CCTV Error"
#       message: Living Room CCTV Motion Connection Lost!


# - alias: CCTV - Garage CCTV Motion Connection Lost
#   id: cctv_garage_cctv_motion_connection_lost
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: sensor.cctv_garage_connection_scrape
#       to: 'Lost connection'
#       for:
#         minutes: 3
#   action:
#   - service: notify.gmaillolo
#     data:
#       title: "HA - CCTV Error"
#       message: Garage CCTV Motion Connection Lost!


# - alias: CCTV - CCTV Conservatory Connection Lost
#   id: cctv_cctv_conservatory_connection_lost
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: sensor.cctv_conservatory_connection_scrape
#       to: 'Lost connection'
#       for:
#         minutes: 3
#   action:
#   - service: notify.gmaillolo
#     data:
#       title: "HA - CCTV Error"
#       message: Conservatory CCTV Motion Connection Lost!

