- alias: Chromecast - Set Radio Volume
  id: chromecast_set_radio_volume
  initial_state: true
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data:
      entity_id: >
        {% if is_state("input_select.chromecast_radio_speakers", "Conservatory") %} media_player.conservatory
        {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.kitchen
        {% elif is_state("input_select.chromecast_radio_speakers", "Living Room") %} media_player.living_room
        {% elif is_state("input_select.chromecast_radio_speakers", "House") %} media_player.house
        {% endif %}
      volume_level: '{{  states("input_number.volume_radio")  }}'


- alias: Chromecast - Set Speakers & Station
  id: chromecast_set_speakers_station
  initial_state: true
  trigger:
  - platform: state
    entity_id:
      - media_player.master_bedroom_nest_hub
      - media_player.conservatory
      - media_player.kitchen
      - media_player.living_room
      - media_player.house
    to: 'playing'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: '{{trigger.entity_id}}'
      is_volume_muted: false
  - service: input_select.select_option
    data:
      entity_id: input_select.chromecast_radio_speakers
      option: >
        {% if is_state(trigger.entity_id, "media_player.conservatory") %} Conservatory
        {% elif is_state(trigger.entity_id, "media_player.kitchen") %} Kitchen
        {% elif is_state(trigger.entity_id, "media_player.living_room") %} Living Room
        {% elif is_state(trigger.entity_id, "media_player.master_bedroom_nest_hub") %} Bedroom Nest Hub
        {% elif is_state(trigger.entity_id, "media_player.office_nest_hub") %} Office Nest Hub
        {% elif is_state(trigger.entity_id, "media_player.house") %} House
        {% endif %}
  - service: input_select.select_option
    data:
      entity_id: input_select.chromecast_radio_station
      option: >
        {% if (is_state_attr(trigger.entity_id, 'media_content_id', 'http://icy-e-bab-04-cr.sharp-stream.com/absoluteradio.mp3') or is_state_attr("media_player.house", 'media_content_id', 'http://icy-e-bab-04-cr.sharp-stream.com/absoluteradio.mp3')) %} Absolute Radio
        {% elif (is_state_attr(trigger.entity_id, 'media_content_id', 'http://icy-e-bab-04-cr.sharp-stream.com/absoluteclassicrock.mp3') or is_state_attr("media_player.house", 'media_content_id', 'http://icy-e-bab-04-cr.sharp-stream.com/absoluteclassicrock.mp3')) %} Absolute Radio Classic Rock
        {% elif (is_state_attr(trigger.entity_id, 'media_content_id', 'http://media-the.musicradio.com/ChillMP3') or is_state_attr("media_player.house", 'media_content_id', 'http://media-the.musicradio.com/ChillMP3')) %} Chill
        {% elif (is_state_attr(trigger.entity_id, 'media_content_id', 'http://broadcast.infomaniak.ch/hitwest-high.mp3') or is_state_attr("media_player.house", 'media_content_id', 'http://broadcast.infomaniak.ch/hitwest-high.mp3')) %} Hit West
        {% elif (is_state_attr(trigger.entity_id, 'media_content_id', states("sensor.ha_podcast")) or is_state_attr("media_player.house", 'media_content_id', states("sensor.ha_podcast"))) %} HA Podcast
        {% elif (is_state_attr(trigger.entity_id, 'media_content_id', states("sensor.internet_of_things_podcast")) or is_state_attr("media_player.house", 'media_content_id', states("sensor.internet_of_things_podcast"))) %} IoT Podcast
        {% elif (is_state_attr(trigger.entity_id, 'media_content_id', 'http://192.111.142.176:8000/NAVTARANG') or is_state_attr("media_player.house", 'media_content_id', 'http://192.111.142.176:8000/NAVTARANG')) %} Navtarang
        {% elif (is_state_attr(trigger.entity_id, 'media_content_id', 'http://peridot.streamguys.com:7150/RFTwo?play') or is_state_attr("media_player.house", 'media_content_id', 'http://peridot.streamguys.com:7150/RFTwo?play')) %} Radio Fiji Two
        {% elif (is_state_attr(trigger.entity_id, 'media_content_id', 'http://icecast.rtl2.fr/rtl2-1-44-128') or is_state_attr("media_player.house", 'media_content_id', 'http://icecast.rtl2.fr/rtl2-1-44-128')) %} RTL2
        {% elif (is_state_attr(trigger.entity_id, 'media_content_id', 'states("input_text.custom_station")') or is_state_attr("media_player.house", 'media_content_id', 'states("input_text.custom_station")')) %} Custom Station
        {% endif %}
  - condition: template
    value_template: '{{ ( states("media_player.onkyo_tx_nr656")=="off" or states("media_player.onkyo_tx_nr656_zone_2")=="off" ) and (states("media_player.house")=="playing" or states("media_player.living_room")=="playing" or states("media_player.conservatory")=="playing" )}}'
  - service: media_player.turn_on
    data:
      entity_id: media_player.onkyo_tx_nr656
  - service: media_player.select_source
    data:
      entity_id: media_player.onkyo_tx_nr656
      source: 'ChromeCast1'
  - service: media_player.turn_on
    data:
      entity_id: media_player.onkyo_tx_nr656_zone_2
  - service: media_player.select_source
    data:
      entity_id: media_player.onkyo_tx_nr656_zone_2
      source: 'ChromeCast2'

- alias: Onkyo - Turn Off When Stop Playing On ChromeCast
  id: onkyo_turn_off_when_stop_playing_on_chromecast
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.house
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: media_player.conservatory
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: media_player.kitchen
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: media_player.living_room
    to: 'off'
    for:
      minutes: 2
  condition:
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: media_player.house
      state: 'off'
    - condition: state
      entity_id: media_player.conservatory
      state: 'off'
    - condition: state
      entity_id: media_player.kitchen
      state: 'off'
    - condition: state
      entity_id: media_player.living_room
      state: 'off'
  action:
  - service: media_player.turn_off
    entity_id: media_player.onkyo_tx_nr656
  - service: media_player.turn_off
    entity_id: media_player.onkyo_tx_nr656_zone_2
    
- alias: ChromeCast - Stop ChromeCast When Turning Onkyo Off or Sky On
  id: chromecast_stop_chromecast_when_turning_onkyo_off_or_sky_on
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.onkyo_tx_nr656
    to: 'off'
  - platform: state
    entity_id: switch.skyhd
    to: 'on'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.conservatory, media_player.house, media_player.kitchen, media_player.living_room, media_player.onkyo_tx_nr656
      is_volume_muted: false
  - service: media_player.turn_off
    entity_id: media_player.house