- alias: Dark - Dark On
  id: dark_dark_on
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.illuminance_back
      below: 4
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.illuminance_front
      below: 35
      for:
        minutes: 5
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: input_boolean.dark
      state: 'off'
    - condition: template
      value_template: '{{ states("sensor.illuminance_back") | int(0) < 4 }}'
    - condition: template
      value_template: '{{ states("sensor.illuminance_front") | int(0) < 35 }}'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{now().hour <= 5}}'
      - condition: template
        value_template: '{{now().hour >= 4}}'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
      - condition: state
        entity_id: group.kitchen_lights
        state: 'on'
      - condition: state
        entity_id: light.hallway
        state: 'on'
      - condition: state
        entity_id: light.conservatory
        state: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dark

- alias: Dark - Dark Off
  id: dark_dark_off
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.illuminance_back
      above: 4
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.illuminance_front
      above: 35
      for:
        minutes: 5
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: input_boolean.dark
      state: 'on'
    - condition: template
      value_template: '{{ states("sensor.illuminance_back") | int(0) >= 4 }}'
    - condition: template
      value_template: '{{ states("sensor.illuminance_front") | int(0) >= 35 }}'
    - condition: template
      value_template: '{{now().hour > 5}}'
    - condition: template
      value_template: '{{now().hour < 4}}'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dark