- alias: Dehumidifier - Mark Dehumidifier Tank as not full
  id: dehumidifier_mark_dehumidifier_tank_as_not_full
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.dehumidifier_power
  condition:
    - condition: state
      entity_id: input_boolean.dehumidifier_tank_full
      state: 'on'
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.dehumidifier_tank_full



- alias: Dehumidifier - Turn LWRF Socket if Power but LWRF is Off
  id: dehumidifier_turn_lwrf_socket_if_power_but_lwrf_is_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.dehumidifier_power
  condition:
    - condition: state
      entity_id: switch.dehumidifier
      state: 'off'
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.switch.dehumidifier.last_updated) | int > 60 )}}'
    - condition: template
      value_template: '{{states("sensor.dehumidifier_power") | int > 10 }}'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.dehumidifier



- alias: Dehumidifier - Dehumidifier Tank is full
  id: dehumidifier_dehumidifier_tank_is_full
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.dehumidifier_power
      below: 1
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.dehumidifier_tank_full
      state: 'off'
    - condition: state
      entity_id: switch.dehumidifier
      state: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dehumidifier_tank_full
    - service: notify.gmaillolo
      data_template:
        title: "HA - Dehumidifier Full"
        message: |
          Dehumidifier Tank is full.
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Please note: The dehumidifier tank is full'


- alias: Dehumidifier - Start Dehumidifier
  id: dehumidifier_start_dehumidifier
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "8"
      minutes: 0
      seconds: 0
    - platform: state
      entity_id: sensor.upstairs_humidity, sensor.master_bedroom_humidity, sensor.pooja_humidity
  condition:
    - condition: time
      after: '08:00'
      before: '16:00'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: template
      value_template: '{{ states("sensor.season") != "Summer" }}'
    - condition: state
      entity_id: switch.dehumidifier
      state: 'off'
    - condition: template
      value_template: '{{(states("sensor.upstairs_humidity") | int  + states("sensor.master_bedroom_humidity") | int  + states("sensor.pooja_humidity") | int )/3 >= 70}}'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.dehumidifier


- alias: Dehumidifier - Stop Dehumidifier
  id: dehumidifier_stop_dehumidifier
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "16"
      minutes: 0
      seconds: 0
    - platform: state
      entity_id: sensor.upstairs_humidity, sensor.master_bedroom_humidity, sensor.pooja_humidity
  condition:
    - condition: state
      entity_id: switch.dehumidifier
      state: 'on'
    - condition: template
      value_template: '{{(states("sensor.upstairs_humidity") | int ) <= 65 or now().hour >= 16}}'
    - condition: template
      value_template: '{{(states("sensor.master_bedroom_humidity") | int ) <= 65 or now().hour >= 16}}'
    - condition: template
      value_template: '{{(states("sensor.pooja_humidity") | int ) <= 65 or now().hour >= 16}}'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.dehumidifier