- alias: Doorbell - Doorbell Notification
  id: doorbell_doorbell_notification
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.doorbell_doorbell_pressed
      to: 'on'
  action:
  - service: scene.create
    data_template:
      scene_id: pre_doorbell_state
      snapshot_entities:
        - light.living_room_main
        - media_player.google_home_minis
        - media_player.panasonic_viera_tv
        - media_player.onkyo_tx_nr656
        - media_player.onkyo_tx_nr656_2
        - media_player.house
        - media_player.living_room
        - media_player.conservatory
        - media_player.kitchen
        - media_player.master_bedroom_nest_hub
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home_minis
      volume_level: 1
  - service: camera.snapshot
    data:
      entity_id: camera.doorbell_last_event
      filename: '/config/www/CCTV_Snapshots/Doorbell.jpg'
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis, media_player.master_bedroom_display
      media_content_id: 'http://192.168.0.24:8123/local/sounds/Doorbell_Tubular_2.mp3'
      media_content_type: 'audio/mp3'
  - service: media_player.play_media
    data:
      entity_id: media_player.master_bedroom_nest_hub
      media_content_id: 'http://192.168.0.24:8123/local/CCTV_Snapshots/Doorbell.jpg'
      media_content_type: 'image/jpg'
  - service: shell_command.viera_on
  - wait_template: '{{ states("media_player.panasonic_viera_tv")== "on" }}'
    timeout: '00:00:05'
  - service: media_player.play_media
    data:
      entity_id: media_player.panasonic_viera_tv
      media_content_id: 'http://192.168.0.24:8123/local/CCTV_Snapshots/Doorbell.jpg'
      media_content_type: url
  - service: media_player.volume_mute
    data_template:
      entity_id: media_player.conservatory, media_player.house, media_player.living_room, media_player.kitchen, media_player.onkyo_tx_nr656, media_player.onkyo_tx_nr656_2
      is_volume_muted: true
  - delay: 00:00:30
  - service: shell_command.viera_input_hdmi2
  - service: scene.turn_on
    data:
      entity_id: scene.pre_doorbell_state