- alias: Doorbell Notification
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.doorbell_ring
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.doorbell_motion
      state: 'on'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home_minis
      volume_level: 1
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis
      media_content_id: '/config/www/audio/Doorbell_Tubular_2.mp3'
      media_content_type: 'audio/mp3'
  - service: camera.snapshot
    data:
      entity_id: camera.doorbell
      filename: '/config/www/CCTV_Snapshots/Doorbell.jpg'
  - delay: 00:00:10
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home_minis
      volume_level: '{% if as_timestamp(now()) | timestamp_custom("%-H") | float >= 7 and as_timestamp(now()) | timestamp_custom("%-H") | float < 20 %} 0.75 {% else %} 0.5 {% endif %}' 