- alias: Doorbell - Doorbell Notification
  id: doorbell_doorbell_notification
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.doorbell_ring
      to: 'on'
  action:
  - service: scene.create
    data_template:
      scene_id: pre_doorbell_state
      snapshot_entities:
        - light.living_room_main
        - media_player.google_home_minis
        - media_player.panasonic_viera_tv
        - media_player.onkyo_tx_nr656
        - media_player.onkyo_tx_nr656_2
        - media_player.house
        - media_player.living_room
        - media_player.conservatory
        - media_player.kitchen
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home_minis
      volume_level: 1
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis, media_player.master_bedroom_display
      media_content_id: 'http://192.168.0.24:8123/local/sounds/Doorbell_Tubular_2.mp3'
      media_content_type: 'audio/mp3'
  - service: camera.snapshot
    data:
      entity_id: camera.doorbell
      filename: '/config/www/CCTV_Snapshots/Doorbell.jpg'
  - condition: template
    value_template: '{{ states("binary_sensor.pir_living_room_front")== "on" or states("binary_sensor.pir_living_room_back")== "on" or states("media_player.panasonic_viera_tv")== "on" }}'
  - service: shell_command.viera_on
  - wait_template: '{{ states("media_player.panasonic_viera_tv")== "on" }}'
    timeout: '00:00:05'
  - service: media_player.play_media
    data:
      entity_id: media_player.panasonic_viera_tv
      media_content_id: 'http://192.168.0.23:8088/'
      media_content_type: url
  - service: media_player.volume_mute
    data_template:
      entity_id: media_player.conservatory, media_player.house, media_player.living_room, media_player.kitchen, media_player.onkyo_tx_nr656, media_player.onkyo_tx_nr656_2
      is_volume_muted: true
  - delay: 00:00:30
  - service: shell_command.viera_input_hdmi2
  - service: scene.turn_on
    data:
      entity_id: scene.pre_doorbell_state


- alias: Doorbell - Reboot When Video Feed Lost
  id: doorbell_reboot_when_video_feed_lost
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - alert.cctv_doorbell_video_feed_lost
      to: 'on'
    - platform: time_pattern
      hours: "4"
      minutes: 0
      seconds: 0
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.doorbell_reboot_when_video_feed_lost", "last_triggered") | default(0)) | int > 300)}}'
  action:
    - service: shell_command.reboot_doorbell


- alias: Doorbell - Set Daylight Colour
  id: doorbell_set_daylight_colour
  initial_state: false
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
      for:
        minutes: 1
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
      for:
        minutes: 15
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
      for:
        minutes: 30
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
      for:
        minutes: 45
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
      for:
        minutes: 60
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.doorbell_reboot_when_video_feed_lost", "last_triggered") | default(0)) | int > 300)}}'
  action:
    - service: shell_command.set_doorbell_daylight