- alias: Openings - Door or Window Opens Closes
  id: openings_door_or_window_opens_closes
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.conservatory_skylight_left
        - binary_sensor.conservatory_single_door
        - binary_sensor.conservatory_double_door
        - binary_sensor.living_room_right_big_window
        - binary_sensor.living_room_right_small_window
        - binary_sensor.master_bedroom_right_big_window
        - binary_sensor.master_bedroom_left_big_window
        - binary_sensor.master_bedroom_right_small_window
        - binary_sensor.master_bedroom_left_small_window
        - binary_sensor.cloakroom_window
        - binary_sensor.bathroom_window
        - binary_sensor.kiaan_big_window
        - binary_sensor.kiaan_small_window
        - binary_sensor.blue_room_big_window
        - binary_sensor.blue_room_small_window
        - binary_sensor.kitchen_window
        - binary_sensor.main_door
        - binary_sensor.pooja_room_big_window
        - binary_sensor.pooja_room_small_window
        - binary_sensor.conservatory_skylight_right
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: disarmed
    - condition: template
      value_template: '{{ trigger.to_state.state in ["on", "off"] }}'
    - condition: template
      value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis
      media_content_id: >
        {% if trigger.to_state.state == "on" %}
          http://192.168.9.23:8123/local/sounds/RemoteOn.mp3
        {% elif trigger.to_state.state == "off" %}
          http://192.168.9.23:8123/local/sounds/RemoteOff.mp3
        {% endif %}
      media_content_type: 'audio/mp3'


- alias: Openings - Downstairs Window Left Open At Night
  id: openings_downstairs_window_left_open_at_night
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'off'
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: group.downstairs_door_and_window_sensors
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.pirs
      state: 'off'
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
  action:
    - service: notify.gmaillolo
      data:
        title: "HA - Doors/Windows Left Open"
        message: >
          The following doors/windows are not closed: 
          {% set doors = [
          states.binary_sensor.conservatory_skylight_left,
          states.binary_sensor.conservatory_skylight_right,
          states.binary_sensor.conservatory_single_door,
          states.binary_sensor.conservatory_double_door,
          states.binary_sensor.living_room_right_big_window,
          states.binary_sensor.living_room_right_small_window,
          states.binary_sensor.cloakroom_window,
          states.binary_sensor.kitchen_window] -%}
          {%- set doors_on = doors | selectattr('state','eq','on') | list -%}
          {% for door_names in doors_on -%}
          {{(door_names | string).split("friendly_name=")[1].split(" @")[0]}}, 
          {%- endfor %}
    - service: media_player.volume_up
      data:
        entity_id: media_player.bedroom_nest_hub
    - service: tts.google_say
      entity_id: media_player.bedroom_nest_hub
      data:
        message: >
          The following doors/windows are not closed: 
          {% set doors = [
          states.binary_sensor.conservatory_skylight_left,
          states.binary_sensor.conservatory_skylight_right,
          states.binary_sensor.conservatory_single_door,
          states.binary_sensor.conservatory_double_door,
          states.binary_sensor.living_room_right_big_window,
          states.binary_sensor.living_room_right_small_window,
          states.binary_sensor.cloakroom_window,
          states.binary_sensor.kitchen_window] -%}
          {%- set doors_on = doors | selectattr('state','eq','on') | list -%}
          {% for door_names in doors_on -%}
          {{(door_names | string).split("friendly_name=")[1].split(" @")[0]}}, 
          {%- endfor %}



- alias: Openings - Conservatory Door Left Unlocked At Night
  id: openings_conservatory_door_left_unlocked_at_night
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'off'
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: binary_sensor.conservatory_door_lock
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.pirs
      state: 'off'
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
  action:
    - service: notify.gmaillolo
      data:
        title: "HA - Conservatory Door Left Unlocked At Night"
        message: "The Conservatory Door Has Been Left Unlocked"
    - service: automation.turn_off
      data:
        entity_id: automation.nest_hub_start_cast
    - service: media_player.volume_up
      data:
        entity_id: media_player.bedroom_nest_hub
    - service: tts.google_say
      entity_id: media_player.bedroom_nest_hub
      data:
        message: "Please Note: The Conservatory Door Has Been Left Unlocked"
    - wait_template: '{{ states("media_player.bedroom_nest_hub") != "playing"}}'
      timeout: '00:00:15'
    - service: automation.turn_off
      data:
        entity_id: automation.nest_hub_start_cast
    - service: script.turn_on
      data:
        entity_id: script.nest_hub_start_cast
    - wait_template: '{{ state_attr("media_player.bedroom_nest_hub", "app_name") == "DashCast"}}'
      timeout: '00:00:15'
    - service: automation.turn_on
      data:
        entity_id: automation.nest_hub_start_cast



- alias: Openings -  Hallway Light On When Opening Main Door
  id: openings_hallway_light_on_when_opening_main_door
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.main_door
      to: 'on'
  condition:
    - condition: state
      entity_id: group.pirs
      state: 'off'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("sensor.aloe_vera_light_intensity") != "unknown" and  states("sensor.aloe_vera_light_intensity") | int < 250 }}'
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
  - service: light.turn_on
    data:
      entity_id: light.hallway
      brightness: 255


- alias: Openings - Hallway Light Off 2 min after Opening Main Door
  id: openings_hallway_light_off_2_min_after_opening_main_door
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.hallway
      to: 'on'
      for:
        minutes: 2
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.holidays
        state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.hallway




