- alias: Fire Stick 4K - Turn Movies on when Netflix or Prime is Playing
  id: fire_stick_4k_max_turn_movies_on_when_netflix_or_prime_is_playing
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.fire_stick_4k_max
      to: 'playing'
      for:
        seconds: 5
    - platform: state
      entity_id: media_player.fire_stick_4k_max
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: template
      value_template: >-
        {{
        state_attr("media_player.fire_stick_4k_max","source") == "Netflix"
        or state_attr("media_player.fire_stick_4k_max","source") ==  "Disney+"
        or state_attr("media_player.fire_stick_4k_max","source") == "Prime Video (Fire TV)"
        }}
    - condition: state
      entity_id: binary_sensor.dark
      state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.movies

- alias: Fire Stick 4K - Dim Lights On when Paused
  id: fire_stick_4k_max_dim_lights_on_when_paused
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.fire_stick_4k_max
      to: 'paused'
  condition:
    - condition: state
      entity_id: input_boolean.movies
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 11

- alias: Fire Stick 4K - Turn Lights Off when Unpaused
  id: fire_stick_4k_max_turn_lights_off_when_unpaused
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.fire_stick_4k_max
      to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.movies
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.living_room_main