- alias: Play Good Morning
  id: play_good_morning
  initial_state: false
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_kitchen
      to: 'on'
  condition:
    - condition: time
      after: '05:30'
      before: '12:00'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: template
      # Only run if more than 6 hours (21,600 sec) since it last ran 
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.play_good_morning", "last_triggered")) | int > 21600 )}}'
  action:
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: tts.google_say
      data_template:
        entity_id: media_player.google_home_minis
        message: |
          Good morning. Today is 
          {{as_timestamp(now()) | timestamp_custom('%A')}}, {% set day = (as_timestamp(now()) | timestamp_custom('%d')) |int-%}
          {{day}}{%- if day >= 4 and day <= 20 or day >= 24 and day <= 30 -%}th
          {%- elif day == 1 or day == 21 or day == 31-%}st
          {%- elif day == 2 or day == 22 -%}nd
          {%- elif day == 3 or day == 23 -%}rd
          {%- endif %} {{as_timestamp(now()) | timestamp_custom('%B')}}
          It's currently {{states('sensor.dark_sky_summary')}} and {{state_attr('weather.dark_sky','temperature')|round}} degrees.
          Today will be {{states('sensor.dark_sky_hourly_summary')|replace(".", "")}},
          highs: {{state_attr('weather.dark_sky', 'forecast')[0].temperature|round}},
          lows: {{state_attr('weather.dark_sky', 'forecast')[0].templow|round}}.
          Winds:
          {% set winbearing = (state_attr('weather.dark_sky','forecast')[0].wind_bearing/45)|round +1 %}
          {% set winddir = ['North', 'North East','East','South East','South','South West','West','North West']%}
          {{ winddir[winbearing]}}
          at {{(states('sensor.dark_sky_wind_speed_0')|int*3.6)|round}} to {{(states('sensor.dark_sky_wind_gust_0')|int*3.6)|round}} km/h.
          Precipitation: {{state_attr('weather.dark_sky', 'forecast')[0].precipitation|round}} millimeters.
          {% if now().strftime("%a") == 'Tue' or now().strftime("%a") == 'Wed' or now().strftime("%a") == 'Thu' %}Estimated travel time to Waybridge: {{states('sensor.home_to_work')}} minutes.{% endif %}
          {% if (as_timestamp(now()) - as_timestamp(state_attr("automation.start_vacuuming", "last_triggered")) | int <= 36000) %} Remember to empty the vacuum.{% endif %}
          {% if as_timestamp(now()) | timestamp_custom('%Y-%m-%d') == (state_attr("calendar.birthdays_events", "start_time")).split(" ")[0] and state_attr("calendar.birthdays__events", "all_day") != True %} Your next appointment is: {{state_attr("calendar.birthdays_events", "message")}} at {{(state_attr("calendar.birthdays_events", "start_time")).split(" ")[1].split(":")[0]}} {%if (state_attr("calendar.birthdays_events", "start_time")).split(" ")[1].split(":")[1] != '00'%}{{(state_attr("calendar.birthdays_events", "start_time")).split(" ")[1].split(":")[1]}} {%endif%} {%endif%}
          {% if as_timestamp(now()) | timestamp_custom('%Y-%m-%d') == (state_attr("calendar.birthdays_events", "start_time")).split(" ")[0] and state_attr("calendar.birthdays_events", "all_day") == True %} Today is : {{state_attr("calendar.birthdays__events", "message")|replace("/","and")}}{%endif%}
