- alias: GA - Set GA Volume To Low At Night
  id: ga_set_ga_volume_to_low_at_night
  initial_state: true
  trigger:
    platform: time_pattern
    hours: "20"
    minutes: 30
    seconds: 0
  action:
  # - service: media_player.volume_set
    # data:
      # entity_id: media_player.master_bedroom_display
      # volume_level: 0.50
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_room_google_mini
      volume_level: 0.50
  - service: media_player.volume_set
    data:
      entity_id: media_player.kitchen_google_mini
      volume_level: 0.50
  - service: media_player.volume_set
    data:
      entity_id: media_player.google_home_minis
      volume_level: 0.50


- alias: GA - Set GA Volume To High Daytime
  id: ga_set_ga_volume_to_high_daytime
  initial_state: true
  trigger:
    platform: time_pattern
    hours: "7"
    minutes: 30
    seconds: 0
  action:
  # - service: media_player.volume_set
    # data:
      # entity_id: media_player.master_bedroom_display
      # volume_level: 0.75
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_room_google_mini
      volume_level: 0.75
  - service: media_player.volume_set
    data:
      entity_id: media_player.kitchen_google_mini
      volume_level: 0.75
  - service: media_player.volume_set
    data:
      entity_id: media_player.google_home_minis
      volume_level: 0.75


- alias: GA - Play RTL2 Radio
  id: ga_play_rtl2_radio
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.rtl2_radio
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_station
        option: RTL2
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_speakers
        option: House
    - service: script.turn_on
      entity_id: script.play_chromecast_radio
    - service: input_boolean.turn_off
      entity_id: input_boolean.rtl2_radio


- alias: GA - Play Scala Radio
  id: ga_play_scala_radio
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.scala_radio
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_station
        option: Scala
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_speakers
        option: Office Nest Hub
    - service: script.turn_on
      entity_id: script.play_chromecast_radio
    - service: input_boolean.turn_off
      entity_id: input_boolean.scala_radio



- alias: GA - Play Chill Radio
  id: ga_play_chill_radio
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.chill_radio
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_station
        option: Chill
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_speakers
        option: House
    - service: script.turn_on
      entity_id: script.play_chromecast_radio
    - service: input_boolean.turn_off
      entity_id: input_boolean.chill_radio


- alias: GA - Play Absolute Radio
  id: ga_play_absolute_radio
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.absolute_radio_radio
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_station
        option: Absolute Radio
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_speakers
        option: House
    - service: script.turn_on
      entity_id: script.play_chromecast_radio
    - service: input_boolean.turn_off
      entity_id: input_boolean.absolute_radio_radio


- alias: GA - Play Absolute CR Radio
  id: ga_play_absolute_cr_radio
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.absolute_radio_cr_radio
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_station
        option: Absolute Radio Classic Rock
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_speakers
        option: House
    - service: script.turn_on
      entity_id: script.play_chromecast_radio
    - service: input_boolean.turn_off
      entity_id: input_boolean.absolute_radio_cr_radio


- alias: GA - Play Radio Fiji Two Radio
  id: ga_play_radio_fiji_two_radio
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.radio_fiji_two_radio
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_station
        option: Radio Fiji Two
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_speakers
        option: House
    - service: script.turn_on
      entity_id: script.play_chromecast_radio
    - service: input_boolean.turn_off
      entity_id: input_boolean.radio_fiji_two_radio


- alias: GA - Play Radio Navtarang
  id: ga_play_radio_navtarang
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.radio_navtarang
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_station
        option: Navtarang
    - service: input_select.select_option
      data:
        entity_id: input_select.chromecast_radio_speakers
        option: House
    - service: script.turn_on
      entity_id: script.play_chromecast_radio
    - service: input_boolean.turn_off
      entity_id: input_boolean.radio_navtarang


- alias: GA - Keep Google Home Alive
  id: ga_keep_google_home_alive
  initial_state: true
  trigger:
    platform: time_pattern
    minutes: '/2'
    seconds: 00
  condition:
    - condition: template
      value_template: '{{ states("media_player.kitchen_google_mini") != "playing"}}'
    - condition: template
      value_template: '{{ states("media_player.living_room_google_mini") != "playing"}}'
    - condition: template
      value_template: '{{ states("media_player.google_home_minis") != "playing"}}'
  action:
    - service: media_player.play_media
      entity_id: media_player.google_home_minis
      data:
        media_content_id: http://192.168.9.23:8123/local/sounds/1sec.mp3
        media_content_type: music
    - delay:
        seconds: 0.1
    - service: media_player.play_media
      entity_id: media_player.google_home_minis
      data:
        media_content_id: http://192.168.9.23:8123/local/sounds/1sec.mp3
        media_content_type: music


- alias: GA - Turn Multimedia Switch on if Sky, TV or Onkyo is on
  id: ga_turn_multimedia_switch_on_if_sky_tv_or_onkyo_is_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.panasonic_viera_tv
      to: 'on'
    - platform: state
      entity_id: media_player.onkyo_tx_nr656
      to: 'on'
    - platform: state
      entity_id: switch.skyhd
      to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.multimedia


- alias: GA - Turn Multimedia off if multimedia switch goes off
  id: ga_turn_multimedia_off_if_multimedia_switch_goes_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.multimedia
      to: 'off'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.living_room_google_mini
        state: 'on'
      - condition: state
        entity_id: media_player.onkyo_tx_nr656
        state: 'on'
      - condition: state
        entity_id: switch.skyhd
        state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.multimedia_off


- alias: GA - Turn Multimedia off if all multimedia is off
  id: ga_turn_multimedia_off_if_all_multimedia_is_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.panasonic_viera_tv
      to: 'off'
    - platform: state
      entity_id: media_player.onkyo_tx_nr656
      to: 'off'
    - platform: state
      entity_id: switch.skyhd
      to: 'off'
  condition:
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: media_player.onkyo_tx_nr656
      state: 'off'
    - condition: state
      entity_id: switch.skyhd
      state: 'off'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.multimedia


- alias: GA - Set TV Audio To Home Cinema
  id: ga_set_tv_audio_to_home_cinema
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.set_tv_audio_to_home_cinema
      to: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.set_tv_audio_to_home_cinema
    - service: input_boolean.turn_off
      entity_id: input_boolean.set_tv_audio_to_home_cinema
