- alias: Holiday - Start
  id: holiday_start
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.laurent
      from: "home"
    - platform: state
      entity_id: person.div
      from: "home"
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) -(state_attr("input_datetime.holiday_start", "timestamp")) | int > 0)}}'
    - condition: template
      value_template: '{{ ((state_attr("input_datetime.holiday_end", "timestamp")) | int) - as_timestamp(now()) > 0 }}'
    - condition: template
      value_template: '{{ states("person.laurent") != "home"}}'
    - condition: template
      value_template: '{{ states("person.div") != "home"}}'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.holidays
    - service: switch.turn_off
      data:
        entity_id: switch.watchtower, switch.watchtower_n54l

- alias: Holiday - End
  id: holiday_end
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'on'
    - platform: state
      entity_id: person.laurent
    - platform: state
      entity_id: person.div
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) -(state_attr("input_datetime.holiday_end", "timestamp")) | int > 0)}}'
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ distance(states.person.laurent) | int(4)  < 3}}'
      - condition: template
        value_template: '{{ distance(states.person.div) | int(4)  < 3}}'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.normal
    - service: switch.turn_on
      data:
        entity_id: switch.watchtower, switch.watchtower_n54l




- alias: Holiday - Living Room On
  id: holiday_living_room_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  condition:
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
  action:
  - delay: "{{range(0,300+1)|random|timestamp_custom('%X',false)}}"
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 255
  - service: light.turn_on
    data:
      entity_id: light.kitchen_window
      brightness: 255



- alias: Holiday - Upstairs on
  id: holiday_upstairs_on
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "22"
      minutes: 30
      seconds: 0
  condition:
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
  action:
  - delay: "{{range(0,1200+1)|random|timestamp_custom('%X',false)}}"
  - service: light.turn_on
    data:
      entity_id: light.lolo_bedside_light
      brightness: 255
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 255
      effect: "solid"
      rgb_color: [255,255,255]
  - delay: "{{range(0,300+1)|random|timestamp_custom('%X',false)}}"
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - delay: "{{range(0,300+1)|random|timestamp_custom('%X',false)}}"
  - service: light.turn_off
    data:
      entity_id: light.kitchen_window


- alias: Holiday - Upstairs off
  id: holiday_upstairs_off
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "23"
      minutes: 0
      seconds: 0
  condition:
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
  action:
  - delay: "{{range(0,1200+1)|random|timestamp_custom('%X',false)}}"
  - service: light.turn_off
    data:
      entity_id: light.lolo_bedside_light
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - service: light.turn_off
    data:
      entity_id: light.kitchen_window
  - service: light.turn_off
    data:
      entity_id: light.kiaan_lamp



