- alias: Notify iOS app
  initial_state: true
  trigger:
    - platform: state
      entity_id: 
        - alert.aloe_vera_battery_too_low
        - alert.aloe_vera_humidity_too_low
        - alert.cctv_dafang_kitchen_lost
        - alert.cctv_dafang_living_room_lost
        - alert.cctv_front_lost
        - alert.cctv_garage_lost
        - alert.currentcost_lost
        - alert.dehumidifier_full
        - alert.fire7_lost
        - alert.home_disk_usage_too_high
        - alert.house_number_led_strip_lost
        - alert.outside_temp_sensor_lost
        - alert.ram_too_high
        - alert.ram_usage_lost
        - alert.root_disk_usage_too_high
        - alert.rpi_lost
        - alert.rpi_zero_w_lost
        - alert.staircase_led_strip_lost
        - alert.tv_cabinet_led_strip_lost
        - alert.upstairs_temp_sensor_lost
      from: 'idle'
      to: 'on'
  action:
    - service: counter.increment
      entity_id: counter.iosbadgecount
    - service: notify.ios_lolos_iphone
      data_template:
        message: '{{ trigger.entity_id | replace("alert.","") | replace("_"," ") |capitalize }}'
        data:
          push:
            badge: '{{states("counter.iosbadgecount")}}'
            category: "alert"
          action_data:
            entity_id: '{{trigger.entity_id}}'

- alias: Turn Alert Off
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISABLE_ALERT
  action:
    - service: alert.turn_off
      data_template:
        entity_id: '{{ trigger.event.data["action_data"]["entity_id"] }}'

- alias: Decrease Counter with Alert to Idle
  initial_state: true
  trigger:
    - platform: state
      entity_id: 
        - alert.aloe_vera_battery_too_low
        - alert.aloe_vera_humidity_too_low
        - alert.cctv_dafang_kitchen_lost
        - alert.cctv_dafang_living_room_lost
        - alert.cctv_front_lost
        - alert.cctv_garage_lost
        - alert.currentcost_lost
        - alert.dehumidifier_full
        - alert.fire7_lost
        - alert.home_disk_usage_too_high
        - alert.house_number_led_strip_lost
        - alert.outside_temp_sensor_lost
        - alert.ram_too_high
        - alert.ram_usage_lost
        - alert.root_disk_usage_too_high
        - alert.rpi_lost
        - alert.rpi_zero_w_lost
        - alert.staircase_led_strip_lost
        - alert.tv_cabinet_led_strip_lost
        - alert.upstairs_temp_sensor_lost
      to: 'idle'
  action:
    - service: counter.decrement
      entity_id: counter.iosbadgecount
    - condition: state
      entity_id: counter.iosbadgecount
      state: '0'
    - service: notify.ios_lolos_iphone
      data:
        message: clear_badge