- alias: iOS - Notify iOS app
  id: ios_notify_ios_app
  initial_state: true
  trigger:
    - platform: state
      entity_id: 
        - alert.cctv_dafang_kitchen_lost
        - alert.cctv_dafang_living_room_lost
        - alert.cctv_front_lost
        - alert.cctv_garage_lost
        - alert.currentcost_lost
        - alert.dehumidifier_full
        - alert.fire7_lost
        - alert.garage_freezer_temp_too_high
        - alert.home_disk_usage_too_high
        - alert.house_number_led_strip_lost
        - alert.kello_lost
        - alert.kitchen_freezer_temp_too_high
        - alert.outside_temp_sensor_lost
        - alert.ram_too_high
        - alert.ram_usage_lost
        - alert.root_disk_usage_too_high
        - alert.rpi_kitchen_lost
        - alert.rpi_lost
        - alert.staircase_led_strip_lost
        - alert.tv_cabinet_led_strip_lost
      from: 'idle'
      to: 'on'
  action:
    - service: counter.increment
      entity_id: counter.iosbadgecount
    - service: notify.mobile_app_lolo_s_iphone
      data_template:
        message: '{{ trigger.entity_id | replace("alert.","") | replace("_"," ") |capitalize }}'
        data:
          push:
            badge: '{{states("counter.iosbadgecount")}}'
            category: "alert"
          action_data:
            entity_id: '{{trigger.entity_id}}'

- alias: iOS - Turn Alert Off
  id: ios_turn_alert_off
  initial_state: true
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISABLE_ALERT
  action:
    - service: alert.turn_off
      data_template:
        entity_id: '{{ trigger.event.data["action_data"]["entity_id"] }}'
    - service: counter.decrement
      entity_id: counter.iosbadgecount
    - condition: state
      entity_id: counter.iosbadgecount
      state: '0'
    - service: notify.mobile_app_lolo_s_iphone
      data:
        message: clear_badge

- alias: iOS - Decrease Counter with Alert to Idle
  id: ios_decrease_counter_with_alert_to_idle
  initial_state: true
  trigger:
    - platform: state
      entity_id: 
        - alert.cctv_dafang_kitchen_lost
        - alert.cctv_dafang_living_room_lost
        - alert.cctv_front_lost
        - alert.cctv_garage_lost
        - alert.currentcost_lost
        - alert.dehumidifier_full
        - alert.fire7_lost
        - alert.garage_freezer_temp_too_high
        - alert.home_disk_usage_too_high
        - alert.house_number_led_strip_lost
        - alert.kello_lost
        - alert.kitchen_freezer_temp_too_high
        - alert.outside_temp_sensor_lost
        - alert.ram_too_high
        - alert.ram_usage_lost
        - alert.root_disk_usage_too_high
        - alert.rpi_kitchen_lost
        - alert.rpi_lost
        - alert.staircase_led_strip_lost
        - alert.tv_cabinet_led_strip_lost
      to: 'idle'
  action:
    - service: counter.decrement
      entity_id: counter.iosbadgecount
    - condition: state
      entity_id: counter.iosbadgecount
      state: '0'
    - service: notify.mobile_app_lolo_s_iphone
      data:
        message: clear_badge