- alias: Kiaan Night Light - Sleep
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 19
      minutes: 00
      seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: "on"
    - condition: state
      entity_id: light.kiaan_lamp
      state: "off"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 0
      effect: "solid"
      rgb_color: [0,0,0]
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 128
      rgb_color: [0,0,255]
      transition: 1



- alias: Kiaan Night Light - Wake Phase1 weekdays
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 5
      minutes: 30
      seconds: 0
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.normal
      state: "on"
    - condition: state
      entity_id: light.kiaan_lamp
      state: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 128
      rgb_color: [0,255,0]
      transition: 1



- alias: Kiaan Night Light - Wake Phase1 weekend
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 6
      minutes: 30
      seconds: 0
  condition:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: state
      entity_id: input_boolean.normal
      state: "on"
    - condition: state
      entity_id: light.kiaan_lamp
      state: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 128
      rgb_color: [0,255,0]
      transition: 1



- alias: Kiaan Night Light - Wake Phase2 
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 7
      minutes: 00
      seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: "on"
    - condition: state
      entity_id: light.kiaan_lamp
      state: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 255
      rgb_color: [0,255,0]
      transition: 5



- alias: Kiaan Night Light - Off weedays
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 7
      minutes: 30
      seconds: 0
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.normal
      state: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 255
      rgb_color: [255,255,255]
  - service: light.turn_off
    data:
      entity_id: light.kiaan_lamp



- alias: Kiaan Night Light - Off weekend
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 8
      minutes: 0
      seconds: 0
  condition:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: state
      entity_id: input_boolean.normal
      state: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 255
      rgb_color: [255,255,255]
  - service: light.turn_off
    data:
      entity_id: light.kiaan_lamp



