- alias: Kiaan Night Light - Sleep
  id: kiaan_night_light_sleep
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "19"
      minutes: 00
      seconds: 0
  condition:
    - condition: template
      value_template: '{{ is_state("input_boolean.normal", "on") or is_state("input_boolean.movies", "on")}}'
    - condition: state
      entity_id: light.kiaan_lamp
      state: "off"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 0
      effect: "solid"
      rgb_color: [0,0,0]
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 128
      rgb_color: [0,0,255]
      transition: 1



- alias: Kiaan Night Light - Wake Phase1 weekdays
  id: kiaan_night_light_wake_phase1_weekdays
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "5"
      minutes: 30
      seconds: 0
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: template
      value_template: '{{ is_state("input_boolean.normal", "on") or is_state("input_boolean.movies", "on")}}'
    - condition: state
      entity_id: light.kiaan_lamp
      state: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 128
      rgb_color: [0,255,0]
      transition: 1



- alias: Kiaan Night Light - Wake Phase1 weekend
  id: kiaan_night_light_wake_phase1_weekend
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "6"
      minutes: 30
      seconds: 0
  condition:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: template
      value_template: '{{ is_state("input_boolean.normal", "on") or is_state("input_boolean.movies", "on")}}'
    - condition: state
      entity_id: light.kiaan_lamp
      state: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 128
      rgb_color: [0,255,0]
      transition: 1



- alias: Kiaan Night Light - Wake Phase2 
  id: kiaan_night_light_wake_phase2
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "7"
      minutes: 00
      seconds: 0
  condition:
    - condition: template
      value_template: '{{ is_state("input_boolean.normal", "on") or is_state("input_boolean.movies", "on")}}'
    - condition: state
      entity_id: light.kiaan_lamp
      state: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 255
      rgb_color: [0,255,0]
      transition: 5



- alias: Kiaan Night Light - Off weedays
  id: kiaan_night_light_off_weedays
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "7"
      minutes: 30
      seconds: 0
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: template
      value_template: '{{ is_state("input_boolean.normal", "on") or is_state("input_boolean.movies", "on")}}'
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 255
      rgb_color: [255,255,255]
  - service: light.turn_off
    data:
      entity_id: light.kiaan_lamp



- alias: Kiaan Night Light - Off weekend
  id: kiaan_night_light_off_weekend
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "8"
      minutes: 0
      seconds: 0
  condition:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: template
      value_template: '{{ is_state("input_boolean.normal", "on") or is_state("input_boolean.movies", "on")}}'
  action:
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 255
      rgb_color: [255,255,255]
  - service: light.turn_off
    data:
      entity_id: light.kiaan_lamp



- alias: Kiaan Lamp - Toggle
  id: kiaan_lamp_toggle
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.kiaan_lamp_sensor
      from: 'unknown'
  condition:
    - condition: template
      value_template: '{{ is_state("input_boolean.normal", "on") or is_state("input_boolean.movies", "on")}}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(this.last_triggered) | int > 5)}}'
  action:
    - wait_template: '{{ states("sensor.kiaan_lamp_sensor") == "unknown" }}'
      timeout: 
        milliseconds: 400
      continue_on_timeout: false
    - service: light.turn_on
      data:
        entity_id: light.kiaan_lamp
        brightness: >
          {% set light_status = states('light.kiaan_lamp') %}
          {% if light_status == "on" %}
            0
          {% else %}
            255
          {% endif %}



- alias: Kiaan Lamp - Set Brightness
  id: kiaan_lamp_set_brightness
  initial_state: true
  mode: single
  trigger:
    - platform: state
      entity_id: sensor.kiaan_lamp_sensor
  condition:
    - condition: template
      value_template: '{{ is_state("input_boolean.normal", "on") or is_state("input_boolean.movies", "on")}}'
    - condition: template
      value_template: '{{ trigger.from_state.state != "unknown" }}'
    - condition: template
      value_template: '{{ trigger.to_state.state != "unknown" }}'
    - condition: template
      value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.kiaan_lamp_toggle", "last_triggered")) | int > 1)}}'
  action:
    - delay:
        milliseconds: 500
    - service: light.turn_on
      data:
        entity_id: light.kiaan_lamp
        brightness: '{{(states("sensor.kiaan_lamp_sensor") | int * 2.55) | round}}'

