- alias: LED Strip - TV Cabinet LED Strip On PIR
  id: led_strip_tv_cabinet_led_strip_on_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.tv_cabinet_led_strip
      brightness: 255
      rgb_color: [0,255,0]
  - service: switch.turn_on
    data:
      entity_id: switch.lwrf_socket_3
  - service: light.turn_on
    data:
      entity_id: light.tv_cabinet_led_strip
      brightness: 255
      rgb_color: [0,255,0]
  - service: switch.turn_on
    data:
      entity_id: switch.lwrf_socket_3





- alias: LED Strip - Flash Alert
  id: led_strip_flash_alert
  initial_state: true
  trigger:
    - platform: state
      entity_id: alert.cctv_front_lost
      to: 'on'
    - platform: state
      entity_id: alert.cctv_garage_lost
      to: 'on'
    - platform: state
      entity_id: alert.currentcost_lost
      to: 'on'
    - platform: state
      entity_id: alert.dehumidifier_full
      to: 'on'
    - platform: state
      entity_id: alert.home_disk_usage_too_high
      to: 'on'
    - platform: state
      entity_id: alert.outside_temp_sensor_lost
      to: 'on'
    - platform: state
      entity_id: alert.ram_too_high
      to: 'on'
    - platform: state
      entity_id: alert.root_disk_usage_too_high
      to: 'on'
    - platform: state
      entity_id: alert.rpi_lost
      to: 'on'
    - platform: state
      entity_id: alert.rpi_kitchen_lost
      to: 'on'
    - platform: state
      entity_id: alert.staircase_led_strip_lost
      to: 'on'
    - platform: state
      entity_id: alert.tv_cabinet_led_strip_lost
      to: 'on'
    - platform: state
      entity_id: alert.upstairs_temp_sensor_lost
      to: 'on'
    - platform: state
      entity_id: binary_sensor.mailbox
      to: 'on'
    - platform: event
      event_type: signal_received
      event_data:
        entity_id: sensor.doorbell_sound
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pir_living_room_front
        state: 'on'
      - condition: state
        entity_id: binary_sensor.pir_living_room_back
        state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.tv_cabinet_led_strip
      brightness: 255
      rgb_color: [255,0,0]
      effect: flash




- alias: LED Strip - TV Cabinet LED Strip Off by PIR
  id: led_strip_tv_cabinet_led_strip_off_by_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'off'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_living_room_front
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_living_room_back
      state: 'off'
    - condition: state
      entity_id: light.tv_cabinet_led_strip
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.tv_cabinet_led_strip
  - service: switch.turn_off
    data:
      entity_id: switch.lwrf_socket_3
  - delay: 00:00:01
  - service: switch.turn_off
    data:
      entity_id: switch.lwrf_socket_3




- alias: LED Strip - Staircase LED Strip On by PIR
  id: led_strip_staircase_led_strip_on_by_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'on'
    - platform: state
      entity_id: binary_sensor.dark
      to: 'on'
  condition:
    - condition: state
      entity_id: light.staircase_led_strip
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_staircase
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: state
      entity_id: binary_sensor.dark
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.staircase_led_strip
      brightness: 255
      rgb_color: [0,128,255]
      transition: 1


- alias: LED Strip - Staircase LED Strip Off by PIR
  id: led_strip_staircase_led_strip_off_by_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: state
      entity_id: light.staircase_led_strip
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.staircase_led_strip






- alias: LED Strip - House Number On
  id: led_strip_house_number_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: light.house_number
      from: 'unavailable'
    - platform: state
      entity_id: light.porch_om_xmas_led_strip
      from: 'unavailable'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '15:00'
  action:
  - service: light.turn_on
    data:
      entity_id: light.house_number
      brightness: 255
      effect: None
      rgb_color: [0,0,255]
  # - service: light.turn_on
  #   data:
  #     entity_id: light.wled_garage
  #     brightness: 10
  #     effect: None
  #     rgb_color: [0,0,255]
  - condition: state
    entity_id: input_boolean.xmas
    state: 'on'
  - service: light.turn_on
    data:
      entity_id: light.porch_om_xmas_led_strip
      brightness: 50
      effect: rainbow

- alias: LED Strip - House Number Off
  id: led_strip_house_number_off
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "0"
      minutes: 0
      seconds: 0
    - platform: state
      entity_id: light.house_number
      from: 'unavailable'
    - platform: state
      entity_id: light.porch_om_xmas_led_strip
      from: 'unavailable'
  condition:
    - condition: time
      before: '02:00'
  action:
  - service: light.turn_off
    data:
      entity_id: light.house_number
  - service: light.turn_off
    data:
      entity_id: light.wled_garage
  - service: light.turn_off
    data:
      entity_id: light.porch_om_xmas_led_strip

- alias: LED Strip - Turn Pooja Frame Off after 3h
  id: led_strip_turn_pooja_frame_off_after_3h
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.pooja_frame
      to: 'on'
      for:
        hours: 3
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: light.pooja_frame
