- alias: TV Cabinet LED Strip On PIR
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.TV_Cabinet_LED_Strip
      brightness: 255
      rgb_color: [0,255,0]
  - service: light.turn_on
    data:
      entity_id: light.TV_Cabinet_LED_Strip
      brightness: 255
      rgb_color: [0,255,0]





- alias: Flash Alert
  initial_state: true
  trigger:
    - platform: state
      entity_id: alert.cctv_front_lost
      to: 'on'
    - platform: state
      entity_id: alert.cctv_garage_lost
      to: 'on'
    - platform: state
      entity_id: alert.currentcost_lost
      to: 'on'
    - platform: state
      entity_id: alert.dehumidifier_full
      to: 'on'
    - platform: state
      entity_id: alert.home_disk_usage_too_high
      to: 'on'
    - platform: state
      entity_id: alert.kello_lost
      to: 'on'
    - platform: state
      entity_id: alert.outside_temp_sensor_lost
      to: 'on'
    - platform: state
      entity_id: alert.ram_too_high
      to: 'on'
    - platform: state
      entity_id: alert.root_disk_usage_too_high
      to: 'on'
    - platform: state
      entity_id: alert.rpi_lost
      to: 'on'
    - platform: state
      entity_id: alert.rpi_kitchen_lost
      to: 'on'
    - platform: state
      entity_id: alert.staircase_led_strip_lost
      to: 'on'
    - platform: state
      entity_id: alert.tv_cabinet_led_strip_lost
      to: 'on'
    - platform: state
      entity_id: alert.upstairs_temp_sensor_lost
      to: 'on'
    - platform: state
      entity_id: binary_sensor.mailbox
      to: 'on'
    - platform: event
      event_type: signal_received
      event_data:
        entity_id: sensor.doorbell_sound
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pir_living_room_front
        state: 'on'
      - condition: state
        entity_id: binary_sensor.pir_living_room_back
        state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.TV_Cabinet_LED_Strip
      brightness: 255
      rgb_color: [255,0,0]
      effect: flash




- alias: TV Cabinet LED Strip Off by PIR
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'off'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_living_room_front
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_living_room_back
      state: 'off'
    - condition: state
      entity_id: light.TV_Cabinet_LED_Strip
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.TV_Cabinet_LED_Strip




- alias: Staircase LED Strip On by PIR
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
    - platform: state
      entity_id: sensor.aloe_vera_light_intensity
  condition:
    - condition: state
      entity_id: light.Staircase_LED_Strip
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_staircase
      state: 'on'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("sensor.aloe_vera_light_intensity") != "unknown" and  states("sensor.aloe_vera_light_intensity") | int < 300 }}'
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.Staircase_LED_Strip
      brightness: 255
      rgb_color: [0,128,255]
      transition: 1


- alias: Staircase LED Strip Off by PIR
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: state
      entity_id: light.Staircase_LED_Strip
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.Staircase_LED_Strip






- alias: House Number On
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  action:
  - service: light.turn_on
    data:
      entity_id: light.porch_om_xmas_led_strip
      brightness: 255
      # effect: rainbow
      rgb_color: [0,0,255]

- alias: House Number Off
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 0
      minutes: 0
      seconds: 0
  action:
  - service: light.turn_off
    data:
      entity_id: light.porch_om_xmas_led_strip
