- alias: LWRF Remote 1 On
  id: lwrf_remote_1_on
  initial_state: true
  # Kitchen lights on
  trigger:
    - platform: event
      event_type: rfxtrx_event
      event_data:
        packet_type: 20
        sub_type: 0
        id_string: "f4ff62:1"
        values:
          Command: 'On'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_1_on", "last_triggered") ) | int > 5 )}}'
    - condition: state
      entity_id: switch.lwrf_remote_1
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: group.kitchen_lights
      brightness: 255
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_minis
      media_content_id: 'http://192.168.0.24:8123/local/sounds/RemoteOn.mp3'
      media_content_type: 'audio/mp3'


- alias: LWRF Remote 1 Off
  id: lwrf_remote_1_off
  initial_state: true
  # Kitchen lights on
  trigger:
    - platform: event
      event_type: rfxtrx_event
      event_data:
        packet_type: 20
        sub_type: 0
        id_string: "f4ff62:1"
        values:
          Command: 'Off'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_1_off", "last_triggered") ) | int > 1 )}}'
    - condition: state
      entity_id: switch.lwrf_remote_1
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: group.kitchen_lights
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_minis
      media_content_id: 'http://192.168.0.24:8123/local/sounds/RemoteOff.mp3'
      media_content_type: 'audio/mp3'



- alias: LWRF Remote 2 On
  id: lwrf_remote_2_on
  initial_state: true
  # Go through CCTV feeds on TV
  trigger:
    - platform: event
      event_type: rfxtrx_event
      event_data:
        packet_type: 20
        sub_type: 0
        id_string: "f4ff62:2"
        values:
          Command: 'On'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_2_on", "last_triggered") ) | int > 1 )}}'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_minis
      media_content_id: 'http://192.168.0.24:8123/local/sounds/RemoteOn.mp3'
      media_content_type: 'music'
  - service: shell_command.viera_audio_home_cinema

- alias: LWRF Remote 2 Off
  id: lwrf_remote_2_off
  initial_state: true
  # Go through CCTV feeds on TV
  trigger:
    - platform: event
      event_type: rfxtrx_event
      event_data:
        packet_type: 20
        sub_type: 0
        id_string: "f4ff62:2"
        values:
          Command: 'Off'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_2_off", "last_triggered") ) | int > 1 )}}'
  action:
  - service: input_select.select_previous
    data:
      entity_id: input_select.mm_cam_feed
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_minis
      media_content_id: 'http://192.168.0.24:8123/local/sounds/RemoteOn.mp3'
      media_content_type: 'audio/mp3'




- alias: LWRF Remote 3 On
  id: lwrf_remote_3_on
  initial_state: true
  # Unmute ChromeCasts
  trigger:
    - platform: event
      event_type: rfxtrx_event
      event_data:
        packet_type: 20
        sub_type: 0
        id_string: "f4ff62:3"
        values:
          Command: 'On'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_3_on", "last_triggered") ) | int > 1 )}}'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.office_nest_hub #conservatory, media_player.house, media_player.kitchen, media_player.living_room, media_player.onkyo_tx_nr656
      is_volume_muted: false

- alias: LWRF Remote 3 Off
  id: lwrf_remote_3_off
  initial_state: true
  # Mute ChromeCasts
  trigger:
    - platform: event
      event_type: rfxtrx_event
      event_data:
        packet_type: 20
        sub_type: 0
        id_string: "f4ff62:3"
        values:
          Command: 'Off'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_3_off", "last_triggered") ) | int > 1 )}}'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.office_nest_hub #conservatory, media_player.house, media_player.kitchen, media_player.living_room, media_player.onkyo_tx_nr656
      is_volume_muted: true
