- alias: LWRF Remote 1 On
  initial_state: true
  # Kitchen lights on
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.lwrf_remote_1
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_1_on", "last_triggered") | default(0)) | int > 1 )}}'
    - condition: state
      entity_id: switch.lwrf_remote_1
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: group.kitchen
      brightness: 255
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_minis
      media_content_id: 'http://192.168.0.24/audio/RemoteOn.mp3'
      media_content_type: 'audio/mp3'


- alias: LWRF Remote 1 Off
  initial_state: true
  # Kitchen lights on
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.lwrf_remote_1
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_1_off", "last_triggered") | default(0)) | int > 1 )}}'
    - condition: state
      entity_id: switch.lwrf_remote_1
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: group.kitchen
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_minis
      media_content_id: 'http://192.168.0.24/audio/RemoteOff.mp3'
      media_content_type: 'audio/mp3'



- alias: LWRF Remote 2 On
  initial_state: true
  # Go through CCTV feeds on TV
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.lwrf_remote_2
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_2_on", "last_triggered") | default(0)) | int > 1 )}}'
  action:
  - service: input_select.select_next
    data:
      entity_id: input_select.mm_cam_feed
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_minis
      media_content_id: 'http://192.168.0.24/audio/RemoteOn.mp3'
      media_content_type: 'audio/mp3'




- alias: LWRF Remote 3 On
  initial_state: true
  # Unmute ChromeCasts
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.lwrf_remote_3
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_3_on", "last_triggered") | default(0)) | int > 1 )}}'
    - condition: state
      entity_id: switch.lwrf_remote_3
      state: 'on'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.house
      is_volume_muted: false

- alias: LWRF Remote 3 Off
  initial_state: true
  # Mute ChromeCasts
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.lwrf_remote_3
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_3_off", "last_triggered") | default(0)) | int > 1 )}}'
    - condition: state
      entity_id: switch.lwrf_remote_3
      state: 'off'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.house
      is_volume_muted: true
