- alias: Nest Hub - Start Cast
  id: nest_hub_start_cast
  initial_state: true
  trigger:
    - platform: time_pattern
      # minutes: '/10'
      seconds: '/30'
  condition:
    - condition: template
      value_template: '{{now().hour >= 19 and now().hour < 24 }}'
    - condition: template
      value_template: '{{ states("person.laurent") == "home"}}'
    - condition: template
      value_template: '{{ states("media_player.master_bedroom_nest_hub") != "playing"}}'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.master_bedroom_nest_hub
        volume_level: 0
    - service: script.turn_on
      data:
        entity_id: script.nest_hub_start_cast


- alias: Lights - Lolo Bedside Cabinet - off from Unavailable
  id: lights_lolo_bedside_cabinet_off_from_unavailable
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.lolo_bedside_light
      from: 'unavailable'
  action:
    - service: light.turn_off
      data:
        entity_id: light.lolo_bedside_light


