- alias: Nest Remove Away Mode
  id: nest_remove_away_mode
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'on'
    - platform: state
      entity_id: person.div
      to: 'home'
    - platform: state
      entity_id: person.laurent
      to: 'home'
    - platform: state
      entity_id: input_boolean.holidays
      to: 'off'
    - platform: state
      entity_id: group.door_and_window_sensors
      to: 'off'
    - platform: template
      value_template: '{{ states("device_tracker.laurent") != "home" and distance(states.device_tracker.laurent) < 0.5 }}'
    - platform: template
      value_template: '{{ states("device_tracker.divashni") != "home" and distance(states.device_tracker.divashni) < 0.5 }}'
  condition:
    - condition: state
      entity_id: group.door_and_window_sensors
      state: 'off'
    - condition: state
      entity_id: input_boolean.holidays
      state: 'off'
  action:
    - service: nest.set_away_mode
      data:
        away_mode: home
    - service: climate.set_temperature
      data_template:
        entity_id: climate.hallway
        temperature: >-
          {% if states("sensor.season") == "summer" or states("sensor.season") == "spring" %}18
          {% elif now().hour |int < 22 and now().hour |int > 5 %}20
          {% else  %} 18
          {% endif %}
        hvac_mode: 'heat'


- alias: Nest Set Away Mode
  id: nest_set_away_mode
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.laurent
      from: 'home'
    - platform: state
      entity_id: person.div
      from: 'home'
    - platform: state
      entity_id: input_boolean.holidays
      to: 'on'
    - platform: state
      entity_id: climate.hallway
      to: 'heat'
    - platform: state
      entity_id: group.door_and_window_sensors
      to: 'on'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: climate.hallway
      state: 'heat'
    - condition: state
      entity_id: input_boolean.guests
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("person.laurent") != "home" and states("person.div") != "home"}}'
      - condition: state
        entity_id: group.door_and_window_sensors
        state: 'on'
  action:
    - service: nest.set_away_mode
      data:
        away_mode: home
    - service: climate.set_temperature
      data_template:
        entity_id: climate.hallway
        temperature: '15'
        hvac_mode: 'heat'


- alias: Nest Set ETA
  id: nest_set_eta
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.laurent
      from: 'Verint'
    - platform: state
      entity_id: person.laurent
      from: 'Uncle P'
  condition:
    - condition: time
      after: '15:30:00'
    - condition: template
      value_template: '{{ states("person.div") != "home"}}'
  action:
    - service: nest.set_eta
      data_template:
        eta: '{{ ((states("sensor.lolo_to_home") | int) * 60) | timestamp_custom("%H:%M:00", true)}}'
        trip_id: Lolo Going Home