- alias: Onkyo - Turn On When TV Goes On
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.panasonic_viera_tv
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.doorbell_doorbell_notification", "last_triggered") | default(0)) | int > 30)}}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.hass_start_sound", "last_triggered") | default(0)) | int > 30)}}'
  action:
  - service: media_player.turn_on
    entity_id: media_player.onkyo_tx_nr656

- alias: TV - Set TV To Home cinema when Vol TV changes
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: media_player.panasonic_viera_tv
    value_template: '{{ state_attr("media_player.panasonic_viera_tv", "volume_level") | int }}'
    above: 1
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: media_player.onkyo_tx_nr656
      state: 'on'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'on'
    - condition: template
      value_template: '{{ (as_timestamp(states.media_player.panasonic_viera_tv.last_changed) | int) - (as_timestamp(state_attr("automation.tv_set_tv_to_home_cinema_when_vol_tv_changes", "last_triggered")) | int )  > 0 }}'
  action:
    - service: shell_command.viera_audio_home_cinema