- alias: Onkyo - Turn On When TV Goes On
  id: onkyo_turn_on_when_tv_goes_on
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.panasonic_viera_tv
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.doorbell_doorbell_notification", "last_triggered") | default(0)) | int > 30)}}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.hass_start_sound", "last_triggered") | default(0)) | int > 30)}}'
  action:
  - service: media_player.turn_on
    entity_id: media_player.onkyo_tx_nr656
  # - service: media_player.select_source
  #   data:
  #     entity_id: media_player.onkyo_tx_nr656
  #     source: 'Sky'

- alias: TV - Set TV To Home cinema when Vol TV changes
  id: tv_set_tv_to_home_cinema_when_vol_tv_changes
  initial_state: true
  trigger:
  - platform: template
    value_template: '{{ state_attr("media_player.panasonic_viera_tv", "volume_level") | float * 100 > 1 }}'
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on' 
    # - condition: template
    #   value_template: '{{ state_attr("media_player.panasonic_viera_tv", "volume_level") | float * 100 > 1}}'
    - condition: state
      entity_id: media_player.onkyo_tx_nr656
      state: 'on'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'on'
    - condition: template
      value_template: '{{ (as_timestamp(states.media_player.panasonic_viera_tv.last_changed) | int) - (as_timestamp(this.attributes.last_triggered)) | int  > 0 }}'
    - condition: template
      value_template: '{{ (as_timestamp(states.media_player.panasonic_viera_tv.last_changed) | int) - as_timestamp(states("sensor.uptime")) > 200 }}'
  action:
    - service: remote.send_command
      data:
        entity_id: remote.panasonic_viera_tv
        command: menu
    - delay: 00:00:02
    - service: remote.send_command
      data:
        entity_id: remote.panasonic_viera_tv
        command: down
    - delay: 00:00:01
    - service: remote.send_command
      data:
        entity_id: remote.panasonic_viera_tv
        command: right
    - delay: 00:00:01
    - service: remote.send_command
      data:
        entity_id: remote.panasonic_viera_tv
        command: enter
    - delay: 00:00:01
    - service: remote.send_command
      data:
        entity_id: remote.panasonic_viera_tv
        command: down
    - delay: 00:00:01
    - service: remote.send_command
      data:
        entity_id: remote.panasonic_viera_tv
        command: enter
    - delay: 00:00:05
    - service: remote.send_command
      data:
        entity_id: remote.panasonic_viera_tv
        command: cancel