- alias: Lights - Living Room Main Light On PIR
  id: lights_living_room_main_light_on_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'on'
    - platform: state
      entity_id: binary_sensor.dark
      to: 'on'
    - platform: homeassistant
      event: start
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: light.living_room_main
        state: 'off'
      - condition: template
        value_template: '{{ state_attr("light.living_room_main","brightness") | int < 250 }}'
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lights_living_room_main_light_on_pir","last_triggered") | default(0)) | int > 10 )}}'
    - condition: and
      conditions:
        - condition: state
          entity_id: media_player.panasonic_viera_tv
          state: 'off'
        - condition: state
          entity_id: input_boolean.normal
          state: 'on'
        - condition: or
          conditions:
          - condition: state
            entity_id: binary_sensor.pir_living_room_front
            state: 'on'
          - condition: state
            entity_id: binary_sensor.pir_living_room_back
            state: 'on'
    - condition: state
      entity_id: binary_sensor.dark
      state: 'on'
  action:
  - service: automation.turn_off
    data:
      entity_id: automation.lights_living_room_main_light_dimmed_off_pir,automation.lights_living_room_main_light_off_pir
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 255
  - service: switch.turn_on
    data:
      entity_id: switch.lwrf_socket_3
  - service: automation.turn_on
    data:
      entity_id: automation.lights_living_room_main_light_dimmed_off_pir,automation.lights_living_room_main_light_off_pir


- alias: Lights - Living Room Main Light Dimmed Off PIR
  id: lights_living_room_main_light_dimmed_off_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'off'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_living_room_front
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_living_room_back
      state: 'off'
    - condition: state
      entity_id: light.living_room_main
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 11



- alias: Lights - Living Room Main Light Off PIR
  id: lights_living_room_main_light_off_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'off'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'off'
      for:
        minutes: 2
    - platform: homeassistant
      event: start
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lights_living_room_main_light_dimmed_off_pir", "last_triggered") | default(0)) | int > 120 )}}'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_living_room_front
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_living_room_back
      state: 'off'
    - condition: state
      entity_id: light.living_room_main
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 255
  - delay: 00:00:02
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - service: switch.turn_off
    data:
      entity_id: switch.lwrf_socket_3



- alias: Lights - Living Room Main Light Dimmed
  id: lights_living_room_main_light_dimmed
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.dark
      to: 'on'
    - platform: state
      entity_id: media_player.panasonic_viera_tv
      to: 'on'
    - platform: state
      entity_id: input_boolean.normal
      to: 'on'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lights_living_room_main_light_dimmed", "last_triggered") | default(0)) | int > 10 )}}'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'on'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: binary_sensor.dark
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 11




- alias: Lights - Living Room Main Light UnDimmed
  id: lights_living_room_main_light_undimmed
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.panasonic_viera_tv
      to: 'off'
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("media_player.panasonic_viera_tv","last_updated") | default(0)) | int > 5)}}'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pir_living_room_front
        state: 'on'
      - condition: state
        entity_id: binary_sensor.pir_living_room_back
        state: 'on'
    - condition: state
      entity_id: binary_sensor.dark
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 255

