- alias: Lights - Kitchen Lights On PIR
  id: lights_kitchen_lights_on_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_kitchen
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_presence
      to: 'on'
    - platform: state
      entity_id: input_boolean.dark
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.normal
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.dark
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pir_kitchen
        state: 'on'
      - condition: state
        entity_id: binary_sensor.kitchen_presence
        state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: group.kitchen_lights
        state: 'off'
      - condition: template
        value_template: '{{ state_attr("light.kitchen_window","brightness") | int < 250 }}'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.lights_kitchen_lights_dimmed_off_pir,automation.lights_kitchen_lights_off_pir,automation.lights_kitchen_tv_off_pir
    - service: light.turn_on
      data:
        entity_id: group.kitchen_lights
        brightness: 255
    - service: light.turn_off
      data:
        entity_id: light.hallway
    - service: light.turn_on
      data:
        entity_id: group.kitchen_lights
        brightness: 255
    - service: automation.turn_on
      data:
        entity_id: automation.lights_kitchen_lights_dimmed_off_pir,automation.lights_kitchen_lights_off_pir,automation.lights_kitchen_tv_off_pir
    - delay:
        seconds: 15
    - condition: state
      entity_id: binary_sensor.kitchen_presence
      state: 'off'
    - service: automation.trigger
      data:
        entity_id: automation.lights_kitchen_lights_off_pir


- alias: Lights - Kitchen Lights Dimmed Off PIR
  id: lights_kitchen_lights_dimmed_off_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_presence
      to: 'off'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.kitchen_door
        state: 'on'
      - condition: state
        entity_id: light.kitchen_window
        state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.kitchen_lights
        brightness: 11
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pir_kitchen
        state: 'on'
      - condition: state
        entity_id: binary_sensor.kitchen_presence
        state: 'on'
    - service: light.turn_on
      data:
        entity_id: group.kitchen_lights
        brightness: 255


- alias: Lights - Kitchen Lights Off PIR
  id: lights_kitchen_lights_off_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_presence
      to: 'off'
      for:
        seconds: 30
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.dark
      to: 'off'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: state
      entity_id: binary_sensor.kitchen_presence
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_kitchen
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.kitchen_door
        state: 'on'
      - condition: state
        entity_id: light.kitchen_window
        state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.kitchen_lights
        brightness: 255
    - delay: 00:00:02
    - service: light.turn_off
      data:
        entity_id: group.kitchen_lights
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pir_kitchen
        state: 'on'
      - condition: state
        entity_id: binary_sensor.kitchen_presence
        state: 'on'
    - service: light.turn_on
      data:
        entity_id: group.kitchen_lights
        brightness: 255



- alias: Lights - Kitchen TV On PIR
  id: lights_kitchen_tv_on_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_presence
      to: 'on'
    - platform: homeassistant
      event: start
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.kitchen_tv
  - service: switch.turn_on
    data:
      entity_id: switch.zigbee_round_socket

- alias: Lights - Kitchen TV Off PIR
  id: lights_kitchen_tv_off_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_presence
      to: 'off'
      for:
        minutes: 2
    - platform: state
      entity_id: binary_sensor.conservatory_presence
      to: 'off'
      for:
        minutes: 2
    - platform: homeassistant
      event: start
  condition:
    - condition: template
      value_template: '{{ states("binary_sensor.kitchen_presence") == "off" and states("binary_sensor.conservatory_presence") == "off"}}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(this.attributes.last_triggered) | int > 300)}}'      
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_tv
    - service: shell_command.restart_magic_mirror
    - service: switch.turn_off
      data:
        entity_id: switch.zigbee_round_socket
    - wait_template: "{{ states('binary_sensor.pir_kitchen') == 'on' }}"
      timeout: '00:00:05'
      continue_on_timeout: false
    - service: switch.turn_on
      data:
        entity_id: switch.zigbee_round_socket
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_tv

- alias: Kitchen - Restart MM on TV
  id: kitchen_restart_mm_on_tv
  initial_state: true
  mode: restart
  trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/aqara_toggle_kitchen_tv'
  action:
    - condition: template
      value_template: '{{ trigger.payload_json.click == "single" }}'
    - service: shell_command.restart_magic_mirror