- alias: Lights - Conservatory Lights On PIR
  id: lights_conservatory_lights_on_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_conservatory
      to: 'on'
    - platform: state
      entity_id: input_boolean.dark
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.normal
      to: 'on'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pir_conservatory
        state: 'on'
      - condition: state
        entity_id: binary_sensor.conservatory_presence
        state: 'on'
    - condition: state
      entity_id: input_boolean.dark
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: light.conservatory
        state: 'off'
      - condition: template
        value_template: '{{ state_attr("light.conservatory","brightness") | int < 250 }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.conservatory
        brightness: 255
    - delay: 00:00:02
    - service: light.turn_on
      data:
        entity_id: light.conservatory
        brightness: 255
    - delay:
        seconds: 15
    - condition: state
      entity_id: binary_sensor.conservatory_presence
      state: 'off'
    - service: automation.trigger
      data:
        entity_id: automation.lights_conservatory_lights_off_pir



- alias: Lights - Conservatory Lights Dimmed Off PIR
  id: lights_conservatory_lights_dimmed_off_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.conservatory_presence
      to: 'off'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: state
      entity_id: light.conservatory
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.conservatory
        brightness: 60
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pir_conservatory
        state: 'on'
      - condition: state
        entity_id: binary_sensor.conservatory_presence
        state: 'on'
    - service: light.turn_on
      data:
        entity_id: light.conservatory
        brightness: 255


- alias: Lights - Conservatory Lights Off PIR
  id: lights_conservatory_lights_off_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.conservatory_presence
      to: 'off'
      for:
        seconds: 30
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.dark
      to: 'off'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(this.attributes.last_triggered)) | int > 90 }}'
    - condition: state
      entity_id: binary_sensor.pir_conservatory
      state: 'off'
    - condition: state
      entity_id: binary_sensor.conservatory_presence
      state: 'off'
    - condition: state
      entity_id: light.conservatory
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.conservatory
        brightness: 255
    - delay: 00:00:02
    - service: light.turn_off
      data:
        entity_id: light.conservatory
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.pir_conservatory
        state: 'on'
      - condition: state
        entity_id: binary_sensor.conservatory_presence
        state: 'on'
    - service: light.turn_on
      data:
        entity_id: light.conservatory
        brightness: 255
    - delay: 00:00:02
    - service: light.turn_on
      data:
        entity_id: light.conservatory
        brightness: 255


- alias: Lights - Conservatory LED Lights On PIR
  id: lights_conservatory_led_lights_on_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_conservatory
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_kitchen
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'on'
    - platform: state
      entity_id: input_boolean.dark
      to: 'on'
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: light.wled_conservatory
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: group.pirs
      state: 'on'
    - condition: state
      entity_id: input_boolean.dark
      state: 'on'
    - condition: state
      entity_id: input_select.lights_mode
      state: 'Normal'
  action:
  - service: light.turn_on
    data:
      entity_id: light.wled_conservatory
      effect: "solid"
      brightness: 128
      rgb_color: [191,191,255]
  - delay: 00:00:01
  - service: light.turn_on
    data:
      entity_id: light.wled_conservatory
      effect: "solid"
      brightness: 128
      rgb_color: [191,191,255]

