- alias: Lights - Staircase Light On by PIR
  id: lights_staircase_light_on_by_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_boolean.normal
      to: 'on'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: state
      entity_id: light.staircase
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_staircase
      state: 'on'
    - condition: time
      after: '06:00'
      before: '23:00'
    - condition: state
      entity_id: binary_sensor.dark
      state: 'on'
  action:
  - service: automation.turn_off
    data:
      entity_id: automation.lights_staircase_light_off_by_pir
  - service: light.turn_on
    data:
      entity_id: light.staircase
      brightness: 255
  - service: light.turn_on
    data:
      entity_id: light.staircase_led_strip
      brightness: 255
      rgb_color: [0,128,255]
  - service: automation.turn_on
    data:
      entity_id: automation.lights_staircase_light_off_by_pir
  - condition: template
    value_template: '{{ states("input_select.lights_mode") in ["Diwali", "Xmas"] }}'
  - service: light.turn_on
    data:
      entity_id: light.staircase_led_strip
      brightness: 255
      effect: colorfade_fast


- alias: Lights - Staircase Light Off by PIR
  id: lights_staircase_light_off_by_pir
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'off'
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: binary_sensor.pir_staircase
      state: 'off'
    - condition: state
      entity_id: light.staircase
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.staircase
  - service: light.turn_off
    data:
      entity_id: light.staircase_led_strip