- alias: Pooja - Turn Pooja Frame Off after 3h
  id: pooja_turn_pooja_frame_off_after_3h
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.pooja_frame
      to: 'on'
      for:
        hours: 3
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: light.pooja_frame

- alias: Pooja - Toggle Turn Pooja Frame From Aqara Button
  id: pooja_toggle_turn_pooja_frame_from_aqara_button
  initial_state: true
  trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/aqara_toggle_pooja'
  action:
  - condition: template
    value_template: '{{ trigger.payload_json.click == "single" }}'
  - service: light.toggle
    data:
      entity_id: light.pooja_frame
  - delay:
      milliseconds: 500
  - wait_template: "{{ (as_timestamp(now()) - as_timestamp(states.light.pooja_frame.last_updated)) | int < 5 and is_state('light.pooja_frame', 'on') }}"
    timeout: '00:00:05'
    continue_on_timeout: false
  - service: light.turn_on
    data:
      entity_id: light.pooja_frame
      effect: 'Rainbow'