- alias: Pooja - Turn Pooja Frame Off after 3h
  id: pooja_turn_pooja_frame_off_after_3h
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.pooja_frame
      to: 'on'
      for:
        hours: 3
  condition:
    - condition: state
      entity_id: input_select.lights_mode
      state: 'Normal'
  action:
  - service: light.turn_off
    data:
      entity_id: light.pooja_frame, light.pooja_led_strip

- alias: Pooja - Toggle Turn Pooja Frame From Aqara Button
  id: pooja_toggle_turn_pooja_frame_from_aqara_button
  initial_state: true
  mode: restart
  trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/aqara_toggle_pooja'
  action:
  - condition: template
    value_template: '{{ trigger.payload_json.click == "single" }}'
  - service: light.toggle
    data:
      entity_id: light.pooja_frame, light.pooja_led_strip
  - delay:
      milliseconds: 500
  - wait_template: "{{ (as_timestamp(now()) - as_timestamp(states.light.pooja_frame.last_updated)) | int < 5 and is_state('light.pooja_frame', 'on') }}"
    timeout: '00:00:05'
    continue_on_timeout: false
  - service: light.turn_on
    data:
      entity_id: light.pooja_frame
      effect: 'Rainbow' 
  - service: light.turn_on
    data:
      entity_id: light.pooja_led_strip
      brightness: 255
      rgb_color: [255,255,191]

- alias: Pooja - Toggle Turn Pooja LED Strips From Aqara Button
  id: pooja_toggle_turn_pooja_led_strips_from_aqara_button
  initial_state: true
  mode: restart
  trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/aqara_toggle_pooja'
  action:
  - condition: template
    value_template: '{{ trigger.payload_json.click == "double" }}'
  - service: light.toggle
    data:
      entity_id: light.pooja_led_strip
  - delay:
      milliseconds: 500
  - wait_template: "{{ (as_timestamp(now()) - as_timestamp(states.light.pooja_led_strip.last_updated)) | int < 5 and is_state('light.pooja_led_strip', 'on') }}"
    timeout: '00:00:05'
    continue_on_timeout: false
  - service: light.turn_on
    data:
      entity_id: light.pooja_led_strip
      brightness: 255
      rgb_color: [255,255,191]


- alias: Pooja - Office Nest Hub UnMute
  id: pooja_office_nest_hub_unmute
  initial_state: true
  # Unmute ChromeCasts
  trigger:
    - platform: state
      entity_id: binary_sensor.pooja_door
      to: 'on'
      from: 'off'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_3_on", "last_triggered") ) | int > 1 )}}'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.office_nest_hub #conservatory, media_player.house, media_player.kitchen, media_player.living_room, media_player.onkyo_tx_nr656
      is_volume_muted: false

- alias: Pooja - Office Nest Hub Mute
  id: pooja_office_nest_hub_mute
  initial_state: true
  # Mute ChromeCasts
  trigger:
    - platform: state
      entity_id: binary_sensor.pooja_door
      to: 'off'
      from: 'on'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.lwrf_remote_3_off", "last_triggered") ) | int > 1 )}}'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: media_player.office_nest_hub #conservatory, media_player.house, media_player.kitchen, media_player.living_room, media_player.onkyo_tx_nr656
      is_volume_muted: true