- alias: Presence - Tell Div Lolo left work
  id: presence_tell_div_lolo_left_work
  initial_state: true
  trigger:
    platform: state
    entity_id: person.laurent
    from: "Verint"
  condition:
  - condition: time
    after: '15:30:00'
  action:
    service: notify.gmaildiv
    data_template:
      message: 'Lolo left work. Estimated arrival time: {%if states("device_tracker.220d") == "verint" %} {{(as_timestamp(now()) + (states("sensor.lolo_to_home") | default(0) | int)*60) | timestamp_custom("%H:%M")}}  (by car) {% else %} {{(as_timestamp(now()) + 40 * 60) | timestamp_custom("%H:%M")}} (by bike){% endif %}'



- alias: Presence - Tell Div Lolo reached work
  id: presence_tell_div_lolo_reached_work
  initial_state: true
  trigger:
    platform: state
    entity_id: person.laurent
    to: "Verint"
  condition:
  - condition: time
    before: '10:00:00'
  action:
    service: notify.gmaildiv
    data_template:
      message: 'Lolo reached work.'


- alias: Presence - Tell Lolo Div left work
  id: presence_tell_lolo_div_left_work
  initial_state: true
  trigger:
    platform: state
    entity_id: person.div
    from: "CBC"
  condition:
  - condition: time
    after: '16:00:00'
  action:
    - service: notify.gmaillolo
      data_template:
        title: "HA - Location Update"
        message: 'Div left work. ETA: {{states("sensor.div_to_home")}} min ({{(as_timestamp(now()) + (states("sensor.div_to_home") | default(0) | int)*60) | timestamp_custom("%H:%M")}})'


- alias: Presence - Tell Lolo Div left yoga
  id: presence_tell_lolo_div_left_yoga
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.div
      from: "Ifield College"
    - platform: state
      entity_id: person.div
      from: "Oriel High School"
  condition:
  - condition: time
    after: '19:00:00'
  action:
    - service: notify.gmaillolo
      data_template:
        title: "HA - Location Update"
        message: 'Div left yoga. ETA: {{states("sensor.div_to_home")}} min ({{(as_timestamp(now()) + (states("sensor.div_to_home") | default(0) | int)*60) | timestamp_custom("%H:%M")}})'

- alias: Presence - Switch everything off when we leave home
  id: presence_switch_everything_off_when_we_leave_home
  initial_state: false
  trigger:
    - platform: state
      entity_id: person.div
      from: "home"
    - platform: state
      entity_id: person.laurent
      from: "home"
  condition:
    - condition: template
      value_template: '{{ states("person.laurent") != "home"}}'
    - condition: template
      value_template: '{{ states("person.div") != "home"}}'
  action:
  - service: media_player.turn_off
    entity_id: media_player.kitchen
  - service: media_player.turn_off
    entity_id: media_player.onkyo_tx_nr656
  - service: media_player.turn_off
    entity_id: media_player.conservatory
  - service: media_player.turn_off
    entity_id: media_player.house
  - service: media_player.turn_off
    entity_id: media_player.downstairs
  - service: input_boolean.turn_off
    entity_id: input_boolean.normal
  - service: light.turn_off
    data:
      entity_id: group.interior_lights
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - service: input_boolean.turn_on
    entity_id: input_boolean.silent
  - service: input_boolean.turn_on
    entity_id: input_boolean.normal
  - service: input_boolean.turn_off
    entity_id: input_boolean.silent



- alias: Presence - Tell Lolo of a long drive home
  id: presence_tell_lolo_of_a_long_drive_home
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.lolo_to_home
  condition:
    - condition: time
      after: '15:30:00'
      before: '18:00:00'
      weekday:
        - tue
        - wed
        - thu
    - condition: template
      value_template: '{{ states("sensor.lolo_to_home") |int(0) >= 65 }}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.presence_tell_lolo_of_a_long_drive_home", "last_triggered") | default(0)) | int > 3600)}}'
    - condition: template
      value_template: '{{ states("person.laurent") == "Verint"}}'
  action:
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: notify.gmaillolo
      data_template:
        title: "HA - Long Drive Home"
        message: 'There is a long drive home ({{states("sensor.lolo_to_home") |int(0)}} min)...'




- alias: Presence - location_lolo
  id: presence_location_lolo
  initial_state: true
  trigger:
      - platform: state
        entity_id: person.laurent
  action:
    service: mqtt.publish
    data_template:
      topic: 'location/lolo'
      payload_template: '{{ trigger.to_state.state }}'
      retain: true

- alias: Presence - location_div
  id: presence_location_div
  initial_state: true
  trigger:
      - platform: state
        entity_id: person.div
  action:
    service: mqtt.publish
    data_template:
      topic: 'location/div'
      payload_template: '{{ trigger.to_state.state }}'
      retain: true