- alias: Rain - Clothes Drying Outside
  id: rain_clothes_drying_outside
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.dark_sky_icon
      to: 'rain'
    - platform: state
      entity_id: weather.dark_sky
      to: 'rain'
    - platform: state
      entity_id: sensor.dark_sky_summary
      to: 'Rain'
  condition:
    - condition: state
      entity_id: input_boolean.clothes_drying_outside
      state: 'on'
  action:
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: "Please note: It's about to rain and clothes are drying outside"



- alias: Rain - Reset Clothes Drying Outside Input Boolean
  id: rain_reset_clothes_drying_outside_input_boolean
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "2"
      minutes: 0
      seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.clothes_drying_outside
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.clothes_drying_outside



- alias: Rain - Skylights left open
  id: rain_skylights_left_open
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.dark_sky_icon
      to: 'rain'
    - platform: state
      entity_id: weather.dark_sky
      to: 'rain'
    - platform: state
      entity_id: sensor.dark_sky_summary
      to: 'rain'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.conservatory_skylight_left
        state: 'on'
      - condition: state
        entity_id: binary_sensor.conservatory_skylight_right
        state: 'on'
  action:
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: "Please note: It's about to rain and the conservatory skylights are open"
    - service: notify.gmaillolo
      data:
        title: "HA - Rain Alert"
        message: "Please note: It's about to rain and the conservatory skylights are open"
