- alias: Scene - Holidays
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.holidays
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.holidays

    - service: input_boolean.turn_off
      entity_id: input_boolean.normal
    - service: input_boolean.turn_off
      entity_id: input_boolean.movies
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: 'away'
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Scene, holidays, activated'

- alias: Scene - Movies
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.movies
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.movies

    - service: input_boolean.turn_off
      entity_id: input_boolean.normal
    - service: light.turn_on
      data:
        entity_id: light.living_room_wall
        brightness: 255
    - service: light.turn_off
      data:
        entity_id: light.living_room_main
    - service: light.turn_on
      data:
        entity_id: light.TV_Cabinet_LED_Strip
        brightness: 255
        rgb_color: [0,0,255]
        transition: 1
    - service: light.turn_on
      data:
        entity_id: light.wled_conservatory
        effect: "solid"
        brightness: 128
        rgb_color: [0,0,255]
    - delay: 00:00:01
    - service: light.turn_on
      data:
        entity_id: light.wled_conservatory
        effect: "solid"
        brightness: 128
        rgb_color: [0,0,255]
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    # - service: tts.google_say
      # entity_id: media_player.google_home_minis
      # data:
        # message: 'Scene, movies, activated'

- alias: Scene - Normal
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.normal
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.normal
    - service: input_boolean.turn_off
      entity_id: input_boolean.movies
    - service: input_boolean.turn_off
      entity_id: input_boolean.holidays
    - service: light.turn_off
      data:
        entity_id: light.living_room_wall
    - service: nest.set_away_mode
      data:
        away_mode: home
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    # - service: tts.google_say
      # entity_id: media_player.google_home_minis
      # data:
        # message: 'Scene, normal, activated'



- alias: Scene - Normal from Movies
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.normal
      to: 'on'
    - platform: state
      entity_id: media_player.panasonic_viera_tv
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.movies
      state: 'on'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room_main
        brightness: 255
    - service: light.turn_off
      data:
        entity_id: light.living_room_wall
    - service: input_boolean.turn_on
      entity_id: input_boolean.normal
    - service: light.turn_on
      data:
        entity_id: light.TV_Cabinet_LED_Strip
        brightness: 255
        rgb_color: [0,255,0]
        transition: 1
    - service: light.turn_on
      data:
        entity_id: light.wled_conservatory
        effect: "solid"
        brightness: 128
        rgb_color: [255,255,255]
    - delay: 00:00:01
    - service: light.turn_on
      data:
        entity_id: light.wled_conservatory
        effect: "solid"
        brightness: 128
        rgb_color: [255,255,255]

- alias: Scene - Xmas On
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.xmas
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.xmas
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Scene, christmas, activated'

- alias: Scene - Xmas Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.xmas
      to: 'off'
  action:
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Scene, christmas, de-activated'


- alias: Scene - Guests Mode On
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.venkat
    to: "home"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.guests


- alias: Scene - Guests Mode Off
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.venkat
    from: "home"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.guests

