- alias: Socket - Edimax - Battery Is Charged, Turning Edimax Off
  id: socket_edimax_battery_is_charged_turning_edimax_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.edimax1_watts
  condition:
    - condition: template
      value_template: '{{ states("sensor.edimax1_watts") | float(0)  <= 0.1 }}'
    - condition: template
      value_template: '{{states("sensor.uptime") | float > 0.03}}'
    - condition: state
      entity_id: input_boolean.edimax_charging
      state: 'on'
  action:
    - delay: '0:10:00'
    - condition: template
      value_template: '{{ states("sensor.edimax1_watts") | float(0)  <= 0.1 }}'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.edimax_charging
    - service: switch.turn_off
      data:
        entity_id: switch.edimax1
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Please note: The battery on the Edimax switch is charged'


- alias: Socket - Edimax - Start Charging Battery
  id: socket_edimax_start_charging_battery
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.edimax_charging
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.edimax1
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.edimax1


- alias: Socket - Edimax - Timer
  id: socket_edimax_timer
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_select.edimax_timer
  condition:
    - condition: state
      entity_id: switch.edimax1
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.edimax1
    - choose:
        - conditions:
            - condition: state
              entity_id: input_select.edimax_timer
              state: "No Timer"
          sequence:
            - service: switch.turn_off
              entity_id: switch.edimax1
      default:
        - service: switch.turn_on
          data:
            entity_id: switch.edimax1

- alias: Socket - Xiaomi - Battery Is Charged, Turning Xiaomi Switch Off
  id: socket_xiaomi_battery_is_charged_turning_xiaomi_switch_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.xiaomi_garage_socket_watts
  condition:
    - condition: template
      value_template: '{{ states("sensor.xiaomi_garage_socket_watts") | float(0)  <= 0.1 }}'
    - condition: template
      value_template: '{{states("sensor.uptime") | float > 0.03}}'
    - condition: state
      entity_id: input_boolean.xiaomi_switch_charging
      state: 'on'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.input_boolean.xiaomi_switch_charging.last_changed) | int  > 60)}}'
  action:
    - delay: '0:10:00'
    - condition: template
      value_template: '{{ states("sensor.xiaomi_garage_socket_watts") | float(0)  <= 0.1 }}'
    - service: notify.gmaillolo
      data_template:
        title: "HA - Xiaomi Battery Charged"
        message: 'The battery on the Xiaomi switch is charged. Charging time: {{ (as_timestamp(now()) - as_timestamp(states.input_boolean.xiaomi_switch_charging.last_changed) | int ) | timestamp_custom("%Hh %Mm", true)}}.'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.xiaomi_switch_charging
    - service: switch.turn_off
      data:
        entity_id: switch.xiaomi_garage_socket
    - condition: state
      entity_id: input_boolean.silent
      state: "off"


- alias: Socket - Xiaomi - Start Charging Battery
  id: socket_xiaomi_start_charging_battery
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.xiaomi_switch_charging
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.xiaomi_garage_socket
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.xiaomi_garage_socket


- alias: Socket - Xiaomi - Automatic Battery Charging 
  id: socket_xiaomi_automatic_battery_charging
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.xiaomi_garage_socket
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.xiaomi_switch_charging
      state: 'off'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.socket_xiaomi_automatic_battery_charging.attributes.last_triggered) | int  > 300)}}'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.xiaomi_switch_charging


- alias: Socket - Xiaomi - Charge If No Rain 
  id: socket_xiaomi_charge_if_no_rain
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: "2"
      minutes: 0
      seconds: 0
  condition:
    - condition: time
      weekday:
        - tue
        - wed
        - thu
    - condition: template
      value_template: "{{(state_attr('weather.dark_sky', 'forecast')[0].precipitation|float(0)|round ) < 1}}"
    - condition: template
      value_template: "{{(state_attr('weather.dark_sky', 'forecast')[0].templow | float(0) > 4 ) }}"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.xiaomi_switch_charging

