- alias: Starling - Balance Below £20
  id: starling_balance_below_ps20
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.starling_effective_balance
      below: 10
  action:
    - service: notify.gmaillolo
      data_template:
        title: "HA - Starling"
        message: 'Starling Balance below £10: £{{states("sensor.starling_effective_balance")}}'