- alias: Vacuum - Start Vacuuming
  id: vacuum_start_vacuuming
  initial_state: false
  trigger:
    - platform: time_pattern
      minutes: '/15'
      seconds: 0
  condition:
    - condition: time
      after: '22:30'
      weekday:
        - tue
        - thu
        - sun
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(this.attributes.last_triggered) | int > 36000)}}'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'unavailable'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("media_player.panasonic_viera_tv","last_updated")) | int > 120)}}'
    - condition: state
      entity_id: group.pirs
      state: 'off'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("group.pirs","last_updated")) | int > 120)}}'
    - condition: state
      entity_id: input_boolean.normal
      state: "on"
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.roborock_vacuum



- alias: Vacuum - Started Vacuuming
  id: vacuum_started_vacuuming
  initial_state: true
  trigger:
    - platform: state
      entity_id: vacuum.roborock_vacuum
      to: 'cleaning'
      from: 'docked'
    - platform: state
      entity_id: vacuum.roborock_vacuum
      to: 'cleaning'
      from: 'idle'
  action:
    - service: notify.gmaillolo
      data_template:
        title: "HA - Vacuum Started"
        message: 'Mi Robot Started Vacuuming...'



- alias: Vacuum Error - continue
  id: vacuum_error_continue
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.xiaomi_status
      to: 'Status: Error'
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.vacuum_error_stop", "last_triggered")) | int > 1800)}}'
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.roborock_vacuum



- alias: Vacuum Error - stop
  id: vacuum_error_stop
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.xiaomi_status
      to: 'Status: Error'
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.vacuum_error_continue", "last_triggered")) | int < 1800)}}'
  action:
    - delay:
        seconds: 59
    - condition: template
      value_template: '{{states("sensor.xiaomi_status") == "Status: Error"}}'
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Please note: Looks like something is wrong with the Vacuum...'
    - service: notify.gmaillolo
      data:
        title: "HA - Vacuum Problem"
        message: 'Looks like something is wrong with the Vacuum...'
        data:
          images:
            - /config/www/navmap.png


- alias: Vacuum - Finished Vacuuming
  id: vacuum_finished_vacuuming
  initial_state: true
  trigger:
    - platform: state
      entity_id: vacuum.roborock_vacuum
      to: 'returning to dock'
    - platform: state
      entity_id: vacuum.roborock_vacuum
      to: 'returning'
  action:
    - service: notify.gmaillolo
      data_template:
        title: "HA - Vacuum Finished"
        message: |
          Mi Robot finished Vacuuming...
          Cleaned {{ state_attr("vacuum.roborock_vacuum","cleaned_area") }} m² in {{ state_attr("vacuum.roborock_vacuum","cleaning_time") }} min.
        data:
          images:
            - /config/www/navmap.png
    - service: notify.gmaildiv
      data_template:
        title: "HA - Vacuum Finished"
        message: |
          Mi Robot finished Vacuuming...
          Cleaned {{ state_attr("vacuum.roborock_vacuum","cleaned_area") }} m² in {{ state_attr("vacuum.roborock_vacuum","cleaning_time") }} min.
        data:
          images:
            - /config/www/navmap.png
    - service: input_boolean.turn_off
      entity_id: input_boolean.vacuum

- alias: Vacuum - Scheduled Vacuuming
  id: vacuum_scheduled_vacuuming
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.laurent
      from: "home"
    - platform: state
      entity_id: person.div
      from: "home"
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: "on"
    - condition: template
      value_template: '{{ states("person.laurent") != "home"}}'
    - condition: template
      value_template: '{{ states("person.div") != "home"}}'
    - condition: state
      entity_id: input_boolean.scheduled_vacuuming
      state: "on"
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.roborock_vacuum
    - service: input_boolean.turn_off
      entity_id: input_boolean.scheduled_vacuuming