- alias: MiBox - Turn Movies on when Kodi is Playing
  id: mibox_turn_movies_on_when_kodi_is_playing
  initial_state: false
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'playing'
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: template
      value_template: '{{state_attr("media_player.kodi","media_title").split(" ")[0] != "Pups"}}'
    - condition: state
      entity_id: input_boolean.dark
      state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.movies

- alias: MiBox - Turn Movies on when Netflix or Prime is Playing
  id: mibox_turn_movies_on_when_netflix_or_prime_is_playing
  initial_state: false
  trigger:
    platform: state
    entity_id: media_player.mi_box3_adtv
    to: 'playing'
    for:
      minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: template
      value_template: '{{state_attr("media_player.mi_box3_adtv","app_name") == "com.amazon.amazonvideo.livingroom" or state_attr("media_player.mi_box3_adtv","app_name") == "Netflix" or state_attr("media_player.mi_box3_adtv","app_name") ==  "com.disney.disneyplus" }}'
    - condition: state
      entity_id: input_boolean.dark
      state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.movies