- alias: Xmas Lights On
  id: xmas_lights_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.pir_conservatory
        - binary_sensor.pir_kitchen
        - binary_sensor.pir_living_room_front
        - binary_sensor.pir_living_room_back
        - binary_sensor.pir_staircase
      to: 'on'
    - platform: state
      entity_id: input_select.lights_mode
      to: 'Xmas'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'on'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: group.pirs
      state: 'on'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.lwrf_socket_xmas
  - service: light.turn_on
    data:
      entity_id: light.TV_Cabinet_LED_Strip
      brightness: 255
      effect: colorfade_fast
  - service: switch.turn_on
    data:
      entity_id: switch.edimax1
  - service: light.turn_on
    data:
      entity_id: group.xmas

  - condition: state
    entity_id: light.wled_conservatory
    state: 'off'
  - service: light.turn_on
    data:
      entity_id: light.wled_conservatory
      effect: "rainbow"
      brightness: 255




- alias: Xmas Lights Off
  id: xmas_lights_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: input_select.lights_mode
      state: 'Xmas'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: group.xmas
  - service: light.turn_off
    data:
      entity_id: light.TV_Cabinet_LED_Strip
  - service: switch.turn_off
    data:
      entity_id: switch.lwrf_socket_xmas
  - service: light.turn_off
    data:
      entity_id: light.wled_conservatory
  - service: switch.turn_off
    data:
      entity_id: switch.edimax1




- alias: Xmas Turn Baubles On 1
  id: xmas_turn_baubles_on_1
  initial_state: true
  trigger:
    - platform: template
      value_template: '{{states("sensor.bauble_random_effect") | int == 1 }}'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: group.pirs
        state: 'on'
      - condition: state
        entity_id: media_player.panasonic_viera_tv
        state: 'on'
    - condition: state
      entity_id: input_select.lights_mode
      state: 'Xmas'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.bauble_1
      effect: "sparkle"
  - service: light.turn_on
    data:
      entity_id: light.bauble_2
      effect: "rainbow"
  - service: light.turn_on
    data:
      entity_id: light.bauble_3
      effect: "uniglow"

- alias: Xmas Turn Baubles On 2
  id: xmas_turn_baubles_on_2
  initial_state: true
  trigger:
    - platform: template
      value_template: '{{states("sensor.bauble_random_effect") | int == 2 }}'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: group.pirs
        state: 'on'
      - condition: state
        entity_id: media_player.panasonic_viera_tv
        state: 'on'
    - condition: state
      entity_id: input_select.lights_mode
      state: 'Xmas'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.bauble_2
      effect: "sparkle"
  - service: light.turn_on
    data:
      entity_id: light.bauble_3
      effect: "rainbow"
  - service: light.turn_on
    data:
      entity_id: light.bauble_1
      effect: "uniglow"

- alias: Xmas Turn Baubles On 3
  id: xmas_turn_baubles_on_3
  initial_state: true
  trigger:
    - platform: template
      value_template: '{{states("sensor.bauble_random_effect") | int == 3 }}'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: group.pirs
        state: 'on'
      - condition: state
        entity_id: media_player.panasonic_viera_tv
        state: 'on'
    - condition: state
      entity_id: input_select.lights_mode
      state: 'Xmas'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.bauble_3
      effect: "sparkle"
  - service: light.turn_on
    data:
      entity_id: light.bauble_1
      effect: "rainbow"
  - service: light.turn_on
    data:
      entity_id: light.bauble_2
      effect: "uniglow"

- alias: Xmas - Change Conservatory WLED Effect
  id: xmas_change_conservatory_wled_effect
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: group.pirs
        state: 'on'
      - condition: state
        entity_id: media_player.panasonic_viera_tv
        state: 'on'
    - condition: state
      entity_id: light.wled_conservatory
      state: 'on'
    - condition: state
      entity_id: input_select.lights_mode
      state: 'Xmas'
  action:
  - service: light.turn_on
    data:
      entity_id: light.wled_conservatory
      brightness: 128
      effect: '{{states.input_select.wled_effects.attributes.options[range(0, 14) | random]}}'

- alias: Xmas - Change Garage WLED Effect
  id: xmas_change_garage_wled_effect
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '15:00'
    - condition: state
      entity_id: input_select.lights_mode
      state: 'Xmas'
  action:
  - service: light.turn_on
    data:
      entity_id: light.wled_garage
      brightness: 128
      effect: '{{states.input_select.wled_effects.attributes.options[range(0, 14) | random]}}'
  - delay: 00:00:01
  - service: light.turn_on
    data:
      entity_id: light.house_number
      brightness: 255
      effect: None
      rgb_color: [0,0,255]

- alias: Halloween - Change Garage WLED Effect
  id: halloween_change_garage_wled_effect
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 0
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '15:00'
    - condition: state
      entity_id: input_select.lights_mode
      state: 'Halloween'
  action:
  - service: light.turn_on
    data:
      entity_id: light.wled_garage
      brightness: 128
      effect: '{{states.input_select.wled_effects_halloween.attributes.options[range(0, 12) | random]}}'
      rgb_color: [255, 128, 0]
  - delay: 00:00:01
  - service: light.turn_on
    data:
      entity_id: light.house_number
      brightness: 255
      effect: None
      rgb_color: [255, 128, 0]