- alias: Zigbee - ZigBee2MQTT Docker Down
  id: zigbee_zigbee2mqtt_docker_down
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.zigbee2mqtt
      to: 'off'
      for:
        minutes: 2
  action:
    service: notify.gmaillolo
    data:
      title: "HA - ZigBee2MQTT Docker Down"
      message: 'Warning - ZigBee2MQTT Docker Container Is Down'