- platform: onkyo
  host: 192.168.0.26
  name: Onkyo TX-NR656
  sources:
    video6: 'Main PC'
    bluray: 'Blu-Ray'
    video2: 'Sky'
    cd:  'ChromeCast1'
    network: 'ChromeCast'
    tv: 'TV'
    strm-box: 'ChromeCast2'
- platform: panasonic_viera
  name: Panasonic Viera TV
  host: 192.168.0.27
  mac: D8:AF:F1:47:7A:16
- platform: mpd
  host: 192.168.0.21
  port: 6600
  name: MPD RPi Kitchen
- platform: androidtv
  host: 192.168.0.28
  name: Mi Box3 ADTV
- platform: androidtv
  host: 192.168.0.29
  name: Fire Stick 4K
  state_detection_rules:
    'Amazon Video':
      - 'playing':
          'media_session_state': 3
      - 'paused':
          'media_session_state': 2
      - 'idle'
  get_sources: false
    
# - platform: universal
#   name: Kello
#   state_template: >
#     {% if is_state('media_player.kodi', 'idle') and is_state('input_boolean.kodi_tv_state', 'off') %}
#     off
#     {% else %}
#     {{ states('media_player.kodi') }}
#     {% endif %}
#   commands:
#     turn_on:
#       service: mqtt.publish
#       data:
#         topic: "Kello/PlayStatus"
#         payload_template: 'ON'
#         retain: False
#     turn_off:
#       service: mqtt.publish
#       data:
#         topic: "Kello/PlayStatus"
#         payload_template: 'OFF'
#         retain: false
#     volume_set:
#       service: mqtt.publish
#       data:
#         topic: "Kello/Volume"
#         payload_template: '{{ volume_level | int(value,16) }}'
#         retain: false
#     media_play:
#       service: mqtt.publish
#       data:
#         topic: "Kello/PlayStatus"
#         payload_template: 'ON'
#         retain: False
#     media_stop:
#       service: mqtt.publish
#       data:
#         topic: "Kello/PlayStatus"
#         payload_template: 'OFF'
#         retain: false
  # attributes:
  #   is_volume_muted: ENTITY_ID|ATTRIBUTE
  #   state: ENTITY_ID|ATTRIBUTE
  # device_class: tv