- platform: onkyo
  host: 192.168.9.26
  name: Onkyo TX-NR656
  sources:
    video2: 'Sky'
    video6: 'Main PC'
    bluray: 'Blu-Ray'
    cd:  'ChromeCast1'
    network: 'ChromeCast'
    tv: 'TV'
    strm-box: 'ChromeCast2'
# - platform: panasonic_viera
#   name: Panasonic Viera TV
#   host: 192.168.9.27
#   mac: D8:AF:F1:47:7A:16
- platform: mpd
  host: 192.168.9.21
  port: 6600
  name: MPD RPi Kitchen
- platform: androidtv
  host: 192.168.9.28
  name: Mi Box3 ADTV
- platform: androidtv
  host: 192.168.9.29
  name: Fire Stick 4K
  state_detection_rules:
    'Amazon Video':
      - 'playing':
          'media_session_state': 3
      - 'paused':
          'media_session_state': 2
      - 'idle'
  get_sources: false