- platform: onkyo
  host: 192.168.9.26
  name: Onkyo TX-NR656
  sources:
    video2: 'Sky'
    video6: 'Main PC'
    bluray: 'Blu-Ray'
    cd:  'ChromeCast1'
    network: 'ChromeCast'
    tv: 'TV'
    strm-box: 'ChromeCast2'
# - platform: androidtv
#   host: 192.168.9.29
#   name: Fire Stick 4K
#   state_detection_rules:
#     'Amazon Video':
#       - 'playing':
#           'media_session_state': 3
#       - 'paused':
#           'media_session_state': 2
#       - 'idle'
#     'uk.co.bbc.iplayer':
#       - 'playing':
#           'wake_lock_size': 4
#       - 'paused':
#           'wake_lock_size': 3
#       - 'paused':
#           'wake_lock_size': 2
#       - 'idle'
#   get_sources: false
# - platform: androidtv
#   host: 192.168.9.28
#   name: Fire Stick 4K Max
#   state_detection_rules:
#     'Amazon Video':
#       - 'playing':
#           'media_session_state': 3
#       - 'paused':
#           'media_session_state': 2
#       - 'idle'
#     'uk.co.bbc.iplayer':
#       - 'playing':
#           'wake_lock_size': 4
#       - 'paused':
#           'wake_lock_size': 3
#       - 'paused':
#           'wake_lock_size': 2
#       - 'idle'
#   get_sources: false